# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.BatchCreateProductVariantsResponseValue201ApplicationJsonPropertyDataItemPropertyPricing do
  @moduledoc """
  BatchCreateProductVariantsResponseValue201ApplicationJsonPropertyDataItemPropertyPricing model.
  """

  defstruct [
    :humble,
    :frequency,
    :type,
    :price,
    __additional_properties__: %{},
    __present_fields__: []
  ]

  @type t :: %__MODULE__{
          humble: boolean(),
          frequency:
            SellApp.BatchCreateProductVariantsResponseValue201ApplicationJsonPropertyDataItemPropertyPricingPropertyFrequency.t(),
          type: String.t(),
          price:
            SellApp.BatchCreateProductVariantsResponseValue201ApplicationJsonPropertyDataItemPropertyPricingPropertyPrice.t(),
          __additional_properties__: map(),
          __present_fields__: [String.t()]
        }

  @schema %{
    name:
      "BatchCreateProductVariantsResponseValue201ApplicationJsonPropertyDataItemPropertyPricing",
    properties: %{
      "humble" => %{required: true, schema: %{kind: :boolean}},
      "frequency" => %{
        required: true,
        schema: %{
          kind: :model,
          module:
            SellApp.BatchCreateProductVariantsResponseValue201ApplicationJsonPropertyDataItemPropertyPricingPropertyFrequency
        }
      },
      "type" => %{required: true, schema: %{kind: :string}},
      "price" => %{
        required: true,
        schema: %{
          kind: :model,
          module:
            SellApp.BatchCreateProductVariantsResponseValue201ApplicationJsonPropertyDataItemPropertyPricingPropertyPrice
        }
      }
    },
    additional_properties: true
  }
  @doc false
  def schema, do: @schema

  @doc false
  @spec from_map(map()) :: t()
  def from_map(map) when is_map(map) do
    SellApp.Schema.validate_model!(map, @schema, :response)

    %__MODULE__{
      humble: map["humble"],
      frequency:
        SellApp.Cast.nested(
          map["frequency"],
          &SellApp.BatchCreateProductVariantsResponseValue201ApplicationJsonPropertyDataItemPropertyPricingPropertyFrequency.from_map/1
        ),
      type: map["type"],
      price:
        SellApp.Cast.nested(
          map["price"],
          &SellApp.BatchCreateProductVariantsResponseValue201ApplicationJsonPropertyDataItemPropertyPricingPropertyPrice.from_map/1
        ),
      __additional_properties__: Map.drop(map, ["humble", "frequency", "type", "price"]),
      __present_fields__: Map.keys(map)
    }
  end

  @doc false
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    known =
      SellApp.Cast.keep_present(
        %{
          "humble" => struct.humble,
          "frequency" =>
            SellApp.Cast.dump_struct(
              struct.frequency,
              &SellApp.BatchCreateProductVariantsResponseValue201ApplicationJsonPropertyDataItemPropertyPricingPropertyFrequency.to_map/1
            ),
          "type" => struct.type,
          "price" =>
            SellApp.Cast.dump_struct(
              struct.price,
              &SellApp.BatchCreateProductVariantsResponseValue201ApplicationJsonPropertyDataItemPropertyPricingPropertyPrice.to_map/1
            )
        },
        ["humble", "frequency", "type", "price"],
        struct.__present_fields__
      )

    Map.merge(struct.__additional_properties__, known)
  end
end
