# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.BlacklistType do
  @moduledoc """
  BlacklistType enum.
  """

  @type t :: :asn | :country | :email | :ip | :wildcard_email

  @doc "All known values."
  @spec values() :: [t()]
  def values, do: [:asn, :country, :email, :ip, :wildcard_email]

  @doc "Casts a wire string to its atom; unknown values pass through unchanged."
  @spec cast(String.t() | nil) :: t() | String.t() | nil
  def cast("ASN"), do: :asn
  def cast("COUNTRY"), do: :country
  def cast("EMAIL"), do: :email
  def cast("IP"), do: :ip
  def cast("WILDCARD_EMAIL"), do: :wildcard_email
  def cast(other), do: other

  @doc "Dumps an atom back to its wire string."
  @spec dump(t() | String.t()) :: String.t()
  def dump(:asn), do: "ASN"
  def dump(:country), do: "COUNTRY"
  def dump(:email), do: "EMAIL"
  def dump(:ip), do: "IP"
  def dump(:wildcard_email), do: "WILDCARD_EMAIL"
  def dump(other) when is_binary(other), do: other
end
