# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.CoursesSections do
  @moduledoc """
  Operations for the CoursesSections API.
  """

  @doc """
  Create a course section

  Append a section to a course curriculum. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.

  ## Parameters

    * `course` — The course path parameter.
    * `params` — request body map
    * `opts` — per-request options (see `SellApp.Client.request/5`)
  """
  @spec create(SellApp.Client.t(), String.t(), map(), keyword()) ::
          {:ok, SellApp.SdkCreateCourseSectionResponseValue201ApplicationJson.t()}
          | {:error, SellApp.Error.error()}
  def create(client, course, params \\ %{}, opts \\ []) do
    SellApp.Schema.validate_value!(
      params,
      %{kind: :model, module: SellApp.SdkCreateCourseSectionRequestApplicationJson},
      :request,
      "$request.body"
    )

    with {:ok, body} <-
           SellApp.Client.request(
             client,
             :post,
             "/v2/courses/#{URI.encode(course, &URI.char_unreserved?/1)}/sections",
             params,
             Keyword.put(
               Keyword.put(opts, :request_body, true),
               :operation_id,
               "createCourseSection"
             )
           ) do
      raw_response = if match?(%SellApp.Response{}, body), do: body, else: nil
      body = if raw_response, do: raw_response.data, else: body

      SellApp.Schema.validate_value!(
        body,
        %{kind: :model, module: SellApp.SdkCreateCourseSectionResponseValue201ApplicationJson},
        :response,
        "$response"
      )

      result =
        SellApp.Cast.nested(
          body,
          &SellApp.SdkCreateCourseSectionResponseValue201ApplicationJson.from_map/1
        )

      {:ok, if(raw_response, do: %{raw_response | data: result}, else: result)}
    end
  end

  @doc """
  Update a course section

  Update a section title or sanitized rich-text description. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.

  ## Parameters

    * `course` — The course path parameter.
    * `section` — The section path parameter.
    * `params` — request body map
    * `opts` — per-request options (see `SellApp.Client.request/5`)
  """
  @spec replace(SellApp.Client.t(), String.t(), String.t(), map(), keyword()) ::
          {:ok, SellApp.SdkReplaceCourseSectionResponseValue200ApplicationJson.t()}
          | {:error, SellApp.Error.error()}
  def replace(client, course, section, params \\ %{}, opts \\ []) do
    SellApp.Schema.validate_value!(
      params,
      %{kind: :model, module: SellApp.SdkReplaceCourseSectionRequestApplicationJson},
      :request,
      "$request.body"
    )

    with {:ok, body} <-
           SellApp.Client.request(
             client,
             :put,
             "/v2/courses/#{URI.encode(course, &URI.char_unreserved?/1)}/sections/#{URI.encode(section, &URI.char_unreserved?/1)}",
             params,
             Keyword.put(
               Keyword.put(opts, :request_body, true),
               :operation_id,
               "replaceCourseSection"
             )
           ) do
      raw_response = if match?(%SellApp.Response{}, body), do: body, else: nil
      body = if raw_response, do: raw_response.data, else: body

      SellApp.Schema.validate_value!(
        body,
        %{kind: :model, module: SellApp.SdkReplaceCourseSectionResponseValue200ApplicationJson},
        :response,
        "$response"
      )

      result =
        SellApp.Cast.nested(
          body,
          &SellApp.SdkReplaceCourseSectionResponseValue200ApplicationJson.from_map/1
        )

      {:ok, if(raw_response, do: %{raw_response | data: result}, else: result)}
    end
  end

  @doc """
  Update a course section

  Update a section title or sanitized rich-text description. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.

  ## Parameters

    * `course` — The course path parameter.
    * `section` — The section path parameter.
    * `params` — request body map
    * `opts` — per-request options (see `SellApp.Client.request/5`)
  """
  @spec update(SellApp.Client.t(), String.t(), String.t(), map(), keyword()) ::
          {:ok, SellApp.SdkUpdateCourseSectionResponseValue200ApplicationJson.t()}
          | {:error, SellApp.Error.error()}
  def update(client, course, section, params \\ %{}, opts \\ []) do
    SellApp.Schema.validate_value!(
      params,
      %{kind: :model, module: SellApp.SdkUpdateCourseSectionRequestApplicationJson},
      :request,
      "$request.body"
    )

    with {:ok, body} <-
           SellApp.Client.request(
             client,
             :patch,
             "/v2/courses/#{URI.encode(course, &URI.char_unreserved?/1)}/sections/#{URI.encode(section, &URI.char_unreserved?/1)}",
             params,
             Keyword.put(
               Keyword.put(opts, :request_body, true),
               :operation_id,
               "updateCourseSection"
             )
           ) do
      raw_response = if match?(%SellApp.Response{}, body), do: body, else: nil
      body = if raw_response, do: raw_response.data, else: body

      SellApp.Schema.validate_value!(
        body,
        %{kind: :model, module: SellApp.SdkUpdateCourseSectionResponseValue200ApplicationJson},
        :response,
        "$response"
      )

      result =
        SellApp.Cast.nested(
          body,
          &SellApp.SdkUpdateCourseSectionResponseValue200ApplicationJson.from_map/1
        )

      {:ok, if(raw_response, do: %{raw_response | data: result}, else: result)}
    end
  end

  @doc """
  Delete a course section

  Delete a section, its lessons, structured questions, attachments, and video references, then normalize remaining section order. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.

  ## Parameters

    * `course` — The course path parameter.
    * `section` — The section path parameter.
    * `opts` — per-request options (see `SellApp.Client.request/5`)
  """
  @spec delete(SellApp.Client.t(), String.t(), String.t(), keyword()) ::
          {:ok, SellApp.SdkDeleteCourseSectionResponseValue200ApplicationJson.t()}
          | {:error, SellApp.Error.error()}
  def delete(client, course, section, opts \\ []) do
    with {:ok, body} <-
           SellApp.Client.request(
             client,
             :delete,
             "/v2/courses/#{URI.encode(course, &URI.char_unreserved?/1)}/sections/#{URI.encode(section, &URI.char_unreserved?/1)}",
             %{},
             Keyword.put(opts, :operation_id, "deleteCourseSection")
           ) do
      raw_response = if match?(%SellApp.Response{}, body), do: body, else: nil
      body = if raw_response, do: raw_response.data, else: body

      SellApp.Schema.validate_value!(
        body,
        %{kind: :model, module: SellApp.SdkDeleteCourseSectionResponseValue200ApplicationJson},
        :response,
        "$response"
      )

      result =
        SellApp.Cast.nested(
          body,
          &SellApp.SdkDeleteCourseSectionResponseValue200ApplicationJson.from_map/1
        )

      {:ok, if(raw_response, do: %{raw_response | data: result}, else: result)}
    end
  end

  @doc """
  Reorder course sections

  Replace the complete section order. Send every section ID exactly once in the desired order. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.

  ## Parameters

    * `course` — The course path parameter.
    * `params` — request body map
    * `opts` — per-request options (see `SellApp.Client.request/5`)
  """
  @spec reorder(SellApp.Client.t(), String.t(), map(), keyword()) ::
          {:ok, SellApp.SdkReorderCourseSectionsResponseValue200ApplicationJson.t()}
          | {:error, SellApp.Error.error()}
  def reorder(client, course, params \\ %{}, opts \\ []) do
    SellApp.Schema.validate_value!(
      params,
      %{kind: :model, module: SellApp.SdkReorderCourseSectionsRequestApplicationJson},
      :request,
      "$request.body"
    )

    with {:ok, body} <-
           SellApp.Client.request(
             client,
             :patch,
             "/v2/courses/#{URI.encode(course, &URI.char_unreserved?/1)}/sections/reorder",
             params,
             Keyword.put(
               Keyword.put(opts, :request_body, true),
               :operation_id,
               "reorderCourseSections"
             )
           ) do
      raw_response = if match?(%SellApp.Response{}, body), do: body, else: nil
      body = if raw_response, do: raw_response.data, else: body

      SellApp.Schema.validate_value!(
        body,
        %{kind: :model, module: SellApp.SdkReorderCourseSectionsResponseValue200ApplicationJson},
        :response,
        "$response"
      )

      result =
        SellApp.Cast.nested(
          body,
          &SellApp.SdkReorderCourseSectionsResponseValue200ApplicationJson.from_map/1
        )

      {:ok, if(raw_response, do: %{raw_response | data: result}, else: result)}
    end
  end
end
