# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.CreateStoreResponseValue201ApplicationJsonPropertyData do
  @moduledoc """
  CreateStoreResponseValue201ApplicationJsonPropertyData model.
  """

  defstruct [
    :id,
    :slug,
    :name,
    :visibility,
    :storefront_url,
    :dashboard_url,
    __additional_properties__: %{},
    __present_fields__: []
  ]

  @type t :: %__MODULE__{
          id: String.t(),
          slug: String.t(),
          name: String.t(),
          visibility: SellApp.StoreVisibility.t(),
          storefront_url: String.t(),
          dashboard_url: String.t(),
          __additional_properties__: map(),
          __present_fields__: [String.t()]
        }

  @schema %{
    name: "CreateStoreResponseValue201ApplicationJsonPropertyData",
    properties: %{
      "id" => %{required: true, schema: %{kind: :string}},
      "slug" => %{required: true, schema: %{kind: :string}},
      "name" => %{required: true, schema: %{kind: :string}},
      "visibility" => %{
        required: true,
        schema: %{kind: :enum, values: ["PUBLIC", "HIDDEN", "PRIVATE"]}
      },
      "storefront_url" => %{required: true, schema: %{kind: :string, format: "uri"}},
      "dashboard_url" => %{required: true, schema: %{kind: :string, format: "uri"}}
    },
    additional_properties: true
  }
  @doc false
  def schema, do: @schema

  @doc false
  @spec from_map(map()) :: t()
  def from_map(map) when is_map(map) do
    SellApp.Schema.validate_model!(map, @schema, :response)

    %__MODULE__{
      id: map["id"],
      slug: map["slug"],
      name: map["name"],
      visibility: SellApp.Cast.enum(map["visibility"], &SellApp.StoreVisibility.cast/1),
      storefront_url: map["storefront_url"],
      dashboard_url: map["dashboard_url"],
      __additional_properties__:
        Map.drop(map, ["id", "slug", "name", "visibility", "storefront_url", "dashboard_url"]),
      __present_fields__: Map.keys(map)
    }
  end

  @doc false
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    known =
      SellApp.Cast.keep_present(
        %{
          "id" => struct.id,
          "slug" => struct.slug,
          "name" => struct.name,
          "visibility" => SellApp.Cast.enum(struct.visibility, &SellApp.StoreVisibility.dump/1),
          "storefront_url" => struct.storefront_url,
          "dashboard_url" => struct.dashboard_url
        },
        ["id", "slug", "name", "visibility", "storefront_url", "dashboard_url"],
        struct.__present_fields__
      )

    Map.merge(struct.__additional_properties__, known)
  end
end
