# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.CreateCustomerSessionRequestApplicationJsonOneOfValue2 do
  @moduledoc """
  CreateCustomerSessionRequestApplicationJsonOneOfValue2 model.
  """

  defstruct [
    :external_customer_id,
    __additional_properties__: %{},
    __present_fields__: []
  ]

  @type t :: %__MODULE__{
          external_customer_id: String.t(),
          __additional_properties__: map(),
          __present_fields__: [String.t()]
        }

  @schema %{
    name: "CreateCustomerSessionRequestApplicationJsonOneOfValue2",
    properties: %{"external_customer_id" => %{required: true, schema: %{kind: :string}}},
    additional_properties: false
  }
  @doc false
  def schema, do: @schema

  @doc false
  @spec from_map(map()) :: t()
  def from_map(map) when is_map(map) do
    SellApp.Schema.validate_model!(map, @schema, :response)

    %__MODULE__{
      external_customer_id: map["external_customer_id"],
      __additional_properties__: Map.drop(map, ["external_customer_id"]),
      __present_fields__: Map.keys(map)
    }
  end

  @doc false
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    known =
      SellApp.Cast.keep_present(
        %{
          "external_customer_id" => struct.external_customer_id
        },
        ["external_customer_id"],
        struct.__present_fields__
      )

    Map.merge(struct.__additional_properties__, known)
  end
end
