# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.CreateExportResponseValue201ApplicationJsonPropertyDataPropertyParameters do
  @moduledoc """
  CreateExportResponseValue201ApplicationJsonPropertyDataPropertyParameters model.
  """

  defstruct [
    :from,
    :to,
    :report_type,
    __additional_properties__: %{},
    __present_fields__: []
  ]

  @type t :: %__MODULE__{
          from: String.t() | nil,
          to: String.t() | nil,
          report_type:
            SellApp.CreateExportResponseValue201ApplicationJsonPropertyDataPropertyParametersReportType.t()
            | nil,
          __additional_properties__: map(),
          __present_fields__: [String.t()]
        }

  @schema %{
    name: "CreateExportResponseValue201ApplicationJsonPropertyDataPropertyParameters",
    properties: %{
      "from" => %{
        required: false,
        schema: %{kind: :nullable, inner: %{kind: :string, format: "date"}}
      },
      "to" => %{
        required: false,
        schema: %{kind: :nullable, inner: %{kind: :string, format: "date"}}
      },
      "report_type" => %{required: false, schema: %{kind: :enum, values: ["summary", "detailed"]}}
    },
    additional_properties: true
  }
  @doc false
  def schema, do: @schema

  @doc false
  @spec from_map(map()) :: t()
  def from_map(map) when is_map(map) do
    SellApp.Schema.validate_model!(map, @schema, :response)

    %__MODULE__{
      from: map["from"],
      to: map["to"],
      report_type:
        SellApp.Cast.enum(
          map["report_type"],
          &SellApp.CreateExportResponseValue201ApplicationJsonPropertyDataPropertyParametersReportType.cast/1
        ),
      __additional_properties__: Map.drop(map, ["from", "to", "report_type"]),
      __present_fields__: Map.keys(map)
    }
  end

  @doc false
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    known =
      SellApp.Cast.keep_present(
        %{
          "from" => struct.from,
          "to" => struct.to,
          "report_type" =>
            SellApp.Cast.enum(
              struct.report_type,
              &SellApp.CreateExportResponseValue201ApplicationJsonPropertyDataPropertyParametersReportType.dump/1
            )
        },
        [],
        struct.__present_fields__
      )

    Map.merge(struct.__additional_properties__, known)
  end
end
