# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.CreateCourseLessonResponseValue201ApplicationJsonPropertyDataPropertyVideo do
  @moduledoc """
  CreateCourseLessonResponseValue201ApplicationJsonPropertyDataPropertyVideo model.
  """

  defstruct [
    :source,
    :external_url,
    :mux_playback_id,
    :mux_status,
    :duration_seconds,
    __additional_properties__: %{},
    __present_fields__: []
  ]

  @type t :: %__MODULE__{
          source:
            SellApp.CreateCourseLessonResponseValue201ApplicationJsonPropertyDataPropertyVideoSource.t(),
          external_url: String.t() | nil,
          mux_playback_id: String.t() | nil,
          mux_status: String.t() | nil,
          duration_seconds: integer() | nil,
          __additional_properties__: map(),
          __present_fields__: [String.t()]
        }

  @schema %{
    name: "CreateCourseLessonResponseValue201ApplicationJsonPropertyDataPropertyVideo",
    properties: %{
      "source" => %{required: true, schema: %{kind: :enum, values: ["mux", "external"]}},
      "external_url" => %{
        required: true,
        schema: %{kind: :nullable, inner: %{kind: :string, format: "uri"}}
      },
      "mux_playback_id" => %{required: true, schema: %{kind: :nullable, inner: %{kind: :string}}},
      "mux_status" => %{required: true, schema: %{kind: :nullable, inner: %{kind: :string}}},
      "duration_seconds" => %{
        required: true,
        schema: %{kind: :nullable, inner: %{kind: :integer, minimum: 0}}
      }
    },
    additional_properties: true
  }
  @doc false
  def schema, do: @schema

  @doc false
  @spec from_map(map()) :: t()
  def from_map(map) when is_map(map) do
    SellApp.Schema.validate_model!(map, @schema, :response)

    %__MODULE__{
      source:
        SellApp.Cast.enum(
          map["source"],
          &SellApp.CreateCourseLessonResponseValue201ApplicationJsonPropertyDataPropertyVideoSource.cast/1
        ),
      external_url: map["external_url"],
      mux_playback_id: map["mux_playback_id"],
      mux_status: map["mux_status"],
      duration_seconds: map["duration_seconds"],
      __additional_properties__:
        Map.drop(map, [
          "source",
          "external_url",
          "mux_playback_id",
          "mux_status",
          "duration_seconds"
        ]),
      __present_fields__: Map.keys(map)
    }
  end

  @doc false
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    known =
      SellApp.Cast.keep_present(
        %{
          "source" =>
            SellApp.Cast.enum(
              struct.source,
              &SellApp.CreateCourseLessonResponseValue201ApplicationJsonPropertyDataPropertyVideoSource.dump/1
            ),
          "external_url" => struct.external_url,
          "mux_playback_id" => struct.mux_playback_id,
          "mux_status" => struct.mux_status,
          "duration_seconds" => struct.duration_seconds
        },
        ["source", "external_url", "mux_playback_id", "mux_status", "duration_seconds"],
        struct.__present_fields__
      )

    Map.merge(struct.__additional_properties__, known)
  end
end
