# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.CreateDynamicDeliveryRetryResponseValue200ApplicationJsonPropertyData do
  @moduledoc """
  CreateDynamicDeliveryRetryResponseValue200ApplicationJsonPropertyData model.
  """

  defstruct [
    :queued,
    __additional_properties__: %{},
    __present_fields__: []
  ]

  @type t :: %__MODULE__{
          queued: boolean(),
          __additional_properties__: map(),
          __present_fields__: [String.t()]
        }

  @schema %{
    name: "CreateDynamicDeliveryRetryResponseValue200ApplicationJsonPropertyData",
    properties: %{"queued" => %{required: true, schema: %{kind: :boolean}}},
    additional_properties: true
  }
  @doc false
  def schema, do: @schema

  @doc false
  @spec from_map(map()) :: t()
  def from_map(map) when is_map(map) do
    SellApp.Schema.validate_model!(map, @schema, :response)

    %__MODULE__{
      queued: map["queued"],
      __additional_properties__: Map.drop(map, ["queued"]),
      __present_fields__: Map.keys(map)
    }
  end

  @doc false
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    known =
      SellApp.Cast.keep_present(
        %{
          "queued" => struct.queued
        },
        ["queued"],
        struct.__present_fields__
      )

    Map.merge(struct.__additional_properties__, known)
  end
end
