# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.CreateInvoiceRefundResponseValue200ApplicationJsonPropertyDataPropertyInvoicePropertyStatus do
  @moduledoc """
  CreateInvoiceRefundResponseValue200ApplicationJsonPropertyDataPropertyInvoicePropertyStatus model.
  """

  defstruct [
    :history,
    :status,
    __additional_properties__: %{},
    __present_fields__: []
  ]

  @type t :: %__MODULE__{
          history: [
            SellApp.CreateInvoiceRefundResponseValue200ApplicationJsonPropertyDataPropertyInvoicePropertyStatusPropertyHistoryItem.t()
          ],
          status:
            SellApp.CreateInvoiceRefundResponseValue200ApplicationJsonPropertyDataPropertyInvoicePropertyStatusPropertyStatus.t(),
          __additional_properties__: map(),
          __present_fields__: [String.t()]
        }

  @schema %{
    name:
      "CreateInvoiceRefundResponseValue200ApplicationJsonPropertyDataPropertyInvoicePropertyStatus",
    properties: %{
      "history" => %{
        required: true,
        schema: %{
          kind: :array,
          items: %{
            kind: :model,
            module:
              SellApp.CreateInvoiceRefundResponseValue200ApplicationJsonPropertyDataPropertyInvoicePropertyStatusPropertyHistoryItem
          }
        }
      },
      "status" => %{
        required: true,
        schema: %{
          kind: :model,
          module:
            SellApp.CreateInvoiceRefundResponseValue200ApplicationJsonPropertyDataPropertyInvoicePropertyStatusPropertyStatus
        }
      }
    },
    additional_properties: true
  }
  @doc false
  def schema, do: @schema

  @doc false
  @spec from_map(map()) :: t()
  def from_map(map) when is_map(map) do
    SellApp.Schema.validate_model!(map, @schema, :response)

    %__MODULE__{
      history:
        SellApp.Cast.list(
          map["history"],
          &SellApp.CreateInvoiceRefundResponseValue200ApplicationJsonPropertyDataPropertyInvoicePropertyStatusPropertyHistoryItem.from_map/1
        ),
      status:
        SellApp.Cast.nested(
          map["status"],
          &SellApp.CreateInvoiceRefundResponseValue200ApplicationJsonPropertyDataPropertyInvoicePropertyStatusPropertyStatus.from_map/1
        ),
      __additional_properties__: Map.drop(map, ["history", "status"]),
      __present_fields__: Map.keys(map)
    }
  end

  @doc false
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    known =
      SellApp.Cast.keep_present(
        %{
          "history" =>
            SellApp.Cast.list(struct.history, fn item ->
              SellApp.Cast.dump_struct(
                item,
                &SellApp.CreateInvoiceRefundResponseValue200ApplicationJsonPropertyDataPropertyInvoicePropertyStatusPropertyHistoryItem.to_map/1
              )
            end),
          "status" =>
            SellApp.Cast.dump_struct(
              struct.status,
              &SellApp.CreateInvoiceRefundResponseValue200ApplicationJsonPropertyDataPropertyInvoicePropertyStatusPropertyStatus.to_map/1
            )
        },
        ["history", "status"],
        struct.__present_fields__
      )

    Map.merge(struct.__additional_properties__, known)
  end
end
