# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.CreateInvoiceResponseValue201ApplicationJsonPropertyData do
  @moduledoc """
  CreateInvoiceResponseValue201ApplicationJsonPropertyData model.
  """

  defstruct [
    :id,
    :payment,
    :status,
    :webhooks,
    :feedback,
    :created_at,
    :updated_at,
    :store_id,
    :coupon_id,
    :subscription_id,
    :checkout,
    :customer_information,
    __additional_properties__: %{},
    __present_fields__: []
  ]

  @type t :: %__MODULE__{
          id: integer(),
          payment:
            SellApp.CreateInvoiceResponseValue201ApplicationJsonPropertyDataPropertyPayment.t(),
          status:
            SellApp.CreateInvoiceResponseValue201ApplicationJsonPropertyDataPropertyStatus.t(),
          webhooks: [
            SellApp.CreateInvoiceResponseValue201ApplicationJsonPropertyDataPropertyWebhooksItem.t()
          ],
          feedback: String.t() | nil,
          created_at: String.t(),
          updated_at: String.t(),
          store_id: integer(),
          coupon_id: integer() | nil,
          subscription_id: integer() | nil,
          checkout: String.t() | nil,
          customer_information:
            SellApp.CreateInvoiceResponseValue201ApplicationJsonPropertyDataPropertyCustomerInformation.t(),
          __additional_properties__: map(),
          __present_fields__: [String.t()]
        }

  @schema %{
    name: "CreateInvoiceResponseValue201ApplicationJsonPropertyData",
    properties: %{
      "id" => %{required: true, schema: %{kind: :integer}},
      "payment" => %{
        required: true,
        schema: %{
          kind: :model,
          module: SellApp.CreateInvoiceResponseValue201ApplicationJsonPropertyDataPropertyPayment
        }
      },
      "status" => %{
        required: true,
        schema: %{
          kind: :model,
          module: SellApp.CreateInvoiceResponseValue201ApplicationJsonPropertyDataPropertyStatus
        }
      },
      "webhooks" => %{
        required: true,
        schema: %{
          kind: :array,
          items: %{
            kind: :model,
            module:
              SellApp.CreateInvoiceResponseValue201ApplicationJsonPropertyDataPropertyWebhooksItem
          }
        }
      },
      "feedback" => %{required: true, schema: %{kind: :nullable, inner: %{kind: :string}}},
      "created_at" => %{required: true, schema: %{kind: :string, format: "date-time"}},
      "updated_at" => %{required: true, schema: %{kind: :string, format: "date-time"}},
      "store_id" => %{required: true, schema: %{kind: :integer}},
      "coupon_id" => %{required: true, schema: %{kind: :nullable, inner: %{kind: :integer}}},
      "subscription_id" => %{required: true, schema: %{kind: :nullable, inner: %{kind: :integer}}},
      "checkout" => %{required: true, schema: %{kind: :nullable, inner: %{kind: :string}}},
      "customer_information" => %{
        required: true,
        schema: %{
          kind: :model,
          module:
            SellApp.CreateInvoiceResponseValue201ApplicationJsonPropertyDataPropertyCustomerInformation
        }
      }
    },
    additional_properties: true
  }
  @doc false
  def schema, do: @schema

  @doc false
  @spec from_map(map()) :: t()
  def from_map(map) when is_map(map) do
    SellApp.Schema.validate_model!(map, @schema, :response)

    %__MODULE__{
      id: map["id"],
      payment:
        SellApp.Cast.nested(
          map["payment"],
          &SellApp.CreateInvoiceResponseValue201ApplicationJsonPropertyDataPropertyPayment.from_map/1
        ),
      status:
        SellApp.Cast.nested(
          map["status"],
          &SellApp.CreateInvoiceResponseValue201ApplicationJsonPropertyDataPropertyStatus.from_map/1
        ),
      webhooks:
        SellApp.Cast.list(
          map["webhooks"],
          &SellApp.CreateInvoiceResponseValue201ApplicationJsonPropertyDataPropertyWebhooksItem.from_map/1
        ),
      feedback: map["feedback"],
      created_at: map["created_at"],
      updated_at: map["updated_at"],
      store_id: map["store_id"],
      coupon_id: map["coupon_id"],
      subscription_id: map["subscription_id"],
      checkout: map["checkout"],
      customer_information:
        SellApp.Cast.nested(
          map["customer_information"],
          &SellApp.CreateInvoiceResponseValue201ApplicationJsonPropertyDataPropertyCustomerInformation.from_map/1
        ),
      __additional_properties__:
        Map.drop(map, [
          "id",
          "payment",
          "status",
          "webhooks",
          "feedback",
          "created_at",
          "updated_at",
          "store_id",
          "coupon_id",
          "subscription_id",
          "checkout",
          "customer_information"
        ]),
      __present_fields__: Map.keys(map)
    }
  end

  @doc false
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    known =
      SellApp.Cast.keep_present(
        %{
          "id" => struct.id,
          "payment" =>
            SellApp.Cast.dump_struct(
              struct.payment,
              &SellApp.CreateInvoiceResponseValue201ApplicationJsonPropertyDataPropertyPayment.to_map/1
            ),
          "status" =>
            SellApp.Cast.dump_struct(
              struct.status,
              &SellApp.CreateInvoiceResponseValue201ApplicationJsonPropertyDataPropertyStatus.to_map/1
            ),
          "webhooks" =>
            SellApp.Cast.list(struct.webhooks, fn item ->
              SellApp.Cast.dump_struct(
                item,
                &SellApp.CreateInvoiceResponseValue201ApplicationJsonPropertyDataPropertyWebhooksItem.to_map/1
              )
            end),
          "feedback" => struct.feedback,
          "created_at" => struct.created_at,
          "updated_at" => struct.updated_at,
          "store_id" => struct.store_id,
          "coupon_id" => struct.coupon_id,
          "subscription_id" => struct.subscription_id,
          "checkout" => struct.checkout,
          "customer_information" =>
            SellApp.Cast.dump_struct(
              struct.customer_information,
              &SellApp.CreateInvoiceResponseValue201ApplicationJsonPropertyDataPropertyCustomerInformation.to_map/1
            )
        },
        [
          "id",
          "payment",
          "status",
          "webhooks",
          "feedback",
          "created_at",
          "updated_at",
          "store_id",
          "coupon_id",
          "subscription_id",
          "checkout",
          "customer_information"
        ],
        struct.__present_fields__
      )

    Map.merge(struct.__additional_properties__, known)
  end
end
