# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.CreateGroupResponseValue201ApplicationJsonPropertyDataPropertyImage do
  @moduledoc """
  The stored group image, or null when the group has none.
  """

  defstruct [
    :path,
    :metadata,
    __additional_properties__: %{},
    __present_fields__: []
  ]

  @type t :: %__MODULE__{
          path: String.t() | nil,
          metadata:
            SellApp.CreateGroupResponseValue201ApplicationJsonPropertyDataPropertyImageValuePropertyMetadata.t()
            | nil,
          __additional_properties__: map(),
          __present_fields__: [String.t()]
        }

  @schema %{
    name: "CreateGroupResponseValue201ApplicationJsonPropertyDataPropertyImage",
    properties: %{
      "path" => %{required: false, schema: %{kind: :string}},
      "metadata" => %{
        required: false,
        schema: %{
          kind: :model,
          module:
            SellApp.CreateGroupResponseValue201ApplicationJsonPropertyDataPropertyImageValuePropertyMetadata
        }
      }
    },
    additional_properties: true
  }
  @doc false
  def schema, do: @schema

  @doc false
  @spec from_map(map()) :: t()
  def from_map(map) when is_map(map) do
    SellApp.Schema.validate_model!(map, @schema, :response)

    %__MODULE__{
      path: map["path"],
      metadata:
        SellApp.Cast.nested(
          map["metadata"],
          &SellApp.CreateGroupResponseValue201ApplicationJsonPropertyDataPropertyImageValuePropertyMetadata.from_map/1
        ),
      __additional_properties__: Map.drop(map, ["path", "metadata"]),
      __present_fields__: Map.keys(map)
    }
  end

  @doc false
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    known =
      SellApp.Cast.keep_present(
        %{
          "path" => struct.path,
          "metadata" =>
            SellApp.Cast.dump_struct(
              struct.metadata,
              &SellApp.CreateGroupResponseValue201ApplicationJsonPropertyDataPropertyImageValuePropertyMetadata.to_map/1
            )
        },
        [],
        struct.__present_fields__
      )

    Map.merge(struct.__additional_properties__, known)
  end
end
