# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.CreateInvoiceRefundResponseValue200ApplicationJsonPropertyDataPropertyRefund do
  @moduledoc """
  CreateInvoiceRefundResponseValue200ApplicationJsonPropertyDataPropertyRefund model.
  """

  defstruct [
    :status,
    :provider,
    :provider_refund_id,
    :amount_cents,
    :currency,
    __additional_properties__: %{},
    __present_fields__: []
  ]

  @type t :: %__MODULE__{
          status:
            SellApp.CreateInvoiceRefundResponseValue200ApplicationJsonPropertyDataPropertyRefundStatus.t(),
          provider: String.t() | nil,
          provider_refund_id: String.t() | nil,
          amount_cents: integer() | nil,
          currency: String.t() | nil,
          __additional_properties__: map(),
          __present_fields__: [String.t()]
        }

  @schema %{
    name: "CreateInvoiceRefundResponseValue200ApplicationJsonPropertyDataPropertyRefund",
    properties: %{
      "status" => %{
        required: true,
        schema: %{kind: :enum, values: ["pending", "effective", "failed", "cancelled"]}
      },
      "provider" => %{required: true, schema: %{kind: :nullable, inner: %{kind: :string}}},
      "provider_refund_id" => %{
        required: true,
        schema: %{kind: :nullable, inner: %{kind: :string}}
      },
      "amount_cents" => %{required: true, schema: %{kind: :nullable, inner: %{kind: :integer}}},
      "currency" => %{required: true, schema: %{kind: :nullable, inner: %{kind: :string}}}
    },
    additional_properties: true
  }
  @doc false
  def schema, do: @schema

  @doc false
  @spec from_map(map()) :: t()
  def from_map(map) when is_map(map) do
    SellApp.Schema.validate_model!(map, @schema, :response)

    %__MODULE__{
      status:
        SellApp.Cast.enum(
          map["status"],
          &SellApp.CreateInvoiceRefundResponseValue200ApplicationJsonPropertyDataPropertyRefundStatus.cast/1
        ),
      provider: map["provider"],
      provider_refund_id: map["provider_refund_id"],
      amount_cents: map["amount_cents"],
      currency: map["currency"],
      __additional_properties__:
        Map.drop(map, ["status", "provider", "provider_refund_id", "amount_cents", "currency"]),
      __present_fields__: Map.keys(map)
    }
  end

  @doc false
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    known =
      SellApp.Cast.keep_present(
        %{
          "status" =>
            SellApp.Cast.enum(
              struct.status,
              &SellApp.CreateInvoiceRefundResponseValue200ApplicationJsonPropertyDataPropertyRefundStatus.dump/1
            ),
          "provider" => struct.provider,
          "provider_refund_id" => struct.provider_refund_id,
          "amount_cents" => struct.amount_cents,
          "currency" => struct.currency
        },
        ["status", "provider", "provider_refund_id", "amount_cents", "currency"],
        struct.__present_fields__
      )

    Map.merge(struct.__additional_properties__, known)
  end
end
