# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.CreatePaymentConnectionHandoffResponseValue200ApplicationJsonPropertyData do
  @moduledoc """
  CreatePaymentConnectionHandoffResponseValue200ApplicationJsonPropertyData model.
  """

  defstruct [
    :payment_method,
    :connect_url,
    :status_url,
    :expires_at,
    __additional_properties__: %{},
    __present_fields__: []
  ]

  @type t :: %__MODULE__{
          payment_method: String.t(),
          connect_url: String.t(),
          status_url: String.t(),
          expires_at: String.t(),
          __additional_properties__: map(),
          __present_fields__: [String.t()]
        }

  @schema %{
    name: "CreatePaymentConnectionHandoffResponseValue200ApplicationJsonPropertyData",
    properties: %{
      "payment_method" => %{required: true, schema: %{kind: :string}},
      "connect_url" => %{required: true, schema: %{kind: :string, format: "uri"}},
      "status_url" => %{required: true, schema: %{kind: :string, format: "uri"}},
      "expires_at" => %{required: true, schema: %{kind: :string, format: "date-time"}}
    },
    additional_properties: true
  }
  @doc false
  def schema, do: @schema

  @doc false
  @spec from_map(map()) :: t()
  def from_map(map) when is_map(map) do
    SellApp.Schema.validate_model!(map, @schema, :response)

    %__MODULE__{
      payment_method: map["payment_method"],
      connect_url: map["connect_url"],
      status_url: map["status_url"],
      expires_at: map["expires_at"],
      __additional_properties__:
        Map.drop(map, ["payment_method", "connect_url", "status_url", "expires_at"]),
      __present_fields__: Map.keys(map)
    }
  end

  @doc false
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    known =
      SellApp.Cast.keep_present(
        %{
          "payment_method" => struct.payment_method,
          "connect_url" => struct.connect_url,
          "status_url" => struct.status_url,
          "expires_at" => struct.expires_at
        },
        ["payment_method", "connect_url", "status_url", "expires_at"],
        struct.__present_fields__
      )

    Map.merge(struct.__additional_properties__, known)
  end
end
