# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.CreateInvoiceResponseValue201ApplicationJsonPropertyDataPropertyCustomerInformationPropertyVat do
  @moduledoc """
  CreateInvoiceResponseValue201ApplicationJsonPropertyDataPropertyCustomerInformationPropertyVat model.
  """

  defstruct [
    :amount,
    :country,
    __additional_properties__: %{},
    __present_fields__: []
  ]

  @type t :: %__MODULE__{
          amount: String.t(),
          country: String.t() | nil,
          __additional_properties__: map(),
          __present_fields__: [String.t()]
        }

  @schema %{
    name:
      "CreateInvoiceResponseValue201ApplicationJsonPropertyDataPropertyCustomerInformationPropertyVat",
    properties: %{
      "amount" => %{required: true, schema: %{kind: :string}},
      "country" => %{required: true, schema: %{kind: :nullable, inner: %{kind: :string}}}
    },
    additional_properties: true
  }
  @doc false
  def schema, do: @schema

  @doc false
  @spec from_map(map()) :: t()
  def from_map(map) when is_map(map) do
    SellApp.Schema.validate_model!(map, @schema, :response)

    %__MODULE__{
      amount: map["amount"],
      country: map["country"],
      __additional_properties__: Map.drop(map, ["amount", "country"]),
      __present_fields__: Map.keys(map)
    }
  end

  @doc false
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    known =
      SellApp.Cast.keep_present(
        %{
          "amount" => struct.amount,
          "country" => struct.country
        },
        ["amount", "country"],
        struct.__present_fields__
      )

    Map.merge(struct.__additional_properties__, known)
  end
end
