# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.GetInvoiceResponseValue200ApplicationJsonPropertyDataPropertyPaymentPropertyGateway do
  @moduledoc """
  GetInvoiceResponseValue200ApplicationJsonPropertyDataPropertyPaymentPropertyGateway model.
  """

  defstruct [
    :data,
    :type,
    __additional_properties__: %{},
    __present_fields__: []
  ]

  @type t :: %__MODULE__{
          data:
            SellApp.GetInvoiceResponseValue200ApplicationJsonPropertyDataPropertyPaymentPropertyGatewayPropertyData.t(),
          type: String.t(),
          __additional_properties__: map(),
          __present_fields__: [String.t()]
        }

  @schema %{
    name: "GetInvoiceResponseValue200ApplicationJsonPropertyDataPropertyPaymentPropertyGateway",
    properties: %{
      "data" => %{
        required: true,
        schema: %{
          kind: :model,
          module:
            SellApp.GetInvoiceResponseValue200ApplicationJsonPropertyDataPropertyPaymentPropertyGatewayPropertyData
        }
      },
      "type" => %{required: true, schema: %{kind: :string}}
    },
    additional_properties: true
  }
  @doc false
  def schema, do: @schema

  @doc false
  @spec from_map(map()) :: t()
  def from_map(map) when is_map(map) do
    SellApp.Schema.validate_model!(map, @schema, :response)

    %__MODULE__{
      data:
        SellApp.Cast.nested(
          map["data"],
          &SellApp.GetInvoiceResponseValue200ApplicationJsonPropertyDataPropertyPaymentPropertyGatewayPropertyData.from_map/1
        ),
      type: map["type"],
      __additional_properties__: Map.drop(map, ["data", "type"]),
      __present_fields__: Map.keys(map)
    }
  end

  @doc false
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    known =
      SellApp.Cast.keep_present(
        %{
          "data" =>
            SellApp.Cast.dump_struct(
              struct.data,
              &SellApp.GetInvoiceResponseValue200ApplicationJsonPropertyDataPropertyPaymentPropertyGatewayPropertyData.to_map/1
            ),
          "type" => struct.type
        },
        ["data", "type"],
        struct.__present_fields__
      )

    Map.merge(struct.__additional_properties__, known)
  end
end
