# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.GetPaymentMethodStatusResponseValue200ApplicationJsonPropertyDataHealthStatus do
  @moduledoc """
  GetPaymentMethodStatusResponseValue200ApplicationJsonPropertyDataHealthStatus enum.
  """

  @type t :: :disconnected | :healthy | :attention_required

  @doc "All known values."
  @spec values() :: [t()]
  def values, do: [:disconnected, :healthy, :attention_required]

  @doc "Casts a wire string to its atom; unknown values pass through unchanged."
  @spec cast(String.t() | nil) :: t() | String.t() | nil
  def cast("disconnected"), do: :disconnected
  def cast("healthy"), do: :healthy
  def cast("attention_required"), do: :attention_required
  def cast(other), do: other

  @doc "Dumps an atom back to its wire string."
  @spec dump(t() | String.t()) :: String.t()
  def dump(:disconnected), do: "disconnected"
  def dump(:healthy), do: "healthy"
  def dump(:attention_required), do: "attention_required"
  def dump(other) when is_binary(other), do: other
end
