# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.GetOrderLineItemResponseValue200ApplicationJsonPropertyDataPropertyPromotion do
  @moduledoc """
  GetOrderLineItemResponseValue200ApplicationJsonPropertyDataPropertyPromotion model.
  """

  defstruct [
    :phase_id,
    :promotion_id,
    :name,
    :discount_type,
    :discount_value,
    __additional_properties__: %{},
    __present_fields__: []
  ]

  @type t :: %__MODULE__{
          phase_id: integer(),
          promotion_id: integer(),
          name: String.t() | nil,
          discount_type: String.t() | nil,
          discount_value: String.t() | nil,
          __additional_properties__: map(),
          __present_fields__: [String.t()]
        }

  @schema %{
    name: "GetOrderLineItemResponseValue200ApplicationJsonPropertyDataPropertyPromotion",
    properties: %{
      "phase_id" => %{required: true, schema: %{kind: :integer}},
      "promotion_id" => %{required: true, schema: %{kind: :integer}},
      "name" => %{required: true, schema: %{kind: :nullable, inner: %{kind: :string}}},
      "discount_type" => %{required: false, schema: %{kind: :nullable, inner: %{kind: :string}}},
      "discount_value" => %{required: false, schema: %{kind: :string}}
    },
    additional_properties: true
  }
  @doc false
  def schema, do: @schema

  @doc false
  @spec from_map(map()) :: t()
  def from_map(map) when is_map(map) do
    SellApp.Schema.validate_model!(map, @schema, :response)

    %__MODULE__{
      phase_id: map["phase_id"],
      promotion_id: map["promotion_id"],
      name: map["name"],
      discount_type: map["discount_type"],
      discount_value: map["discount_value"],
      __additional_properties__:
        Map.drop(map, ["phase_id", "promotion_id", "name", "discount_type", "discount_value"]),
      __present_fields__: Map.keys(map)
    }
  end

  @doc false
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    known =
      SellApp.Cast.keep_present(
        %{
          "phase_id" => struct.phase_id,
          "promotion_id" => struct.promotion_id,
          "name" => struct.name,
          "discount_type" => struct.discount_type,
          "discount_value" => struct.discount_value
        },
        ["phase_id", "promotion_id", "name"],
        struct.__present_fields__
      )

    Map.merge(struct.__additional_properties__, known)
  end
end
