# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.GetInvoiceResponseValue200ApplicationJsonPropertyDataPropertyPayment do
  @moduledoc """
  GetInvoiceResponseValue200ApplicationJsonPropertyDataPropertyPayment model.
  """

  defstruct [
    :fee,
    :gateway,
    :subtotal,
    :expires_at,
    :full_price,
    :original_amount,
    __additional_properties__: %{},
    __present_fields__: []
  ]

  @type t :: %__MODULE__{
          fee:
            SellApp.GetInvoiceResponseValue200ApplicationJsonPropertyDataPropertyPaymentPropertyFee.t(),
          gateway:
            SellApp.GetInvoiceResponseValue200ApplicationJsonPropertyDataPropertyPaymentPropertyGateway.t(),
          subtotal:
            SellApp.GetInvoiceResponseValue200ApplicationJsonPropertyDataPropertyPaymentPropertySubtotal.t(),
          expires_at: String.t(),
          full_price:
            SellApp.GetInvoiceResponseValue200ApplicationJsonPropertyDataPropertyPaymentPropertyFullPrice.t(),
          original_amount:
            SellApp.GetInvoiceResponseValue200ApplicationJsonPropertyDataPropertyPaymentPropertyOriginalAmount.t(),
          __additional_properties__: map(),
          __present_fields__: [String.t()]
        }

  @schema %{
    name: "GetInvoiceResponseValue200ApplicationJsonPropertyDataPropertyPayment",
    properties: %{
      "fee" => %{
        required: true,
        schema: %{
          kind: :model,
          module:
            SellApp.GetInvoiceResponseValue200ApplicationJsonPropertyDataPropertyPaymentPropertyFee
        }
      },
      "gateway" => %{
        required: true,
        schema: %{
          kind: :model,
          module:
            SellApp.GetInvoiceResponseValue200ApplicationJsonPropertyDataPropertyPaymentPropertyGateway
        }
      },
      "subtotal" => %{
        required: true,
        schema: %{
          kind: :model,
          module:
            SellApp.GetInvoiceResponseValue200ApplicationJsonPropertyDataPropertyPaymentPropertySubtotal
        }
      },
      "expires_at" => %{required: true, schema: %{kind: :string, format: "date-time"}},
      "full_price" => %{
        required: true,
        schema: %{
          kind: :model,
          module:
            SellApp.GetInvoiceResponseValue200ApplicationJsonPropertyDataPropertyPaymentPropertyFullPrice
        }
      },
      "original_amount" => %{
        required: true,
        schema: %{
          kind: :model,
          module:
            SellApp.GetInvoiceResponseValue200ApplicationJsonPropertyDataPropertyPaymentPropertyOriginalAmount
        }
      }
    },
    additional_properties: true
  }
  @doc false
  def schema, do: @schema

  @doc false
  @spec from_map(map()) :: t()
  def from_map(map) when is_map(map) do
    SellApp.Schema.validate_model!(map, @schema, :response)

    %__MODULE__{
      fee:
        SellApp.Cast.nested(
          map["fee"],
          &SellApp.GetInvoiceResponseValue200ApplicationJsonPropertyDataPropertyPaymentPropertyFee.from_map/1
        ),
      gateway:
        SellApp.Cast.nested(
          map["gateway"],
          &SellApp.GetInvoiceResponseValue200ApplicationJsonPropertyDataPropertyPaymentPropertyGateway.from_map/1
        ),
      subtotal:
        SellApp.Cast.nested(
          map["subtotal"],
          &SellApp.GetInvoiceResponseValue200ApplicationJsonPropertyDataPropertyPaymentPropertySubtotal.from_map/1
        ),
      expires_at: map["expires_at"],
      full_price:
        SellApp.Cast.nested(
          map["full_price"],
          &SellApp.GetInvoiceResponseValue200ApplicationJsonPropertyDataPropertyPaymentPropertyFullPrice.from_map/1
        ),
      original_amount:
        SellApp.Cast.nested(
          map["original_amount"],
          &SellApp.GetInvoiceResponseValue200ApplicationJsonPropertyDataPropertyPaymentPropertyOriginalAmount.from_map/1
        ),
      __additional_properties__:
        Map.drop(map, [
          "fee",
          "gateway",
          "subtotal",
          "expires_at",
          "full_price",
          "original_amount"
        ]),
      __present_fields__: Map.keys(map)
    }
  end

  @doc false
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    known =
      SellApp.Cast.keep_present(
        %{
          "fee" =>
            SellApp.Cast.dump_struct(
              struct.fee,
              &SellApp.GetInvoiceResponseValue200ApplicationJsonPropertyDataPropertyPaymentPropertyFee.to_map/1
            ),
          "gateway" =>
            SellApp.Cast.dump_struct(
              struct.gateway,
              &SellApp.GetInvoiceResponseValue200ApplicationJsonPropertyDataPropertyPaymentPropertyGateway.to_map/1
            ),
          "subtotal" =>
            SellApp.Cast.dump_struct(
              struct.subtotal,
              &SellApp.GetInvoiceResponseValue200ApplicationJsonPropertyDataPropertyPaymentPropertySubtotal.to_map/1
            ),
          "expires_at" => struct.expires_at,
          "full_price" =>
            SellApp.Cast.dump_struct(
              struct.full_price,
              &SellApp.GetInvoiceResponseValue200ApplicationJsonPropertyDataPropertyPaymentPropertyFullPrice.to_map/1
            ),
          "original_amount" =>
            SellApp.Cast.dump_struct(
              struct.original_amount,
              &SellApp.GetInvoiceResponseValue200ApplicationJsonPropertyDataPropertyPaymentPropertyOriginalAmount.to_map/1
            )
        },
        ["fee", "gateway", "subtotal", "expires_at", "full_price", "original_amount"],
        struct.__present_fields__
      )

    Map.merge(struct.__additional_properties__, known)
  end
end
