# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.GetAccountResponseValue200ApplicationJsonPropertyData do
  @moduledoc """
  GetAccountResponseValue200ApplicationJsonPropertyData model.
  """

  defstruct [
    :id,
    :username,
    :email,
    :credential_type,
    __additional_properties__: %{},
    __present_fields__: []
  ]

  @type t :: %__MODULE__{
          id: String.t(),
          username: String.t() | nil,
          email: String.t(),
          credential_type:
            SellApp.GetAccountResponseValue200ApplicationJsonPropertyDataCredentialType.t(),
          __additional_properties__: map(),
          __present_fields__: [String.t()]
        }

  @schema %{
    name: "GetAccountResponseValue200ApplicationJsonPropertyData",
    properties: %{
      "id" => %{required: true, schema: %{kind: :string}},
      "username" => %{required: true, schema: %{kind: :nullable, inner: %{kind: :string}}},
      "email" => %{required: true, schema: %{kind: :string}},
      "credential_type" => %{required: true, schema: %{kind: :enum, values: ["sanctum", "oauth"]}}
    },
    additional_properties: true
  }
  @doc false
  def schema, do: @schema

  @doc false
  @spec from_map(map()) :: t()
  def from_map(map) when is_map(map) do
    SellApp.Schema.validate_model!(map, @schema, :response)

    %__MODULE__{
      id: map["id"],
      username: map["username"],
      email: map["email"],
      credential_type:
        SellApp.Cast.enum(
          map["credential_type"],
          &SellApp.GetAccountResponseValue200ApplicationJsonPropertyDataCredentialType.cast/1
        ),
      __additional_properties__: Map.drop(map, ["id", "username", "email", "credential_type"]),
      __present_fields__: Map.keys(map)
    }
  end

  @doc false
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    known =
      SellApp.Cast.keep_present(
        %{
          "id" => struct.id,
          "username" => struct.username,
          "email" => struct.email,
          "credential_type" =>
            SellApp.Cast.enum(
              struct.credential_type,
              &SellApp.GetAccountResponseValue200ApplicationJsonPropertyDataCredentialType.dump/1
            )
        },
        ["id", "username", "email", "credential_type"],
        struct.__present_fields__
      )

    Map.merge(struct.__additional_properties__, known)
  end
end
