# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.GetOrderResponseValue200ApplicationJsonPropertyData do
  @moduledoc """
  GetOrderResponseValue200ApplicationJsonPropertyData model.
  """

  defstruct [
    :id,
    :status,
    :timeline,
    :customer,
    :payment,
    :totals,
    :coupon_id,
    :line_items,
    :created_at,
    :updated_at,
    __additional_properties__: %{},
    __present_fields__: []
  ]

  @type t :: %__MODULE__{
          id: integer(),
          status: SellApp.GetOrderResponseValue200ApplicationJsonPropertyDataStatus.t(),
          timeline: [
            SellApp.GetOrderResponseValue200ApplicationJsonPropertyDataPropertyTimelineItem.t()
          ],
          customer:
            SellApp.GetOrderResponseValue200ApplicationJsonPropertyDataPropertyCustomer.t(),
          payment: SellApp.GetOrderResponseValue200ApplicationJsonPropertyDataPropertyPayment.t(),
          totals: SellApp.GetOrderResponseValue200ApplicationJsonPropertyDataPropertyTotals.t(),
          coupon_id: integer() | nil,
          line_items: [
            SellApp.GetOrderResponseValue200ApplicationJsonPropertyDataPropertyLineItemsItem.t()
          ],
          created_at: String.t() | nil,
          updated_at: String.t() | nil,
          __additional_properties__: map(),
          __present_fields__: [String.t()]
        }

  @schema %{
    name: "GetOrderResponseValue200ApplicationJsonPropertyData",
    properties: %{
      "id" => %{required: true, schema: %{kind: :integer}},
      "status" => %{
        required: true,
        schema: %{
          kind: :enum,
          values: [
            "PENDING",
            "REVERSED",
            "PARTIAL",
            "VOIDED",
            "REFUNDED",
            "PAID",
            "COMPLETED",
            "DISPUTING",
            "REVIEW",
            "FAILED"
          ]
        }
      },
      "timeline" => %{
        required: true,
        schema: %{
          kind: :array,
          items: %{
            kind: :model,
            module:
              SellApp.GetOrderResponseValue200ApplicationJsonPropertyDataPropertyTimelineItem
          }
        }
      },
      "customer" => %{
        required: true,
        schema: %{
          kind: :model,
          module: SellApp.GetOrderResponseValue200ApplicationJsonPropertyDataPropertyCustomer
        }
      },
      "payment" => %{
        required: true,
        schema: %{
          kind: :model,
          module: SellApp.GetOrderResponseValue200ApplicationJsonPropertyDataPropertyPayment
        }
      },
      "totals" => %{
        required: true,
        schema: %{
          kind: :model,
          module: SellApp.GetOrderResponseValue200ApplicationJsonPropertyDataPropertyTotals
        }
      },
      "coupon_id" => %{required: true, schema: %{kind: :nullable, inner: %{kind: :integer}}},
      "line_items" => %{
        required: true,
        schema: %{
          kind: :array,
          items: %{
            kind: :model,
            module:
              SellApp.GetOrderResponseValue200ApplicationJsonPropertyDataPropertyLineItemsItem
          }
        }
      },
      "created_at" => %{
        required: true,
        schema: %{kind: :nullable, inner: %{kind: :string, format: "date-time"}}
      },
      "updated_at" => %{
        required: true,
        schema: %{kind: :nullable, inner: %{kind: :string, format: "date-time"}}
      }
    },
    additional_properties: true
  }
  @doc false
  def schema, do: @schema

  @doc false
  @spec from_map(map()) :: t()
  def from_map(map) when is_map(map) do
    SellApp.Schema.validate_model!(map, @schema, :response)

    %__MODULE__{
      id: map["id"],
      status:
        SellApp.Cast.enum(
          map["status"],
          &SellApp.GetOrderResponseValue200ApplicationJsonPropertyDataStatus.cast/1
        ),
      timeline:
        SellApp.Cast.list(
          map["timeline"],
          &SellApp.GetOrderResponseValue200ApplicationJsonPropertyDataPropertyTimelineItem.from_map/1
        ),
      customer:
        SellApp.Cast.nested(
          map["customer"],
          &SellApp.GetOrderResponseValue200ApplicationJsonPropertyDataPropertyCustomer.from_map/1
        ),
      payment:
        SellApp.Cast.nested(
          map["payment"],
          &SellApp.GetOrderResponseValue200ApplicationJsonPropertyDataPropertyPayment.from_map/1
        ),
      totals:
        SellApp.Cast.nested(
          map["totals"],
          &SellApp.GetOrderResponseValue200ApplicationJsonPropertyDataPropertyTotals.from_map/1
        ),
      coupon_id: map["coupon_id"],
      line_items:
        SellApp.Cast.list(
          map["line_items"],
          &SellApp.GetOrderResponseValue200ApplicationJsonPropertyDataPropertyLineItemsItem.from_map/1
        ),
      created_at: map["created_at"],
      updated_at: map["updated_at"],
      __additional_properties__:
        Map.drop(map, [
          "id",
          "status",
          "timeline",
          "customer",
          "payment",
          "totals",
          "coupon_id",
          "line_items",
          "created_at",
          "updated_at"
        ]),
      __present_fields__: Map.keys(map)
    }
  end

  @doc false
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    known =
      SellApp.Cast.keep_present(
        %{
          "id" => struct.id,
          "status" =>
            SellApp.Cast.enum(
              struct.status,
              &SellApp.GetOrderResponseValue200ApplicationJsonPropertyDataStatus.dump/1
            ),
          "timeline" =>
            SellApp.Cast.list(struct.timeline, fn item ->
              SellApp.Cast.dump_struct(
                item,
                &SellApp.GetOrderResponseValue200ApplicationJsonPropertyDataPropertyTimelineItem.to_map/1
              )
            end),
          "customer" =>
            SellApp.Cast.dump_struct(
              struct.customer,
              &SellApp.GetOrderResponseValue200ApplicationJsonPropertyDataPropertyCustomer.to_map/1
            ),
          "payment" =>
            SellApp.Cast.dump_struct(
              struct.payment,
              &SellApp.GetOrderResponseValue200ApplicationJsonPropertyDataPropertyPayment.to_map/1
            ),
          "totals" =>
            SellApp.Cast.dump_struct(
              struct.totals,
              &SellApp.GetOrderResponseValue200ApplicationJsonPropertyDataPropertyTotals.to_map/1
            ),
          "coupon_id" => struct.coupon_id,
          "line_items" =>
            SellApp.Cast.list(struct.line_items, fn item ->
              SellApp.Cast.dump_struct(
                item,
                &SellApp.GetOrderResponseValue200ApplicationJsonPropertyDataPropertyLineItemsItem.to_map/1
              )
            end),
          "created_at" => struct.created_at,
          "updated_at" => struct.updated_at
        },
        [
          "id",
          "status",
          "timeline",
          "customer",
          "payment",
          "totals",
          "coupon_id",
          "line_items",
          "created_at",
          "updated_at"
        ],
        struct.__present_fields__
      )

    Map.merge(struct.__additional_properties__, known)
  end
end
