# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.IssueEligibleRewardGrantResponseValue201ApplicationJsonPropertyDataTriggerType do
  @moduledoc """
  IssueEligibleRewardGrantResponseValue201ApplicationJsonPropertyDataTriggerType enum.
  """

  @type t :: :purchase_count | :total_spent

  @doc "All known values."
  @spec values() :: [t()]
  def values, do: [:purchase_count, :total_spent]

  @doc "Casts a wire string to its atom; unknown values pass through unchanged."
  @spec cast(String.t() | nil) :: t() | String.t() | nil
  def cast("PURCHASE_COUNT"), do: :purchase_count
  def cast("TOTAL_SPENT"), do: :total_spent
  def cast(other), do: other

  @doc "Dumps an atom back to its wire string."
  @spec dump(t() | String.t()) :: String.t()
  def dump(:purchase_count), do: "PURCHASE_COUNT"
  def dump(:total_spent), do: "TOTAL_SPENT"
  def dump(other) when is_binary(other), do: other
end
