# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.ListOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItem do
  @moduledoc """
  ListOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItem model.
  """

  defstruct [
    :id,
    :order,
    :status,
    :product,
    :variant,
    :quantity,
    :currency,
    :amounts,
    :discounts,
    :tax,
    :promotion,
    :referral,
    :subscription,
    :fulfillment,
    :created_at,
    :updated_at,
    :customer_id,
    :currency_rate,
    :payment_method,
    __additional_properties__: %{},
    __present_fields__: []
  ]

  @type t :: %__MODULE__{
          id: integer(),
          order:
            SellApp.ListOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyOrder.t(),
          status:
            SellApp.ListOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItemStatus.t(),
          product:
            SellApp.ListOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyProduct.t(),
          variant:
            SellApp.ListOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyVariant.t(),
          quantity: integer(),
          currency: String.t() | nil,
          amounts:
            SellApp.ListOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyAmounts.t(),
          discounts:
            SellApp.ListOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyDiscounts.t(),
          tax:
            SellApp.ListOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyTax.t(),
          promotion:
            SellApp.ListOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyPromotion.t()
            | nil,
          referral:
            SellApp.ListOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyReferral.t()
            | nil,
          subscription:
            SellApp.ListOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertySubscription.t()
            | nil,
          fulfillment:
            SellApp.ListOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyFulfillment.t(),
          created_at: String.t() | nil,
          updated_at: String.t() | nil,
          customer_id: integer() | nil,
          currency_rate: String.t() | nil,
          payment_method: SellApp.PaymentMethod.t() | nil,
          __additional_properties__: map(),
          __present_fields__: [String.t()]
        }

  @schema %{
    name: "ListOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItem",
    properties: %{
      "id" => %{required: true, schema: %{kind: :integer}},
      "order" => %{
        required: true,
        schema: %{
          kind: :model,
          module:
            SellApp.ListOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyOrder
        }
      },
      "status" => %{
        required: true,
        schema: %{
          kind: :enum,
          values: [
            "PENDING",
            "REVERSED",
            "PARTIAL",
            "VOIDED",
            "REFUNDED",
            "PAID",
            "COMPLETED",
            "DISPUTING",
            "REVIEW",
            "FAILED"
          ]
        }
      },
      "product" => %{
        required: true,
        schema: %{
          kind: :model,
          module:
            SellApp.ListOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyProduct
        }
      },
      "variant" => %{
        required: true,
        schema: %{
          kind: :model,
          module:
            SellApp.ListOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyVariant
        }
      },
      "quantity" => %{required: true, schema: %{kind: :integer, minimum: 1}},
      "currency" => %{
        required: true,
        schema: %{kind: :nullable, inner: %{kind: :string, min_length: 3, max_length: 3}}
      },
      "amounts" => %{
        required: true,
        schema: %{
          kind: :model,
          module:
            SellApp.ListOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyAmounts
        }
      },
      "discounts" => %{
        required: true,
        schema: %{
          kind: :model,
          module:
            SellApp.ListOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyDiscounts
        }
      },
      "tax" => %{
        required: true,
        schema: %{
          kind: :model,
          module:
            SellApp.ListOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyTax
        }
      },
      "promotion" => %{
        required: true,
        schema: %{
          kind: :nullable,
          inner: %{
            kind: :model,
            module:
              SellApp.ListOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyPromotion
          }
        }
      },
      "referral" => %{
        required: true,
        schema: %{
          kind: :nullable,
          inner: %{
            kind: :model,
            module:
              SellApp.ListOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyReferral
          }
        }
      },
      "subscription" => %{
        required: true,
        schema: %{
          kind: :nullable,
          inner: %{
            kind: :model,
            module:
              SellApp.ListOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertySubscription
          }
        }
      },
      "fulfillment" => %{
        required: true,
        schema: %{
          kind: :model,
          module:
            SellApp.ListOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyFulfillment
        }
      },
      "created_at" => %{
        required: true,
        schema: %{kind: :nullable, inner: %{kind: :string, format: "date-time"}}
      },
      "updated_at" => %{
        required: true,
        schema: %{kind: :nullable, inner: %{kind: :string, format: "date-time"}}
      },
      "customer_id" => %{required: false, schema: %{kind: :nullable, inner: %{kind: :integer}}},
      "currency_rate" => %{required: false, schema: %{kind: :nullable, inner: %{kind: :string}}},
      "payment_method" => %{
        required: false,
        schema: %{
          kind: :nullable,
          inner: %{
            kind: :enum,
            values: [
              "AUTHNET",
              "BTCPAY",
              "CASHAPP",
              "COINBASE",
              "PADDLE",
              "PAYDASH",
              "PAYPAL",
              "PAYSTACK",
              "SQUARE",
              "STRIPE",
              "VENMO",
              "NMI",
              "MERCADO_PAGO",
              "MOLLIE",
              "RAZORPAY",
              "CUSTOM_PAYMENT_METHOD",
              "LIFI",
              "BTC",
              "LTC",
              "ETH",
              "XMR",
              "SOL",
              "ADA",
              "BNB",
              "TRX",
              "MATIC",
              "ETH_USDT",
              "ETH_USDC",
              "ETH_UNI",
              "ETH_SHIB",
              "ETH_DAI",
              "BNB_USDT",
              "BNB_USDC",
              "TRX_USDT",
              "TRX_USDC",
              "SOL_USDT",
              "SOL_USDC"
            ]
          }
        }
      }
    },
    additional_properties: true
  }
  @doc false
  def schema, do: @schema

  @doc false
  @spec from_map(map()) :: t()
  def from_map(map) when is_map(map) do
    SellApp.Schema.validate_model!(map, @schema, :response)

    %__MODULE__{
      id: map["id"],
      order:
        SellApp.Cast.nested(
          map["order"],
          &SellApp.ListOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyOrder.from_map/1
        ),
      status:
        SellApp.Cast.enum(
          map["status"],
          &SellApp.ListOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItemStatus.cast/1
        ),
      product:
        SellApp.Cast.nested(
          map["product"],
          &SellApp.ListOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyProduct.from_map/1
        ),
      variant:
        SellApp.Cast.nested(
          map["variant"],
          &SellApp.ListOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyVariant.from_map/1
        ),
      quantity: map["quantity"],
      currency: map["currency"],
      amounts:
        SellApp.Cast.nested(
          map["amounts"],
          &SellApp.ListOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyAmounts.from_map/1
        ),
      discounts:
        SellApp.Cast.nested(
          map["discounts"],
          &SellApp.ListOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyDiscounts.from_map/1
        ),
      tax:
        SellApp.Cast.nested(
          map["tax"],
          &SellApp.ListOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyTax.from_map/1
        ),
      promotion:
        SellApp.Cast.nested(
          map["promotion"],
          &SellApp.ListOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyPromotion.from_map/1
        ),
      referral:
        SellApp.Cast.nested(
          map["referral"],
          &SellApp.ListOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyReferral.from_map/1
        ),
      subscription:
        SellApp.Cast.nested(
          map["subscription"],
          &SellApp.ListOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertySubscription.from_map/1
        ),
      fulfillment:
        SellApp.Cast.nested(
          map["fulfillment"],
          &SellApp.ListOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyFulfillment.from_map/1
        ),
      created_at: map["created_at"],
      updated_at: map["updated_at"],
      customer_id: map["customer_id"],
      currency_rate: map["currency_rate"],
      payment_method: SellApp.Cast.enum(map["payment_method"], &SellApp.PaymentMethod.cast/1),
      __additional_properties__:
        Map.drop(map, [
          "id",
          "order",
          "status",
          "product",
          "variant",
          "quantity",
          "currency",
          "amounts",
          "discounts",
          "tax",
          "promotion",
          "referral",
          "subscription",
          "fulfillment",
          "created_at",
          "updated_at",
          "customer_id",
          "currency_rate",
          "payment_method"
        ]),
      __present_fields__: Map.keys(map)
    }
  end

  @doc false
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    known =
      SellApp.Cast.keep_present(
        %{
          "id" => struct.id,
          "order" =>
            SellApp.Cast.dump_struct(
              struct.order,
              &SellApp.ListOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyOrder.to_map/1
            ),
          "status" =>
            SellApp.Cast.enum(
              struct.status,
              &SellApp.ListOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItemStatus.dump/1
            ),
          "product" =>
            SellApp.Cast.dump_struct(
              struct.product,
              &SellApp.ListOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyProduct.to_map/1
            ),
          "variant" =>
            SellApp.Cast.dump_struct(
              struct.variant,
              &SellApp.ListOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyVariant.to_map/1
            ),
          "quantity" => struct.quantity,
          "currency" => struct.currency,
          "amounts" =>
            SellApp.Cast.dump_struct(
              struct.amounts,
              &SellApp.ListOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyAmounts.to_map/1
            ),
          "discounts" =>
            SellApp.Cast.dump_struct(
              struct.discounts,
              &SellApp.ListOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyDiscounts.to_map/1
            ),
          "tax" =>
            SellApp.Cast.dump_struct(
              struct.tax,
              &SellApp.ListOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyTax.to_map/1
            ),
          "promotion" =>
            SellApp.Cast.dump_struct(
              struct.promotion,
              &SellApp.ListOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyPromotion.to_map/1
            ),
          "referral" =>
            SellApp.Cast.dump_struct(
              struct.referral,
              &SellApp.ListOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyReferral.to_map/1
            ),
          "subscription" =>
            SellApp.Cast.dump_struct(
              struct.subscription,
              &SellApp.ListOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertySubscription.to_map/1
            ),
          "fulfillment" =>
            SellApp.Cast.dump_struct(
              struct.fulfillment,
              &SellApp.ListOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyFulfillment.to_map/1
            ),
          "created_at" => struct.created_at,
          "updated_at" => struct.updated_at,
          "customer_id" => struct.customer_id,
          "currency_rate" => struct.currency_rate,
          "payment_method" =>
            SellApp.Cast.enum(struct.payment_method, &SellApp.PaymentMethod.dump/1)
        },
        [
          "id",
          "order",
          "status",
          "product",
          "variant",
          "quantity",
          "currency",
          "amounts",
          "discounts",
          "tax",
          "promotion",
          "referral",
          "subscription",
          "fulfillment",
          "created_at",
          "updated_at"
        ],
        struct.__present_fields__
      )

    Map.merge(struct.__additional_properties__, known)
  end
end
