# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.ListCustomerEntitlementsResponseValue200ApplicationJsonPropertyDataItemPropertySubject do
  @moduledoc """
  ListCustomerEntitlementsResponseValue200ApplicationJsonPropertyDataItemPropertySubject model.
  """

  defstruct [
    :type,
    :id,
    :name,
    __additional_properties__: %{},
    __present_fields__: []
  ]

  @type t :: %__MODULE__{
          type: String.t(),
          id: integer() | String.t(),
          name: String.t(),
          __additional_properties__: map(),
          __present_fields__: [String.t()]
        }

  @schema %{
    name:
      "ListCustomerEntitlementsResponseValue200ApplicationJsonPropertyDataItemPropertySubject",
    properties: %{
      "type" => %{required: true, schema: %{kind: :string}},
      "id" => %{
        required: true,
        schema: %{kind: :union, variants: [%{kind: :integer}, %{kind: :string}]}
      },
      "name" => %{required: true, schema: %{kind: :string}}
    },
    additional_properties: true
  }
  @doc false
  def schema, do: @schema

  @doc false
  @spec from_map(map()) :: t()
  def from_map(map) when is_map(map) do
    SellApp.Schema.validate_model!(map, @schema, :response)

    %__MODULE__{
      type: map["type"],
      id: map["id"],
      name: map["name"],
      __additional_properties__: Map.drop(map, ["type", "id", "name"]),
      __present_fields__: Map.keys(map)
    }
  end

  @doc false
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    known =
      SellApp.Cast.keep_present(
        %{
          "type" => struct.type,
          "id" => SellApp.Cast.dump_union(struct.id),
          "name" => struct.name
        },
        ["type", "id", "name"],
        struct.__present_fields__
      )

    Map.merge(struct.__additional_properties__, known)
  end
end
