# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.ListAffiliateReferralsResponseValue200ApplicationJsonPropertyDataItemPropertyCommissionType do
  @moduledoc """
  ListAffiliateReferralsResponseValue200ApplicationJsonPropertyDataItemPropertyCommissionType enum.
  """

  @type t :: :percentage | :fixed

  @doc "All known values."
  @spec values() :: [t()]
  def values, do: [:percentage, :fixed]

  @doc "Casts a wire string to its atom; unknown values pass through unchanged."
  @spec cast(String.t() | nil) :: t() | String.t() | nil
  def cast("percentage"), do: :percentage
  def cast("fixed"), do: :fixed
  def cast(other), do: other

  @doc "Dumps an atom back to its wire string."
  @spec dump(t() | String.t()) :: String.t()
  def dump(:percentage), do: "percentage"
  def dump(:fixed), do: "fixed"
  def dump(other) when is_binary(other), do: other
end
