# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.ListAffiliatesResponseValue200ApplicationJsonPropertyDataItemPropertyBalances do
  @moduledoc """
  ListAffiliatesResponseValue200ApplicationJsonPropertyDataItemPropertyBalances model.
  """

  defstruct [
    :available_usd_cents,
    :pending_usd_cents,
    :paid_usd_cents,
    __additional_properties__: %{},
    __present_fields__: []
  ]

  @type t :: %__MODULE__{
          available_usd_cents: integer(),
          pending_usd_cents: integer(),
          paid_usd_cents: integer(),
          __additional_properties__: map(),
          __present_fields__: [String.t()]
        }

  @schema %{
    name: "ListAffiliatesResponseValue200ApplicationJsonPropertyDataItemPropertyBalances",
    properties: %{
      "available_usd_cents" => %{required: true, schema: %{kind: :integer, minimum: 0}},
      "pending_usd_cents" => %{required: true, schema: %{kind: :integer, minimum: 0}},
      "paid_usd_cents" => %{required: true, schema: %{kind: :integer, minimum: 0}}
    },
    additional_properties: true
  }
  @doc false
  def schema, do: @schema

  @doc false
  @spec from_map(map()) :: t()
  def from_map(map) when is_map(map) do
    SellApp.Schema.validate_model!(map, @schema, :response)

    %__MODULE__{
      available_usd_cents: map["available_usd_cents"],
      pending_usd_cents: map["pending_usd_cents"],
      paid_usd_cents: map["paid_usd_cents"],
      __additional_properties__:
        Map.drop(map, ["available_usd_cents", "pending_usd_cents", "paid_usd_cents"]),
      __present_fields__: Map.keys(map)
    }
  end

  @doc false
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    known =
      SellApp.Cast.keep_present(
        %{
          "available_usd_cents" => struct.available_usd_cents,
          "pending_usd_cents" => struct.pending_usd_cents,
          "paid_usd_cents" => struct.paid_usd_cents
        },
        ["available_usd_cents", "pending_usd_cents", "paid_usd_cents"],
        struct.__present_fields__
      )

    Map.merge(struct.__additional_properties__, known)
  end
end
