# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.ListGroupsResponseValue200ApplicationJsonPropertyDataItemPropertyImageValuePropertyMetadata do
  @moduledoc """
  ListGroupsResponseValue200ApplicationJsonPropertyDataItemPropertyImageValuePropertyMetadata model.
  """

  defstruct [
    :size,
    :filename,
    :extension,
    :mime_type,
    __additional_properties__: %{},
    __present_fields__: []
  ]

  @type t :: %__MODULE__{
          size: integer() | nil,
          filename: String.t() | nil,
          extension: String.t() | nil,
          mime_type: String.t() | nil,
          __additional_properties__: map(),
          __present_fields__: [String.t()]
        }

  @schema %{
    name:
      "ListGroupsResponseValue200ApplicationJsonPropertyDataItemPropertyImageValuePropertyMetadata",
    properties: %{
      "size" => %{required: false, schema: %{kind: :integer}},
      "filename" => %{required: false, schema: %{kind: :string}},
      "extension" => %{required: false, schema: %{kind: :string}},
      "mime_type" => %{required: false, schema: %{kind: :string}}
    },
    additional_properties: true
  }
  @doc false
  def schema, do: @schema

  @doc false
  @spec from_map(map()) :: t()
  def from_map(map) when is_map(map) do
    SellApp.Schema.validate_model!(map, @schema, :response)

    %__MODULE__{
      size: map["size"],
      filename: map["filename"],
      extension: map["extension"],
      mime_type: map["mime_type"],
      __additional_properties__: Map.drop(map, ["size", "filename", "extension", "mime_type"]),
      __present_fields__: Map.keys(map)
    }
  end

  @doc false
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    known =
      SellApp.Cast.keep_present(
        %{
          "size" => struct.size,
          "filename" => struct.filename,
          "extension" => struct.extension,
          "mime_type" => struct.mime_type
        },
        [],
        struct.__present_fields__
      )

    Map.merge(struct.__additional_properties__, known)
  end
end
