# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.ListInvoicesResponseValue200ApplicationJsonPropertyDataItem do
  @moduledoc """
  ListInvoicesResponseValue200ApplicationJsonPropertyDataItem model.
  """

  defstruct [
    :id,
    :payment,
    :status,
    :webhooks,
    :feedback,
    :created_at,
    :updated_at,
    :store_id,
    :coupon_id,
    :subscription_id,
    :customer_information,
    :product_variants,
    __additional_properties__: %{},
    __present_fields__: []
  ]

  @type t :: %__MODULE__{
          id: integer(),
          payment:
            SellApp.ListInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyPayment.t(),
          status:
            SellApp.ListInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyStatus.t(),
          webhooks: [
            SellApp.ListInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyWebhooksItem.t()
          ],
          feedback: String.t() | nil,
          created_at: String.t(),
          updated_at: String.t(),
          store_id: integer(),
          coupon_id: integer() | nil,
          subscription_id: integer() | nil,
          customer_information:
            SellApp.ListInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyCustomerInformation.t(),
          product_variants: [
            SellApp.ListInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyProductVariantsItem.t()
          ],
          __additional_properties__: map(),
          __present_fields__: [String.t()]
        }

  @schema %{
    name: "ListInvoicesResponseValue200ApplicationJsonPropertyDataItem",
    properties: %{
      "id" => %{required: true, schema: %{kind: :integer}},
      "payment" => %{
        required: true,
        schema: %{
          kind: :model,
          module:
            SellApp.ListInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyPayment
        }
      },
      "status" => %{
        required: true,
        schema: %{
          kind: :model,
          module:
            SellApp.ListInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyStatus
        }
      },
      "webhooks" => %{
        required: true,
        schema: %{
          kind: :array,
          items: %{
            kind: :model,
            module:
              SellApp.ListInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyWebhooksItem
          }
        }
      },
      "feedback" => %{required: true, schema: %{kind: :nullable, inner: %{kind: :string}}},
      "created_at" => %{required: true, schema: %{kind: :string, format: "date-time"}},
      "updated_at" => %{required: true, schema: %{kind: :string, format: "date-time"}},
      "store_id" => %{required: true, schema: %{kind: :integer}},
      "coupon_id" => %{required: true, schema: %{kind: :nullable, inner: %{kind: :integer}}},
      "subscription_id" => %{required: true, schema: %{kind: :nullable, inner: %{kind: :integer}}},
      "customer_information" => %{
        required: true,
        schema: %{
          kind: :model,
          module:
            SellApp.ListInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyCustomerInformation
        }
      },
      "product_variants" => %{
        required: true,
        schema: %{
          kind: :array,
          items: %{
            kind: :model,
            module:
              SellApp.ListInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyProductVariantsItem
          }
        }
      }
    },
    additional_properties: true
  }
  @doc false
  def schema, do: @schema

  @doc false
  @spec from_map(map()) :: t()
  def from_map(map) when is_map(map) do
    SellApp.Schema.validate_model!(map, @schema, :response)

    %__MODULE__{
      id: map["id"],
      payment:
        SellApp.Cast.nested(
          map["payment"],
          &SellApp.ListInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyPayment.from_map/1
        ),
      status:
        SellApp.Cast.nested(
          map["status"],
          &SellApp.ListInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyStatus.from_map/1
        ),
      webhooks:
        SellApp.Cast.list(
          map["webhooks"],
          &SellApp.ListInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyWebhooksItem.from_map/1
        ),
      feedback: map["feedback"],
      created_at: map["created_at"],
      updated_at: map["updated_at"],
      store_id: map["store_id"],
      coupon_id: map["coupon_id"],
      subscription_id: map["subscription_id"],
      customer_information:
        SellApp.Cast.nested(
          map["customer_information"],
          &SellApp.ListInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyCustomerInformation.from_map/1
        ),
      product_variants:
        SellApp.Cast.list(
          map["product_variants"],
          &SellApp.ListInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyProductVariantsItem.from_map/1
        ),
      __additional_properties__:
        Map.drop(map, [
          "id",
          "payment",
          "status",
          "webhooks",
          "feedback",
          "created_at",
          "updated_at",
          "store_id",
          "coupon_id",
          "subscription_id",
          "customer_information",
          "product_variants"
        ]),
      __present_fields__: Map.keys(map)
    }
  end

  @doc false
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    known =
      SellApp.Cast.keep_present(
        %{
          "id" => struct.id,
          "payment" =>
            SellApp.Cast.dump_struct(
              struct.payment,
              &SellApp.ListInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyPayment.to_map/1
            ),
          "status" =>
            SellApp.Cast.dump_struct(
              struct.status,
              &SellApp.ListInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyStatus.to_map/1
            ),
          "webhooks" =>
            SellApp.Cast.list(struct.webhooks, fn item ->
              SellApp.Cast.dump_struct(
                item,
                &SellApp.ListInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyWebhooksItem.to_map/1
              )
            end),
          "feedback" => struct.feedback,
          "created_at" => struct.created_at,
          "updated_at" => struct.updated_at,
          "store_id" => struct.store_id,
          "coupon_id" => struct.coupon_id,
          "subscription_id" => struct.subscription_id,
          "customer_information" =>
            SellApp.Cast.dump_struct(
              struct.customer_information,
              &SellApp.ListInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyCustomerInformation.to_map/1
            ),
          "product_variants" =>
            SellApp.Cast.list(struct.product_variants, fn item ->
              SellApp.Cast.dump_struct(
                item,
                &SellApp.ListInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyProductVariantsItem.to_map/1
              )
            end)
        },
        [
          "id",
          "payment",
          "status",
          "webhooks",
          "feedback",
          "created_at",
          "updated_at",
          "store_id",
          "coupon_id",
          "subscription_id",
          "customer_information",
          "product_variants"
        ],
        struct.__present_fields__
      )

    Map.merge(struct.__additional_properties__, known)
  end
end
