# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.Provider do
  @moduledoc """
  Provider enum.
  """

  @type t ::
          :manual
          | :mercado_pago
          | :nmi
          | :mollie
          | :paypal
          | :razorpay
          | :square
          | :stripe
          | :null

  @doc "All known values."
  @spec values() :: [t()]
  def values,
    do: [:manual, :mercado_pago, :nmi, :mollie, :paypal, :razorpay, :square, :stripe, :null]

  @doc "Casts a wire string to its atom; unknown values pass through unchanged."
  @spec cast(String.t() | nil) :: t() | String.t() | nil
  def cast("manual"), do: :manual
  def cast("mercado_pago"), do: :mercado_pago
  def cast("nmi"), do: :nmi
  def cast("mollie"), do: :mollie
  def cast("paypal"), do: :paypal
  def cast("razorpay"), do: :razorpay
  def cast("square"), do: :square
  def cast("stripe"), do: :stripe
  def cast("null"), do: :null
  def cast(other), do: other

  @doc "Dumps an atom back to its wire string."
  @spec dump(t() | String.t()) :: String.t()
  def dump(:manual), do: "manual"
  def dump(:mercado_pago), do: "mercado_pago"
  def dump(:nmi), do: "nmi"
  def dump(:mollie), do: "mollie"
  def dump(:paypal), do: "paypal"
  def dump(:razorpay), do: "razorpay"
  def dump(:square), do: "square"
  def dump(:stripe), do: "stripe"
  def dump(:null), do: "null"
  def dump(other) when is_binary(other), do: other
end
