# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.ReplaceCourseLessonRequestApplicationJsonPropertyQuestionsItemPropertyAnswersItem do
  @moduledoc """
  ReplaceCourseLessonRequestApplicationJsonPropertyQuestionsItemPropertyAnswersItem model.
  """

  defstruct [
    :answer,
    :is_correct,
    __additional_properties__: %{},
    __present_fields__: []
  ]

  @type t :: %__MODULE__{
          answer: String.t(),
          is_correct: boolean(),
          __additional_properties__: map(),
          __present_fields__: [String.t()]
        }

  @schema %{
    name: "ReplaceCourseLessonRequestApplicationJsonPropertyQuestionsItemPropertyAnswersItem",
    properties: %{
      "answer" => %{required: true, schema: %{kind: :string, max_length: 65535}},
      "is_correct" => %{required: true, schema: %{kind: :boolean}}
    },
    additional_properties: true
  }
  @doc false
  def schema, do: @schema

  @doc false
  @spec from_map(map()) :: t()
  def from_map(map) when is_map(map) do
    SellApp.Schema.validate_model!(map, @schema, :response)

    %__MODULE__{
      answer: map["answer"],
      is_correct: map["is_correct"],
      __additional_properties__: Map.drop(map, ["answer", "is_correct"]),
      __present_fields__: Map.keys(map)
    }
  end

  @doc false
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    known =
      SellApp.Cast.keep_present(
        %{
          "answer" => struct.answer,
          "is_correct" => struct.is_correct
        },
        ["answer", "is_correct"],
        struct.__present_fields__
      )

    Map.merge(struct.__additional_properties__, known)
  end
end
