# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.ReplaceProductVariantPricingRequestApplicationJsonPropertyPricingPropertyPrice do
  @moduledoc """
  Base price in integer minor units.
  """

  defstruct [
    :price,
    :currency,
    __additional_properties__: %{},
    __present_fields__: []
  ]

  @type t :: %__MODULE__{
          price: integer(),
          currency:
            SellApp.ReplaceProductVariantPricingRequestApplicationJsonPropertyPricingPropertyPriceCurrency.t(),
          __additional_properties__: map(),
          __present_fields__: [String.t()]
        }

  @schema %{
    name: "ReplaceProductVariantPricingRequestApplicationJsonPropertyPricingPropertyPrice",
    properties: %{
      "price" => %{required: true, schema: %{kind: :integer, minimum: 0}},
      "currency" => %{
        required: true,
        schema: %{
          kind: :enum,
          values: [
            "AUD",
            "BRL",
            "CAD",
            "CNY",
            "CZK",
            "DKK",
            "EUR",
            "GHS",
            "HKD",
            "HUF",
            "ILS",
            "INR",
            "JPY",
            "MYR",
            "MXN",
            "NGN",
            "TWD",
            "NZD",
            "NOK",
            "PHP",
            "PLN",
            "GBP",
            "RUB",
            "SGD",
            "SEK",
            "CHF",
            "THB",
            "USD",
            "ZAR"
          ]
        }
      }
    },
    additional_properties: true
  }
  @doc false
  def schema, do: @schema

  @doc false
  @spec from_map(map()) :: t()
  def from_map(map) when is_map(map) do
    SellApp.Schema.validate_model!(map, @schema, :response)

    %__MODULE__{
      price: map["price"],
      currency:
        SellApp.Cast.enum(
          map["currency"],
          &SellApp.ReplaceProductVariantPricingRequestApplicationJsonPropertyPricingPropertyPriceCurrency.cast/1
        ),
      __additional_properties__: Map.drop(map, ["price", "currency"]),
      __present_fields__: Map.keys(map)
    }
  end

  @doc false
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    known =
      SellApp.Cast.keep_present(
        %{
          "price" => struct.price,
          "currency" =>
            SellApp.Cast.enum(
              struct.currency,
              &SellApp.ReplaceProductVariantPricingRequestApplicationJsonPropertyPricingPropertyPriceCurrency.dump/1
            )
        },
        ["price", "currency"],
        struct.__present_fields__
      )

    Map.merge(struct.__additional_properties__, known)
  end
end
