# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.ReplaceAffiliateProgramConfigurationResponseValue200ApplicationJsonPropertyDataPropertySettingsPropertyCommission do
  @moduledoc """
  ReplaceAffiliateProgramConfigurationResponseValue200ApplicationJsonPropertyDataPropertySettingsPropertyCommission model.
  """

  defstruct [
    :type,
    :amount,
    __additional_properties__: %{},
    __present_fields__: []
  ]

  @type t :: %__MODULE__{
          type:
            SellApp.ReplaceAffiliateProgramConfigurationResponseValue200ApplicationJsonPropertyDataPropertySettingsPropertyCommissionType.t(),
          amount: String.t() | nil,
          __additional_properties__: map(),
          __present_fields__: [String.t()]
        }

  @schema %{
    name:
      "ReplaceAffiliateProgramConfigurationResponseValue200ApplicationJsonPropertyDataPropertySettingsPropertyCommission",
    properties: %{
      "type" => %{required: true, schema: %{kind: :enum, values: ["percentage", "fixed"]}},
      "amount" => %{required: true, schema: %{kind: :nullable, inner: %{kind: :string}}}
    },
    additional_properties: true
  }
  @doc false
  def schema, do: @schema

  @doc false
  @spec from_map(map()) :: t()
  def from_map(map) when is_map(map) do
    SellApp.Schema.validate_model!(map, @schema, :response)

    %__MODULE__{
      type:
        SellApp.Cast.enum(
          map["type"],
          &SellApp.ReplaceAffiliateProgramConfigurationResponseValue200ApplicationJsonPropertyDataPropertySettingsPropertyCommissionType.cast/1
        ),
      amount: map["amount"],
      __additional_properties__: Map.drop(map, ["type", "amount"]),
      __present_fields__: Map.keys(map)
    }
  end

  @doc false
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    known =
      SellApp.Cast.keep_present(
        %{
          "type" =>
            SellApp.Cast.enum(
              struct.type,
              &SellApp.ReplaceAffiliateProgramConfigurationResponseValue200ApplicationJsonPropertyDataPropertySettingsPropertyCommissionType.dump/1
            ),
          "amount" => struct.amount
        },
        ["type", "amount"],
        struct.__present_fields__
      )

    Map.merge(struct.__additional_properties__, known)
  end
end
