# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.RewardCouponTemplates do
  @moduledoc """
  Operations for the RewardCouponTemplates API.
  """

  @doc """
  List reward coupon templates

  List reward coupon templates owned by the authenticated store. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.

  ## Parameters

    * `params` — query parameters: `:limit`, `:page`, `:pagination`
    * `opts` — per-request options (see `SellApp.Client.request/5`)
  """
  @spec list(SellApp.Client.t(), map(), keyword()) ::
          {:ok,
           SellApp.Page.t(SellApp.SdkListRewardCouponTemplatesResponseValue200ApplicationJson.t())}
          | {:error, SellApp.Error.error()}
  def list(client, params \\ %{}, opts \\ []) do
    with {:ok, body} <-
           SellApp.Client.request(
             client,
             :get,
             "/v2/reward-coupon-templates",
             params,
             Keyword.put(opts, :operation_id, "listRewardCouponTemplates")
           ) do
      raw_response = if match?(%SellApp.Response{}, body), do: body, else: nil
      body = if raw_response, do: raw_response.data, else: body

      fetch_next = fn cursor ->
        list(
          client,
          SellApp.Page.next_params(params, "page", cursor),
          Keyword.delete(opts, :with_response)
        )
      end

      result =
        SellApp.Page.from_map(
          body,
          "data",
          &SellApp.SdkListRewardCouponTemplatesResponseValue200ApplicationJson.from_map/1,
          fetch_next,
          base_url: client.base_url,
          path: "/v2/reward-coupon-templates",
          pagination_param: "page"
        )

      {:ok, if(raw_response, do: %{raw_response | data: result}, else: result)}
    end
  end

  @doc """
  Create a reward coupon template

  Create reward coupon template configuration. Grant issuance remains a separate operation. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.

  ## Parameters

    * `params` — request body map
    * `opts` — per-request options (see `SellApp.Client.request/5`)
  """
  @spec create(SellApp.Client.t(), map(), keyword()) ::
          {:ok, SellApp.SdkCreateRewardCouponTemplateResponseValue201ApplicationJson.t()}
          | {:error, SellApp.Error.error()}
  def create(client, params \\ %{}, opts \\ []) do
    SellApp.Schema.validate_value!(
      params,
      %{kind: :model, module: SellApp.SdkCreateRewardCouponTemplateRequestApplicationJson},
      :request,
      "$request.body"
    )

    with {:ok, body} <-
           SellApp.Client.request(
             client,
             :post,
             "/v2/reward-coupon-templates",
             params,
             Keyword.put(
               Keyword.put(opts, :request_body, true),
               :operation_id,
               "createRewardCouponTemplate"
             )
           ) do
      raw_response = if match?(%SellApp.Response{}, body), do: body, else: nil
      body = if raw_response, do: raw_response.data, else: body

      SellApp.Schema.validate_value!(
        body,
        %{
          kind: :model,
          module: SellApp.SdkCreateRewardCouponTemplateResponseValue201ApplicationJson
        },
        :response,
        "$response"
      )

      result =
        SellApp.Cast.nested(
          body,
          &SellApp.SdkCreateRewardCouponTemplateResponseValue201ApplicationJson.from_map/1
        )

      {:ok, if(raw_response, do: %{raw_response | data: result}, else: result)}
    end
  end

  @doc """
  Search reward coupon templates

  Search and filter reward coupon templates owned by the authenticated store. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.

  ## Parameters

    * `params` — request body map
    * `opts` — per-request options (see `SellApp.Client.request/5`)
  """
  @spec search(SellApp.Client.t(), map(), keyword()) ::
          {:ok,
           SellApp.Page.t(
             SellApp.SdkSearchRewardCouponTemplatesResponseValue200ApplicationJson.t()
           )}
          | {:error, SellApp.Error.error()}
  def search(client, params \\ %{}, opts \\ []) do
    SellApp.Schema.validate_value!(
      params,
      %{kind: :model, module: SellApp.SdkSearchRewardRulesRequestApplicationJson},
      :request,
      "$request.body"
    )

    with {:ok, body} <-
           SellApp.Client.request(
             client,
             :post,
             "/v2/reward-coupon-templates/search",
             params,
             Keyword.put(
               Keyword.put(opts, :request_body, true),
               :operation_id,
               "searchRewardCouponTemplates"
             )
           ) do
      raw_response = if match?(%SellApp.Response{}, body), do: body, else: nil
      body = if raw_response, do: raw_response.data, else: body

      fetch_next = fn cursor ->
        search(
          client,
          SellApp.Page.next_params(params, "page", cursor),
          Keyword.delete(opts, :with_response)
        )
      end

      result =
        SellApp.Page.from_map(
          body,
          "data",
          &SellApp.SdkSearchRewardCouponTemplatesResponseValue200ApplicationJson.from_map/1,
          fetch_next,
          base_url: client.base_url,
          path: "/v2/reward-coupon-templates/search",
          pagination_param: "page"
        )

      {:ok, if(raw_response, do: %{raw_response | data: result}, else: result)}
    end
  end

  @doc """
  Retrieve a reward coupon template

  Retrieve one store-owned reward coupon template. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.

  ## Parameters

    * `reward_coupon_template` — The rewardCouponTemplate path parameter.
    * `opts` — per-request options (see `SellApp.Client.request/5`)
  """
  @spec get(SellApp.Client.t(), String.t(), keyword()) ::
          {:ok, SellApp.SdkGetRewardCouponTemplateResponseValue200ApplicationJson.t()}
          | {:error, SellApp.Error.error()}
  def get(client, reward_coupon_template, opts \\ []) do
    with {:ok, body} <-
           SellApp.Client.request(
             client,
             :get,
             "/v2/reward-coupon-templates/#{URI.encode(reward_coupon_template, &URI.char_unreserved?/1)}",
             %{},
             Keyword.put(opts, :operation_id, "getRewardCouponTemplate")
           ) do
      raw_response = if match?(%SellApp.Response{}, body), do: body, else: nil
      body = if raw_response, do: raw_response.data, else: body

      SellApp.Schema.validate_value!(
        body,
        %{
          kind: :model,
          module: SellApp.SdkGetRewardCouponTemplateResponseValue200ApplicationJson
        },
        :response,
        "$response"
      )

      result =
        SellApp.Cast.nested(
          body,
          &SellApp.SdkGetRewardCouponTemplateResponseValue200ApplicationJson.from_map/1
        )

      {:ok, if(raw_response, do: %{raw_response | data: result}, else: result)}
    end
  end

  @doc """
  Update a reward coupon template

  Update reward coupon template configuration without directly issuing a customer grant. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.

  ## Parameters

    * `reward_coupon_template` — The rewardCouponTemplate path parameter.
    * `params` — request body map
    * `opts` — per-request options (see `SellApp.Client.request/5`)
  """
  @spec replace(SellApp.Client.t(), String.t(), map(), keyword()) ::
          {:ok, SellApp.SdkReplaceRewardCouponTemplateResponseValue200ApplicationJson.t()}
          | {:error, SellApp.Error.error()}
  def replace(client, reward_coupon_template, params \\ %{}, opts \\ []) do
    SellApp.Schema.validate_value!(
      params,
      %{kind: :model, module: SellApp.SdkReplaceRewardCouponTemplateRequestApplicationJson},
      :request,
      "$request.body"
    )

    with {:ok, body} <-
           SellApp.Client.request(
             client,
             :put,
             "/v2/reward-coupon-templates/#{URI.encode(reward_coupon_template, &URI.char_unreserved?/1)}",
             params,
             Keyword.put(
               Keyword.put(opts, :request_body, true),
               :operation_id,
               "replaceRewardCouponTemplate"
             )
           ) do
      raw_response = if match?(%SellApp.Response{}, body), do: body, else: nil
      body = if raw_response, do: raw_response.data, else: body

      SellApp.Schema.validate_value!(
        body,
        %{
          kind: :model,
          module: SellApp.SdkReplaceRewardCouponTemplateResponseValue200ApplicationJson
        },
        :response,
        "$response"
      )

      result =
        SellApp.Cast.nested(
          body,
          &SellApp.SdkReplaceRewardCouponTemplateResponseValue200ApplicationJson.from_map/1
        )

      {:ok, if(raw_response, do: %{raw_response | data: result}, else: result)}
    end
  end

  @doc """
  Update a reward coupon template

  Update reward coupon template configuration without directly issuing a customer grant. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.

  ## Parameters

    * `reward_coupon_template` — The rewardCouponTemplate path parameter.
    * `params` — request body map
    * `opts` — per-request options (see `SellApp.Client.request/5`)
  """
  @spec update(SellApp.Client.t(), String.t(), map(), keyword()) ::
          {:ok, SellApp.SdkUpdateRewardCouponTemplateResponseValue200ApplicationJson.t()}
          | {:error, SellApp.Error.error()}
  def update(client, reward_coupon_template, params \\ %{}, opts \\ []) do
    SellApp.Schema.validate_value!(
      params,
      %{kind: :model, module: SellApp.SdkUpdateRewardCouponTemplateRequestApplicationJson},
      :request,
      "$request.body"
    )

    with {:ok, body} <-
           SellApp.Client.request(
             client,
             :patch,
             "/v2/reward-coupon-templates/#{URI.encode(reward_coupon_template, &URI.char_unreserved?/1)}",
             params,
             Keyword.put(
               Keyword.put(opts, :request_body, true),
               :operation_id,
               "updateRewardCouponTemplate"
             )
           ) do
      raw_response = if match?(%SellApp.Response{}, body), do: body, else: nil
      body = if raw_response, do: raw_response.data, else: body

      SellApp.Schema.validate_value!(
        body,
        %{
          kind: :model,
          module: SellApp.SdkUpdateRewardCouponTemplateResponseValue200ApplicationJson
        },
        :response,
        "$response"
      )

      result =
        SellApp.Cast.nested(
          body,
          &SellApp.SdkUpdateRewardCouponTemplateResponseValue200ApplicationJson.from_map/1
        )

      {:ok, if(raw_response, do: %{raw_response | data: result}, else: result)}
    end
  end
end
