# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.SdkCreateChargeRequestApplicationJson do
  @moduledoc """
  SdkCreateChargeRequestApplicationJson model.
  """

  defstruct [
    :email,
    :return_url,
    :cancel_url,
    :webhook,
    :reference,
    :description,
    :currency,
    :total,
    :payment_method,
    :payment_methods,
    :custom_payment_method_id,
    :custom_payment_method_ids,
    :use_all_payment_methods,
    :deliverable,
    :metadata,
    :coupon_code,
    __additional_properties__: %{},
    __present_fields__: []
  ]

  @type t :: %__MODULE__{
          email: String.t(),
          return_url: String.t(),
          cancel_url: String.t() | nil,
          webhook: String.t() | nil,
          reference: String.t() | nil,
          description: String.t() | nil,
          currency: String.t() | nil,
          total: integer() | nil,
          payment_method: SellApp.SdkCreateChargeRequestApplicationJsonPaymentMethod.t() | nil,
          payment_methods:
            [SellApp.SdkCreateChargeRequestApplicationJsonPaymentMethods.t()] | nil,
          custom_payment_method_id: String.t() | nil,
          custom_payment_method_ids: [String.t()] | nil,
          use_all_payment_methods: boolean() | nil,
          deliverable: SellApp.CreateChargeRequestApplicationJsonPropertyDeliverable.t() | nil,
          metadata: SellApp.CreateChargeRequestApplicationJsonPropertyMetadata.t() | nil,
          coupon_code: String.t() | nil,
          __additional_properties__: map(),
          __present_fields__: [String.t()]
        }

  @schema %{
    name: "SdkCreateChargeRequestApplicationJson",
    properties: %{
      "email" => %{required: true, schema: %{kind: :string, format: "email"}},
      "return_url" => %{required: true, schema: %{kind: :string, format: "uri"}},
      "cancel_url" => %{
        required: false,
        schema: %{kind: :nullable, inner: %{kind: :string, format: "uri"}}
      },
      "webhook" => %{
        required: false,
        schema: %{kind: :nullable, inner: %{kind: :string, format: "uri"}}
      },
      "reference" => %{
        required: false,
        schema: %{kind: :nullable, inner: %{kind: :string, max_length: 255}}
      },
      "description" => %{
        required: false,
        schema: %{kind: :nullable, inner: %{kind: :string, max_length: 255}}
      },
      "currency" => %{required: false, schema: %{kind: :string, min_length: 3, max_length: 3}},
      "total" => %{required: false, schema: %{kind: :integer, minimum: 0}},
      "payment_method" => %{
        required: false,
        schema: %{
          kind: :enum,
          values: [
            "AUTHNET",
            "BTCPAY",
            "CASHAPP",
            "COINBASE",
            "PADDLE",
            "PAYDASH",
            "PAYPAL",
            "PAYSTACK",
            "SQUARE",
            "STRIPE",
            "VENMO",
            "NMI",
            "MERCADO_PAGO",
            "MOLLIE",
            "RAZORPAY",
            "CUSTOM_PAYMENT_METHOD",
            "LIFI",
            "BTC",
            "LTC",
            "ETH",
            "XMR",
            "SOL",
            "ADA",
            "BNB",
            "TRX",
            "MATIC",
            "ETH_USDT",
            "ETH_USDC",
            "ETH_UNI",
            "ETH_SHIB",
            "ETH_DAI",
            "BNB_USDT",
            "BNB_USDC",
            "TRX_USDT",
            "TRX_USDC",
            "SOL_USDT",
            "SOL_USDC"
          ]
        }
      },
      "payment_methods" => %{
        required: false,
        schema: %{
          kind: :array,
          items: %{
            kind: :enum,
            values: [
              "AUTHNET",
              "BTCPAY",
              "CASHAPP",
              "COINBASE",
              "PADDLE",
              "PAYDASH",
              "PAYPAL",
              "PAYSTACK",
              "SQUARE",
              "STRIPE",
              "VENMO",
              "NMI",
              "MERCADO_PAGO",
              "MOLLIE",
              "RAZORPAY",
              "CUSTOM_PAYMENT_METHOD",
              "LIFI",
              "BTC",
              "LTC",
              "ETH",
              "XMR",
              "SOL",
              "ADA",
              "BNB",
              "TRX",
              "MATIC",
              "ETH_USDT",
              "ETH_USDC",
              "ETH_UNI",
              "ETH_SHIB",
              "ETH_DAI",
              "BNB_USDT",
              "BNB_USDC",
              "TRX_USDT",
              "TRX_USDC",
              "SOL_USDT",
              "SOL_USDC"
            ]
          },
          min_items: 1
        }
      },
      "custom_payment_method_id" => %{
        required: false,
        schema: %{kind: :nullable, inner: %{kind: :string, min_length: 26, max_length: 26}}
      },
      "custom_payment_method_ids" => %{
        required: false,
        schema: %{
          kind: :array,
          items: %{kind: :string, min_length: 26, max_length: 26},
          min_items: 1,
          unique_items: true
        }
      },
      "use_all_payment_methods" => %{required: false, schema: %{kind: :boolean}},
      "deliverable" => %{
        required: false,
        schema: %{
          kind: :model,
          module: SellApp.CreateChargeRequestApplicationJsonPropertyDeliverable
        }
      },
      "metadata" => %{
        required: false,
        schema: %{
          kind: :model,
          module: SellApp.CreateChargeRequestApplicationJsonPropertyMetadata
        }
      },
      "coupon_code" => %{required: false, schema: %{kind: :nullable, inner: %{kind: :string}}}
    },
    additional_properties: true
  }
  @doc false
  def schema, do: @schema

  @doc false
  @spec from_map(map()) :: t()
  def from_map(map) when is_map(map) do
    SellApp.Schema.validate_model!(map, @schema, :response)

    %__MODULE__{
      email: map["email"],
      return_url: map["return_url"],
      cancel_url: map["cancel_url"],
      webhook: map["webhook"],
      reference: map["reference"],
      description: map["description"],
      currency: map["currency"],
      total: map["total"],
      payment_method:
        SellApp.Cast.enum(
          map["payment_method"],
          &SellApp.SdkCreateChargeRequestApplicationJsonPaymentMethod.cast/1
        ),
      payment_methods:
        SellApp.Cast.list(
          map["payment_methods"],
          &SellApp.SdkCreateChargeRequestApplicationJsonPaymentMethods.cast/1
        ),
      custom_payment_method_id: map["custom_payment_method_id"],
      custom_payment_method_ids: map["custom_payment_method_ids"],
      use_all_payment_methods: map["use_all_payment_methods"],
      deliverable:
        SellApp.Cast.nested(
          map["deliverable"],
          &SellApp.CreateChargeRequestApplicationJsonPropertyDeliverable.from_map/1
        ),
      metadata:
        SellApp.Cast.nested(
          map["metadata"],
          &SellApp.CreateChargeRequestApplicationJsonPropertyMetadata.from_map/1
        ),
      coupon_code: map["coupon_code"],
      __additional_properties__:
        Map.drop(map, [
          "email",
          "return_url",
          "cancel_url",
          "webhook",
          "reference",
          "description",
          "currency",
          "total",
          "payment_method",
          "payment_methods",
          "custom_payment_method_id",
          "custom_payment_method_ids",
          "use_all_payment_methods",
          "deliverable",
          "metadata",
          "coupon_code"
        ]),
      __present_fields__: Map.keys(map)
    }
  end

  @doc false
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    known =
      SellApp.Cast.keep_present(
        %{
          "email" => struct.email,
          "return_url" => struct.return_url,
          "cancel_url" => struct.cancel_url,
          "webhook" => struct.webhook,
          "reference" => struct.reference,
          "description" => struct.description,
          "currency" => struct.currency,
          "total" => struct.total,
          "payment_method" =>
            SellApp.Cast.enum(
              struct.payment_method,
              &SellApp.SdkCreateChargeRequestApplicationJsonPaymentMethod.dump/1
            ),
          "payment_methods" =>
            SellApp.Cast.list(
              struct.payment_methods,
              &SellApp.SdkCreateChargeRequestApplicationJsonPaymentMethods.dump/1
            ),
          "custom_payment_method_id" => struct.custom_payment_method_id,
          "custom_payment_method_ids" => struct.custom_payment_method_ids,
          "use_all_payment_methods" => struct.use_all_payment_methods,
          "deliverable" =>
            SellApp.Cast.dump_struct(
              struct.deliverable,
              &SellApp.CreateChargeRequestApplicationJsonPropertyDeliverable.to_map/1
            ),
          "metadata" =>
            SellApp.Cast.dump_struct(
              struct.metadata,
              &SellApp.CreateChargeRequestApplicationJsonPropertyMetadata.to_map/1
            ),
          "coupon_code" => struct.coupon_code
        },
        ["email", "return_url"],
        struct.__present_fields__
      )

    Map.merge(struct.__additional_properties__, known)
  end
end
