# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.SdkDeactivateLicenseRequestApplicationJson do
  @moduledoc """
  SdkDeactivateLicenseRequestApplicationJson model.
  """

  defstruct [
    :license_key,
    :instance_id,
    __additional_properties__: %{},
    __present_fields__: []
  ]

  @type t :: %__MODULE__{
          license_key: String.t(),
          instance_id: String.t(),
          __additional_properties__: map(),
          __present_fields__: [String.t()]
        }

  @schema %{
    name: "SdkDeactivateLicenseRequestApplicationJson",
    properties: %{
      "license_key" => %{required: true, schema: %{kind: :string}},
      "instance_id" => %{required: true, schema: %{kind: :string}}
    },
    additional_properties: true
  }
  @doc false
  def schema, do: @schema

  @doc false
  @spec from_map(map()) :: t()
  def from_map(map) when is_map(map) do
    SellApp.Schema.validate_model!(map, @schema, :response)

    %__MODULE__{
      license_key: map["license_key"],
      instance_id: map["instance_id"],
      __additional_properties__: Map.drop(map, ["license_key", "instance_id"]),
      __present_fields__: Map.keys(map)
    }
  end

  @doc false
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    known =
      SellApp.Cast.keep_present(
        %{
          "license_key" => struct.license_key,
          "instance_id" => struct.instance_id
        },
        ["license_key", "instance_id"],
        struct.__present_fields__
      )

    Map.merge(struct.__additional_properties__, known)
  end
end
