# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.SdkReorderCourseSectionsResponseValue200ApplicationJson do
  @moduledoc """
  SdkReorderCourseSectionsResponseValue200ApplicationJson model.
  """

  defstruct [
    :data,
    __additional_properties__: %{},
    __present_fields__: []
  ]

  @type t :: %__MODULE__{
          data: SellApp.ReorderCourseSectionsResponseValue200ApplicationJsonPropertyData.t(),
          __additional_properties__: map(),
          __present_fields__: [String.t()]
        }

  @schema %{
    name: "SdkReorderCourseSectionsResponseValue200ApplicationJson",
    properties: %{
      "data" => %{
        required: true,
        schema: %{
          kind: :model,
          module: SellApp.ReorderCourseSectionsResponseValue200ApplicationJsonPropertyData
        }
      }
    },
    additional_properties: true
  }
  @doc false
  def schema, do: @schema

  @doc false
  @spec from_map(map()) :: t()
  def from_map(map) when is_map(map) do
    SellApp.Schema.validate_model!(map, @schema, :response)

    %__MODULE__{
      data:
        SellApp.Cast.nested(
          map["data"],
          &SellApp.ReorderCourseSectionsResponseValue200ApplicationJsonPropertyData.from_map/1
        ),
      __additional_properties__: Map.drop(map, ["data"]),
      __present_fields__: Map.keys(map)
    }
  end

  @doc false
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    known =
      SellApp.Cast.keep_present(
        %{
          "data" =>
            SellApp.Cast.dump_struct(
              struct.data,
              &SellApp.ReorderCourseSectionsResponseValue200ApplicationJsonPropertyData.to_map/1
            )
        },
        ["data"],
        struct.__present_fields__
      )

    Map.merge(struct.__additional_properties__, known)
  end
end
