# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.SdkCreateStoreRequestApplicationJson do
  @moduledoc """
  SdkCreateStoreRequestApplicationJson model.
  """

  defstruct [
    :name,
    :slug,
    :visibility,
    __additional_properties__: %{},
    __present_fields__: []
  ]

  @type t :: %__MODULE__{
          name: String.t(),
          slug: String.t(),
          visibility: SellApp.StoreVisibility.t() | nil,
          __additional_properties__: map(),
          __present_fields__: [String.t()]
        }

  @schema %{
    name: "SdkCreateStoreRequestApplicationJson",
    properties: %{
      "name" => %{
        required: true,
        schema: %{kind: :string, min_length: 3, max_length: 48, pattern: "^[\\p{L}\\p{N}\\s]+$"}
      },
      "slug" => %{
        required: true,
        schema: %{kind: :string, min_length: 3, max_length: 63, pattern: "^[A-Za-z0-9]+$"}
      },
      "visibility" => %{
        required: false,
        schema: %{kind: :enum, values: ["PUBLIC", "HIDDEN", "PRIVATE"]}
      }
    },
    additional_properties: true
  }
  @doc false
  def schema, do: @schema

  @doc false
  @spec from_map(map()) :: t()
  def from_map(map) when is_map(map) do
    SellApp.Schema.validate_model!(map, @schema, :response)

    %__MODULE__{
      name: map["name"],
      slug: map["slug"],
      visibility: SellApp.Cast.enum(map["visibility"], &SellApp.StoreVisibility.cast/1),
      __additional_properties__: Map.drop(map, ["name", "slug", "visibility"]),
      __present_fields__: Map.keys(map)
    }
  end

  @doc false
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    known =
      SellApp.Cast.keep_present(
        %{
          "name" => struct.name,
          "slug" => struct.slug,
          "visibility" => SellApp.Cast.enum(struct.visibility, &SellApp.StoreVisibility.dump/1)
        },
        ["name", "slug"],
        struct.__present_fields__
      )

    Map.merge(struct.__additional_properties__, known)
  end
end
