# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.SdkExchangeOAuthTokenResponseValue200ApplicationJson do
  @moduledoc """
  SdkExchangeOAuthTokenResponseValue200ApplicationJson model.
  """

  defstruct [
    :token_type,
    :expires_in,
    :access_token,
    :refresh_token,
    __additional_properties__: %{},
    __present_fields__: []
  ]

  @type t :: %__MODULE__{
          token_type: String.t(),
          expires_in: 3600,
          access_token: String.t(),
          refresh_token: String.t(),
          __additional_properties__: map(),
          __present_fields__: [String.t()]
        }

  @schema %{
    name: "SdkExchangeOAuthTokenResponseValue200ApplicationJson",
    properties: %{
      "token_type" => %{required: true, schema: %{kind: :literal, value: "Bearer"}},
      "expires_in" => %{required: true, schema: %{kind: :literal, value: 3600}},
      "access_token" => %{required: true, schema: %{kind: :string}},
      "refresh_token" => %{required: true, schema: %{kind: :string}}
    },
    additional_properties: true
  }
  @doc false
  def schema, do: @schema

  @doc false
  @spec from_map(map()) :: t()
  def from_map(map) when is_map(map) do
    SellApp.Schema.validate_model!(map, @schema, :response)

    %__MODULE__{
      token_type: map["token_type"],
      expires_in: map["expires_in"],
      access_token: map["access_token"],
      refresh_token: map["refresh_token"],
      __additional_properties__:
        Map.drop(map, ["token_type", "expires_in", "access_token", "refresh_token"]),
      __present_fields__: Map.keys(map)
    }
  end

  @doc false
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    known =
      SellApp.Cast.keep_present(
        %{
          "token_type" => struct.token_type,
          "expires_in" => struct.expires_in,
          "access_token" => struct.access_token,
          "refresh_token" => struct.refresh_token
        },
        ["token_type", "expires_in", "access_token", "refresh_token"],
        struct.__present_fields__
      )

    Map.merge(struct.__additional_properties__, known)
  end
end
