# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.SdkSearchCouponsResponseValue200ApplicationJson do
  @moduledoc """
  SdkSearchCouponsResponseValue200ApplicationJson model.
  """

  defstruct [
    :data,
    :links,
    :meta,
    __additional_properties__: %{},
    __present_fields__: []
  ]

  @type t :: %__MODULE__{
          data: [SellApp.SearchCouponsResponseValue200ApplicationJsonPropertyDataItem.t()],
          links: SellApp.SearchCouponsResponseValue200ApplicationJsonPropertyLinks.t(),
          meta: SellApp.SearchCouponsResponseValue200ApplicationJsonPropertyMeta.t(),
          __additional_properties__: map(),
          __present_fields__: [String.t()]
        }

  @schema %{
    name: "SdkSearchCouponsResponseValue200ApplicationJson",
    properties: %{
      "data" => %{
        required: true,
        schema: %{
          kind: :array,
          items: %{
            kind: :model,
            module: SellApp.SearchCouponsResponseValue200ApplicationJsonPropertyDataItem
          }
        }
      },
      "links" => %{
        required: true,
        schema: %{
          kind: :model,
          module: SellApp.SearchCouponsResponseValue200ApplicationJsonPropertyLinks
        }
      },
      "meta" => %{
        required: true,
        schema: %{
          kind: :model,
          module: SellApp.SearchCouponsResponseValue200ApplicationJsonPropertyMeta
        }
      }
    },
    additional_properties: true
  }
  @doc false
  def schema, do: @schema

  @doc false
  @spec from_map(map()) :: t()
  def from_map(map) when is_map(map) do
    SellApp.Schema.validate_model!(map, @schema, :response)

    %__MODULE__{
      data:
        SellApp.Cast.list(
          map["data"],
          &SellApp.SearchCouponsResponseValue200ApplicationJsonPropertyDataItem.from_map/1
        ),
      links:
        SellApp.Cast.nested(
          map["links"],
          &SellApp.SearchCouponsResponseValue200ApplicationJsonPropertyLinks.from_map/1
        ),
      meta:
        SellApp.Cast.nested(
          map["meta"],
          &SellApp.SearchCouponsResponseValue200ApplicationJsonPropertyMeta.from_map/1
        ),
      __additional_properties__: Map.drop(map, ["data", "links", "meta"]),
      __present_fields__: Map.keys(map)
    }
  end

  @doc false
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    known =
      SellApp.Cast.keep_present(
        %{
          "data" =>
            SellApp.Cast.list(struct.data, fn item ->
              SellApp.Cast.dump_struct(
                item,
                &SellApp.SearchCouponsResponseValue200ApplicationJsonPropertyDataItem.to_map/1
              )
            end),
          "links" =>
            SellApp.Cast.dump_struct(
              struct.links,
              &SellApp.SearchCouponsResponseValue200ApplicationJsonPropertyLinks.to_map/1
            ),
          "meta" =>
            SellApp.Cast.dump_struct(
              struct.meta,
              &SellApp.SearchCouponsResponseValue200ApplicationJsonPropertyMeta.to_map/1
            )
        },
        ["data", "links", "meta"],
        struct.__present_fields__
      )

    Map.merge(struct.__additional_properties__, known)
  end
end
