# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.SdkReplaceCustomPaymentMethodRequestApplicationJson do
  @moduledoc """
  SdkReplaceCustomPaymentMethodRequestApplicationJson model.
  """

  defstruct [
    :type,
    :name,
    :description,
    :instructions,
    :steps,
    :redirect_url,
    :skip_interstitial_page,
    :show_processing_status_page,
    :require_proof_of_payment,
    :enabled,
    :sort_order,
    :modifier,
    __additional_properties__: %{},
    __present_fields__: []
  ]

  @type t :: %__MODULE__{
          type: SellApp.SdkReplaceCustomPaymentMethodRequestApplicationJsonType.t(),
          name: String.t(),
          description: String.t() | nil,
          instructions: String.t() | nil,
          steps: [String.t() | nil] | nil,
          redirect_url: String.t() | nil,
          skip_interstitial_page: boolean() | nil,
          show_processing_status_page: boolean() | nil,
          require_proof_of_payment: boolean() | nil,
          enabled: boolean() | nil,
          sort_order: integer() | nil,
          modifier:
            SellApp.ReplaceCustomPaymentMethodRequestApplicationJsonPropertyModifier.t() | nil,
          __additional_properties__: map(),
          __present_fields__: [String.t()]
        }

  @schema %{
    name: "SdkReplaceCustomPaymentMethodRequestApplicationJson",
    properties: %{
      "type" => %{required: true, schema: %{kind: :enum, values: ["instructions", "redirect"]}},
      "name" => %{required: true, schema: %{kind: :string, max_length: 80}},
      "description" => %{
        required: false,
        schema: %{kind: :nullable, inner: %{kind: :string, max_length: 500}}
      },
      "instructions" => %{
        required: false,
        schema: %{kind: :nullable, inner: %{kind: :string, max_length: 5000}}
      },
      "steps" => %{
        required: false,
        schema: %{
          kind: :nullable,
          inner: %{
            kind: :array,
            items: %{kind: :nullable, inner: %{kind: :string, max_length: 1000}},
            max_items: 3
          }
        }
      },
      "redirect_url" => %{
        required: false,
        schema: %{kind: :nullable, inner: %{kind: :string, format: "uri", max_length: 2000}}
      },
      "skip_interstitial_page" => %{required: false, schema: %{kind: :boolean}},
      "show_processing_status_page" => %{required: false, schema: %{kind: :boolean}},
      "require_proof_of_payment" => %{required: false, schema: %{kind: :boolean}},
      "enabled" => %{required: false, schema: %{kind: :boolean}},
      "sort_order" => %{required: false, schema: %{kind: :integer, minimum: 0}},
      "modifier" => %{
        required: false,
        schema: %{
          kind: :nullable,
          inner: %{
            kind: :model,
            module: SellApp.ReplaceCustomPaymentMethodRequestApplicationJsonPropertyModifier
          }
        }
      }
    },
    additional_properties: true
  }
  @doc false
  def schema, do: @schema

  @doc false
  @spec from_map(map()) :: t()
  def from_map(map) when is_map(map) do
    SellApp.Schema.validate_model!(map, @schema, :response)

    %__MODULE__{
      type:
        SellApp.Cast.enum(
          map["type"],
          &SellApp.SdkReplaceCustomPaymentMethodRequestApplicationJsonType.cast/1
        ),
      name: map["name"],
      description: map["description"],
      instructions: map["instructions"],
      steps: map["steps"],
      redirect_url: map["redirect_url"],
      skip_interstitial_page: map["skip_interstitial_page"],
      show_processing_status_page: map["show_processing_status_page"],
      require_proof_of_payment: map["require_proof_of_payment"],
      enabled: map["enabled"],
      sort_order: map["sort_order"],
      modifier:
        SellApp.Cast.nested(
          map["modifier"],
          &SellApp.ReplaceCustomPaymentMethodRequestApplicationJsonPropertyModifier.from_map/1
        ),
      __additional_properties__:
        Map.drop(map, [
          "type",
          "name",
          "description",
          "instructions",
          "steps",
          "redirect_url",
          "skip_interstitial_page",
          "show_processing_status_page",
          "require_proof_of_payment",
          "enabled",
          "sort_order",
          "modifier"
        ]),
      __present_fields__: Map.keys(map)
    }
  end

  @doc false
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    known =
      SellApp.Cast.keep_present(
        %{
          "type" =>
            SellApp.Cast.enum(
              struct.type,
              &SellApp.SdkReplaceCustomPaymentMethodRequestApplicationJsonType.dump/1
            ),
          "name" => struct.name,
          "description" => struct.description,
          "instructions" => struct.instructions,
          "steps" => struct.steps,
          "redirect_url" => struct.redirect_url,
          "skip_interstitial_page" => struct.skip_interstitial_page,
          "show_processing_status_page" => struct.show_processing_status_page,
          "require_proof_of_payment" => struct.require_proof_of_payment,
          "enabled" => struct.enabled,
          "sort_order" => struct.sort_order,
          "modifier" =>
            SellApp.Cast.dump_struct(
              struct.modifier,
              &SellApp.ReplaceCustomPaymentMethodRequestApplicationJsonPropertyModifier.to_map/1
            )
        },
        ["type", "name"],
        struct.__present_fields__
      )

    Map.merge(struct.__additional_properties__, known)
  end
end
