# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.SdkPauseSubscriptionRequestApplicationJson do
  @moduledoc """
  SdkPauseSubscriptionRequestApplicationJson model.
  """

  defstruct [
    :idempotency_key,
    :resume_at,
    :reason,
    __additional_properties__: %{},
    __present_fields__: []
  ]

  @type t :: %__MODULE__{
          idempotency_key: String.t() | nil,
          resume_at: String.t() | nil,
          reason: String.t() | nil,
          __additional_properties__: map(),
          __present_fields__: [String.t()]
        }

  @schema %{
    name: "SdkPauseSubscriptionRequestApplicationJson",
    properties: %{
      "idempotency_key" => %{
        required: false,
        schema: %{kind: :nullable, inner: %{kind: :string, max_length: 128}}
      },
      "resume_at" => %{
        required: false,
        schema: %{kind: :nullable, inner: %{kind: :string, format: "date-time"}}
      },
      "reason" => %{
        required: false,
        schema: %{kind: :nullable, inner: %{kind: :string, max_length: 500}}
      }
    },
    additional_properties: true
  }
  @doc false
  def schema, do: @schema

  @doc false
  @spec from_map(map()) :: t()
  def from_map(map) when is_map(map) do
    SellApp.Schema.validate_model!(map, @schema, :response)

    %__MODULE__{
      idempotency_key: map["idempotency_key"],
      resume_at: map["resume_at"],
      reason: map["reason"],
      __additional_properties__: Map.drop(map, ["idempotency_key", "resume_at", "reason"]),
      __present_fields__: Map.keys(map)
    }
  end

  @doc false
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    known =
      SellApp.Cast.keep_present(
        %{
          "idempotency_key" => struct.idempotency_key,
          "resume_at" => struct.resume_at,
          "reason" => struct.reason
        },
        [],
        struct.__present_fields__
      )

    Map.merge(struct.__additional_properties__, known)
  end
end
