# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.SdkUpdateGroupRequestApplicationJson do
  @moduledoc """
  SdkUpdateGroupRequestApplicationJson model.
  """

  defstruct [
    :title,
    :unlisted,
    :order,
    :product_ids,
    :section_id,
    __additional_properties__: %{},
    __present_fields__: []
  ]

  @type t :: %__MODULE__{
          title: String.t() | nil,
          unlisted: boolean() | nil,
          order: integer() | nil,
          product_ids: [integer()] | nil,
          section_id: integer() | nil,
          __additional_properties__: map(),
          __present_fields__: [String.t()]
        }

  @schema %{
    name: "SdkUpdateGroupRequestApplicationJson",
    properties: %{
      "title" => %{required: false, schema: %{kind: :string}},
      "unlisted" => %{required: false, schema: %{kind: :boolean}},
      "order" => %{required: false, schema: %{kind: :nullable, inner: %{kind: :integer}}},
      "product_ids" => %{
        required: false,
        schema: %{kind: :array, items: %{kind: :integer}, max_items: 100, unique_items: true}
      },
      "section_id" => %{required: false, schema: %{kind: :nullable, inner: %{kind: :integer}}}
    },
    additional_properties: true
  }
  @doc false
  def schema, do: @schema

  @doc false
  @spec from_map(map()) :: t()
  def from_map(map) when is_map(map) do
    SellApp.Schema.validate_model!(map, @schema, :response)

    %__MODULE__{
      title: map["title"],
      unlisted: map["unlisted"],
      order: map["order"],
      product_ids: map["product_ids"],
      section_id: map["section_id"],
      __additional_properties__:
        Map.drop(map, ["title", "unlisted", "order", "product_ids", "section_id"]),
      __present_fields__: Map.keys(map)
    }
  end

  @doc false
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    known =
      SellApp.Cast.keep_present(
        %{
          "title" => struct.title,
          "unlisted" => struct.unlisted,
          "order" => struct.order,
          "product_ids" => struct.product_ids,
          "section_id" => struct.section_id
        },
        [],
        struct.__present_fields__
      )

    Map.merge(struct.__additional_properties__, known)
  end
end
