# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.SdkReplaceHighlightMediaMetadataRequestApplicationJson do
  @moduledoc """
  SdkReplaceHighlightMediaMetadataRequestApplicationJson model.
  """

  defstruct [
    :cta_title,
    :product_id,
    __additional_properties__: %{},
    __present_fields__: []
  ]

  @type t :: %__MODULE__{
          cta_title: String.t() | nil,
          product_id: integer() | nil,
          __additional_properties__: map(),
          __present_fields__: [String.t()]
        }

  @schema %{
    name: "SdkReplaceHighlightMediaMetadataRequestApplicationJson",
    properties: %{
      "cta_title" => %{required: false, schema: %{kind: :string, max_length: 510}},
      "product_id" => %{
        required: false,
        schema: %{kind: :nullable, inner: %{kind: :integer, minimum: 1}}
      }
    },
    additional_properties: true
  }
  @doc false
  def schema, do: @schema

  @doc false
  @spec from_map(map()) :: t()
  def from_map(map) when is_map(map) do
    SellApp.Schema.validate_model!(map, @schema, :response)

    %__MODULE__{
      cta_title: map["cta_title"],
      product_id: map["product_id"],
      __additional_properties__: Map.drop(map, ["cta_title", "product_id"]),
      __present_fields__: Map.keys(map)
    }
  end

  @doc false
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    known =
      SellApp.Cast.keep_present(
        %{
          "cta_title" => struct.cta_title,
          "product_id" => struct.product_id
        },
        [],
        struct.__present_fields__
      )

    Map.merge(struct.__additional_properties__, known)
  end
end
