# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.SdkGetOAuthAuthorizationRequestResponseValue401ApplicationJson do
  @moduledoc """
  SdkGetOAuthAuthorizationRequestResponseValue401ApplicationJson model.
  """

  defstruct [
    :error,
    :error_description,
    :error_uri,
    __additional_properties__: %{},
    __present_fields__: []
  ]

  @type t :: %__MODULE__{
          error: String.t(),
          error_description: String.t() | nil,
          error_uri: String.t() | nil,
          __additional_properties__: map(),
          __present_fields__: [String.t()]
        }

  @schema %{
    name: "SdkGetOAuthAuthorizationRequestResponseValue401ApplicationJson",
    properties: %{
      "error" => %{required: true, schema: %{kind: :string}},
      "error_description" => %{required: false, schema: %{kind: :string}},
      "error_uri" => %{required: false, schema: %{kind: :string, format: "uri"}}
    },
    additional_properties: true
  }
  @doc false
  def schema, do: @schema

  @doc false
  @spec from_map(map()) :: t()
  def from_map(map) when is_map(map) do
    SellApp.Schema.validate_model!(map, @schema, :response)

    %__MODULE__{
      error: map["error"],
      error_description: map["error_description"],
      error_uri: map["error_uri"],
      __additional_properties__: Map.drop(map, ["error", "error_description", "error_uri"]),
      __present_fields__: Map.keys(map)
    }
  end

  @doc false
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    known =
      SellApp.Cast.keep_present(
        %{
          "error" => struct.error,
          "error_description" => struct.error_description,
          "error_uri" => struct.error_uri
        },
        ["error"],
        struct.__present_fields__
      )

    Map.merge(struct.__additional_properties__, known)
  end
end
