# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.SdkCreateWebhookChannelRequestApplicationJson do
  @moduledoc """
  SdkCreateWebhookChannelRequestApplicationJson model.
  """

  defstruct [
    :url,
    :allowed_notifications,
    :name,
    __additional_properties__: %{},
    __present_fields__: []
  ]

  @type t :: %__MODULE__{
          url: String.t(),
          allowed_notifications: [
            SellApp.SdkCreateWebhookChannelRequestApplicationJsonAllowedNotifications.t()
          ],
          name: String.t() | nil,
          __additional_properties__: map(),
          __present_fields__: [String.t()]
        }

  @schema %{
    name: "SdkCreateWebhookChannelRequestApplicationJson",
    properties: %{
      "url" => %{required: true, schema: %{kind: :string, format: "uri", max_length: 2048}},
      "allowed_notifications" => %{
        required: true,
        schema: %{
          kind: :array,
          items: %{
            kind: :enum,
            values: [
              "booking.cancelled",
              "booking.rescheduled",
              "cash_app.payment_requires_attention",
              "charge.completed",
              "charge.created",
              "charge.disputed",
              "charge.partial_paid",
              "charge.review",
              "feedback.created",
              "order.completed",
              "order.created",
              "order.disputed",
              "order.manual_payment_completed",
              "order.paid",
              "order.partial_paid",
              "product.created",
              "product.trashed",
              "product.updated",
              "subscription.cancelled",
              "subscription.created",
              "subscription.renewed",
              "ticket_message.created",
              "variant.created",
              "variant.sold_out",
              "variant.updated"
            ]
          },
          unique_items: true
        }
      },
      "name" => %{
        required: false,
        schema: %{kind: :nullable, inner: %{kind: :string, max_length: 100}}
      }
    },
    additional_properties: true
  }
  @doc false
  def schema, do: @schema

  @doc false
  @spec from_map(map()) :: t()
  def from_map(map) when is_map(map) do
    SellApp.Schema.validate_model!(map, @schema, :response)

    %__MODULE__{
      url: map["url"],
      allowed_notifications:
        SellApp.Cast.list(
          map["allowed_notifications"],
          &SellApp.SdkCreateWebhookChannelRequestApplicationJsonAllowedNotifications.cast/1
        ),
      name: map["name"],
      __additional_properties__: Map.drop(map, ["url", "allowed_notifications", "name"]),
      __present_fields__: Map.keys(map)
    }
  end

  @doc false
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    known =
      SellApp.Cast.keep_present(
        %{
          "url" => struct.url,
          "allowed_notifications" =>
            SellApp.Cast.list(
              struct.allowed_notifications,
              &SellApp.SdkCreateWebhookChannelRequestApplicationJsonAllowedNotifications.dump/1
            ),
          "name" => struct.name
        },
        ["url", "allowed_notifications"],
        struct.__present_fields__
      )

    Map.merge(struct.__additional_properties__, known)
  end
end
