# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.SdkReplaceRewardRuleRequestApplicationJson do
  @moduledoc """
  SdkReplaceRewardRuleRequestApplicationJson model.
  """

  defstruct [
    :name,
    :description,
    :is_active,
    :trigger_type,
    :trigger_threshold,
    :outputs,
    :expected_updated_at,
    __additional_properties__: %{},
    __present_fields__: []
  ]

  @type t :: %__MODULE__{
          name: String.t() | nil,
          description: String.t() | nil,
          is_active: boolean() | nil,
          trigger_type: SellApp.SdkReplaceRewardRuleRequestApplicationJsonTriggerType.t() | nil,
          trigger_threshold: integer() | nil,
          outputs: [SellApp.ReplaceRewardRuleRequestApplicationJsonPropertyOutputsItem.t()] | nil,
          expected_updated_at: String.t() | nil,
          __additional_properties__: map(),
          __present_fields__: [String.t()]
        }

  @schema %{
    name: "SdkReplaceRewardRuleRequestApplicationJson",
    properties: %{
      "name" => %{required: false, schema: %{kind: :string, min_length: 1, max_length: 120}},
      "description" => %{
        required: false,
        schema: %{kind: :nullable, inner: %{kind: :string, max_length: 255}}
      },
      "is_active" => %{required: false, schema: %{kind: :boolean}},
      "trigger_type" => %{
        required: false,
        schema: %{kind: :enum, values: ["PURCHASE_COUNT", "TOTAL_SPENT"]}
      },
      "trigger_threshold" => %{required: false, schema: %{kind: :integer, minimum: 1}},
      "outputs" => %{
        required: false,
        schema: %{
          kind: :array,
          items: %{
            kind: :model,
            module: SellApp.ReplaceRewardRuleRequestApplicationJsonPropertyOutputsItem
          },
          min_items: 1
        }
      },
      "expected_updated_at" => %{required: false, schema: %{kind: :string, format: "date-time"}}
    },
    additional_properties: true
  }
  @doc false
  def schema, do: @schema

  @doc false
  @spec from_map(map()) :: t()
  def from_map(map) when is_map(map) do
    SellApp.Schema.validate_model!(map, @schema, :response)

    %__MODULE__{
      name: map["name"],
      description: map["description"],
      is_active: map["is_active"],
      trigger_type:
        SellApp.Cast.enum(
          map["trigger_type"],
          &SellApp.SdkReplaceRewardRuleRequestApplicationJsonTriggerType.cast/1
        ),
      trigger_threshold: map["trigger_threshold"],
      outputs:
        SellApp.Cast.list(
          map["outputs"],
          &SellApp.ReplaceRewardRuleRequestApplicationJsonPropertyOutputsItem.from_map/1
        ),
      expected_updated_at: map["expected_updated_at"],
      __additional_properties__:
        Map.drop(map, [
          "name",
          "description",
          "is_active",
          "trigger_type",
          "trigger_threshold",
          "outputs",
          "expected_updated_at"
        ]),
      __present_fields__: Map.keys(map)
    }
  end

  @doc false
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    known =
      SellApp.Cast.keep_present(
        %{
          "name" => struct.name,
          "description" => struct.description,
          "is_active" => struct.is_active,
          "trigger_type" =>
            SellApp.Cast.enum(
              struct.trigger_type,
              &SellApp.SdkReplaceRewardRuleRequestApplicationJsonTriggerType.dump/1
            ),
          "trigger_threshold" => struct.trigger_threshold,
          "outputs" =>
            SellApp.Cast.list(struct.outputs, fn item ->
              SellApp.Cast.dump_struct(
                item,
                &SellApp.ReplaceRewardRuleRequestApplicationJsonPropertyOutputsItem.to_map/1
              )
            end),
          "expected_updated_at" => struct.expected_updated_at
        },
        [],
        struct.__present_fields__
      )

    Map.merge(struct.__additional_properties__, known)
  end
end
