# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.SdkReplaceGeneralStoreSettingsRequestApplicationJson do
  @moduledoc """
  SdkReplaceGeneralStoreSettingsRequestApplicationJson model.
  """

  defstruct [
    :name,
    :visibility,
    :timezone,
    :currency,
    :dark_mode,
    __additional_properties__: %{},
    __present_fields__: []
  ]

  @type t :: %__MODULE__{
          name: String.t(),
          visibility: SellApp.CourseVisibility.t(),
          timezone: String.t(),
          currency: String.t(),
          dark_mode: SellApp.DarkMode.t() | nil,
          __additional_properties__: map(),
          __present_fields__: [String.t()]
        }

  @schema %{
    name: "SdkReplaceGeneralStoreSettingsRequestApplicationJson",
    properties: %{
      "name" => %{required: true, schema: %{kind: :string, max_length: 48}},
      "visibility" => %{
        required: true,
        schema: %{kind: :enum, values: ["PUBLIC", "HIDDEN", "PRIVATE"]}
      },
      "timezone" => %{required: true, schema: %{kind: :string}},
      "currency" => %{required: true, schema: %{kind: :string, min_length: 3, max_length: 3}},
      "dark_mode" => %{
        required: false,
        schema: %{
          kind: :nullable,
          inner: %{kind: :enum, values: ["light", "dark", "system", "null"]}
        }
      }
    },
    additional_properties: true
  }
  @doc false
  def schema, do: @schema

  @doc false
  @spec from_map(map()) :: t()
  def from_map(map) when is_map(map) do
    SellApp.Schema.validate_model!(map, @schema, :response)

    %__MODULE__{
      name: map["name"],
      visibility: SellApp.Cast.enum(map["visibility"], &SellApp.CourseVisibility.cast/1),
      timezone: map["timezone"],
      currency: map["currency"],
      dark_mode: SellApp.Cast.enum(map["dark_mode"], &SellApp.DarkMode.cast/1),
      __additional_properties__:
        Map.drop(map, ["name", "visibility", "timezone", "currency", "dark_mode"]),
      __present_fields__: Map.keys(map)
    }
  end

  @doc false
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    known =
      SellApp.Cast.keep_present(
        %{
          "name" => struct.name,
          "visibility" => SellApp.Cast.enum(struct.visibility, &SellApp.CourseVisibility.dump/1),
          "timezone" => struct.timezone,
          "currency" => struct.currency,
          "dark_mode" => SellApp.Cast.enum(struct.dark_mode, &SellApp.DarkMode.dump/1)
        },
        ["name", "visibility", "timezone", "currency"],
        struct.__present_fields__
      )

    Map.merge(struct.__additional_properties__, known)
  end
end
