# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.SearchCreditsProductsRequestApplicationJsonPropertyFiltersItemField do
  @moduledoc """
  SearchCreditsProductsRequestApplicationJsonPropertyFiltersItemField enum.
  """

  @type t :: :id | :visibility | :is_draft

  @doc "All known values."
  @spec values() :: [t()]
  def values, do: [:id, :visibility, :is_draft]

  @doc "Casts a wire string to its atom; unknown values pass through unchanged."
  @spec cast(String.t() | nil) :: t() | String.t() | nil
  def cast("id"), do: :id
  def cast("visibility"), do: :visibility
  def cast("is_draft"), do: :is_draft
  def cast(other), do: other

  @doc "Dumps an atom back to its wire string."
  @spec dump(t() | String.t()) :: String.t()
  def dump(:id), do: "id"
  def dump(:visibility), do: "visibility"
  def dump(:is_draft), do: "is_draft"
  def dump(other) when is_binary(other), do: other
end
