# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.SearchProductsResponseValue200ApplicationJsonPropertyDataItem do
  @moduledoc """
  SearchProductsResponseValue200ApplicationJsonPropertyDataItem model.
  """

  defstruct [
    :id,
    :title,
    :slug,
    :description,
    :images,
    :order,
    :visibility,
    :delivery_text,
    :additional_information,
    :other_settings,
    :deleted_at,
    :created_at,
    :updated_at,
    :store_id,
    :section_id,
    :section_order,
    :is_discoverable,
    :variants,
    :url,
    __additional_properties__: %{},
    __present_fields__: []
  ]

  @type t :: %__MODULE__{
          id: integer(),
          title: String.t(),
          slug: String.t(),
          description: String.t(),
          images: [
            SellApp.SearchProductsResponseValue200ApplicationJsonPropertyDataItemPropertyImagesItem.t()
          ],
          order: integer() | nil,
          visibility: String.t(),
          delivery_text: String.t(),
          additional_information: [
            SellApp.SearchProductsResponseValue200ApplicationJsonPropertyDataItemPropertyAdditionalInformationItem.t()
          ],
          other_settings:
            SellApp.SearchProductsResponseValue200ApplicationJsonPropertyDataItemPropertyOtherSettings.t(),
          deleted_at: String.t() | nil,
          created_at: String.t(),
          updated_at: String.t(),
          store_id: integer(),
          section_id: integer() | nil,
          section_order: integer() | nil,
          is_discoverable: boolean(),
          variants: [
            SellApp.SearchProductsResponseValue200ApplicationJsonPropertyDataItemPropertyVariantsItem.t()
          ],
          url: String.t(),
          __additional_properties__: map(),
          __present_fields__: [String.t()]
        }

  @schema %{
    name: "SearchProductsResponseValue200ApplicationJsonPropertyDataItem",
    properties: %{
      "id" => %{required: true, schema: %{kind: :integer}},
      "title" => %{required: true, schema: %{kind: :string}},
      "slug" => %{required: true, schema: %{kind: :string}},
      "description" => %{required: true, schema: %{kind: :string}},
      "images" => %{
        required: true,
        schema: %{
          kind: :array,
          items: %{
            kind: :model,
            module:
              SellApp.SearchProductsResponseValue200ApplicationJsonPropertyDataItemPropertyImagesItem
          }
        }
      },
      "order" => %{required: true, schema: %{kind: :nullable, inner: %{kind: :integer}}},
      "visibility" => %{required: true, schema: %{kind: :string}},
      "delivery_text" => %{required: true, schema: %{kind: :string}},
      "additional_information" => %{
        required: true,
        schema: %{
          kind: :array,
          items: %{
            kind: :model,
            module:
              SellApp.SearchProductsResponseValue200ApplicationJsonPropertyDataItemPropertyAdditionalInformationItem
          }
        }
      },
      "other_settings" => %{
        required: true,
        schema: %{
          kind: :model,
          module:
            SellApp.SearchProductsResponseValue200ApplicationJsonPropertyDataItemPropertyOtherSettings
        }
      },
      "deleted_at" => %{
        required: true,
        schema: %{kind: :nullable, inner: %{kind: :string, format: "date-time"}}
      },
      "created_at" => %{required: true, schema: %{kind: :string, format: "date-time"}},
      "updated_at" => %{required: true, schema: %{kind: :string, format: "date-time"}},
      "store_id" => %{required: true, schema: %{kind: :integer}},
      "section_id" => %{required: true, schema: %{kind: :nullable, inner: %{kind: :integer}}},
      "section_order" => %{required: true, schema: %{kind: :nullable, inner: %{kind: :integer}}},
      "is_discoverable" => %{required: true, schema: %{kind: :boolean}},
      "variants" => %{
        required: true,
        schema: %{
          kind: :array,
          items: %{
            kind: :model,
            module:
              SellApp.SearchProductsResponseValue200ApplicationJsonPropertyDataItemPropertyVariantsItem
          }
        }
      },
      "url" => %{required: true, schema: %{kind: :string}}
    },
    additional_properties: true
  }
  @doc false
  def schema, do: @schema

  @doc false
  @spec from_map(map()) :: t()
  def from_map(map) when is_map(map) do
    SellApp.Schema.validate_model!(map, @schema, :response)

    %__MODULE__{
      id: map["id"],
      title: map["title"],
      slug: map["slug"],
      description: map["description"],
      images:
        SellApp.Cast.list(
          map["images"],
          &SellApp.SearchProductsResponseValue200ApplicationJsonPropertyDataItemPropertyImagesItem.from_map/1
        ),
      order: map["order"],
      visibility: map["visibility"],
      delivery_text: map["delivery_text"],
      additional_information:
        SellApp.Cast.list(
          map["additional_information"],
          &SellApp.SearchProductsResponseValue200ApplicationJsonPropertyDataItemPropertyAdditionalInformationItem.from_map/1
        ),
      other_settings:
        SellApp.Cast.nested(
          map["other_settings"],
          &SellApp.SearchProductsResponseValue200ApplicationJsonPropertyDataItemPropertyOtherSettings.from_map/1
        ),
      deleted_at: map["deleted_at"],
      created_at: map["created_at"],
      updated_at: map["updated_at"],
      store_id: map["store_id"],
      section_id: map["section_id"],
      section_order: map["section_order"],
      is_discoverable: map["is_discoverable"],
      variants:
        SellApp.Cast.list(
          map["variants"],
          &SellApp.SearchProductsResponseValue200ApplicationJsonPropertyDataItemPropertyVariantsItem.from_map/1
        ),
      url: map["url"],
      __additional_properties__:
        Map.drop(map, [
          "id",
          "title",
          "slug",
          "description",
          "images",
          "order",
          "visibility",
          "delivery_text",
          "additional_information",
          "other_settings",
          "deleted_at",
          "created_at",
          "updated_at",
          "store_id",
          "section_id",
          "section_order",
          "is_discoverable",
          "variants",
          "url"
        ]),
      __present_fields__: Map.keys(map)
    }
  end

  @doc false
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    known =
      SellApp.Cast.keep_present(
        %{
          "id" => struct.id,
          "title" => struct.title,
          "slug" => struct.slug,
          "description" => struct.description,
          "images" =>
            SellApp.Cast.list(struct.images, fn item ->
              SellApp.Cast.dump_struct(
                item,
                &SellApp.SearchProductsResponseValue200ApplicationJsonPropertyDataItemPropertyImagesItem.to_map/1
              )
            end),
          "order" => struct.order,
          "visibility" => struct.visibility,
          "delivery_text" => struct.delivery_text,
          "additional_information" =>
            SellApp.Cast.list(struct.additional_information, fn item ->
              SellApp.Cast.dump_struct(
                item,
                &SellApp.SearchProductsResponseValue200ApplicationJsonPropertyDataItemPropertyAdditionalInformationItem.to_map/1
              )
            end),
          "other_settings" =>
            SellApp.Cast.dump_struct(
              struct.other_settings,
              &SellApp.SearchProductsResponseValue200ApplicationJsonPropertyDataItemPropertyOtherSettings.to_map/1
            ),
          "deleted_at" => struct.deleted_at,
          "created_at" => struct.created_at,
          "updated_at" => struct.updated_at,
          "store_id" => struct.store_id,
          "section_id" => struct.section_id,
          "section_order" => struct.section_order,
          "is_discoverable" => struct.is_discoverable,
          "variants" =>
            SellApp.Cast.list(struct.variants, fn item ->
              SellApp.Cast.dump_struct(
                item,
                &SellApp.SearchProductsResponseValue200ApplicationJsonPropertyDataItemPropertyVariantsItem.to_map/1
              )
            end),
          "url" => struct.url
        },
        [
          "id",
          "title",
          "slug",
          "description",
          "images",
          "order",
          "visibility",
          "delivery_text",
          "additional_information",
          "other_settings",
          "deleted_at",
          "created_at",
          "updated_at",
          "store_id",
          "section_id",
          "section_order",
          "is_discoverable",
          "variants",
          "url"
        ],
        struct.__present_fields__
      )

    Map.merge(struct.__additional_properties__, known)
  end
end
