# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.SearchCreditsProductsRequestApplicationJsonPropertySortItemField do
  @moduledoc """
  SearchCreditsProductsRequestApplicationJsonPropertySortItemField enum.
  """

  @type t :: :id | :title | :created_at | :updated_at

  @doc "All known values."
  @spec values() :: [t()]
  def values, do: [:id, :title, :created_at, :updated_at]

  @doc "Casts a wire string to its atom; unknown values pass through unchanged."
  @spec cast(String.t() | nil) :: t() | String.t() | nil
  def cast("id"), do: :id
  def cast("title"), do: :title
  def cast("created_at"), do: :created_at
  def cast("updated_at"), do: :updated_at
  def cast(other), do: other

  @doc "Dumps an atom back to its wire string."
  @spec dump(t() | String.t()) :: String.t()
  def dump(:id), do: "id"
  def dump(:title), do: "title"
  def dump(:created_at), do: "created_at"
  def dump(:updated_at), do: "updated_at"
  def dump(other) when is_binary(other), do: other
end
