# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.SearchTicketsRequestApplicationJsonPropertyFiltersItemType do
  @moduledoc """
  SearchTicketsRequestApplicationJsonPropertyFiltersItemType enum.
  """

  @type t :: :and | :or

  @doc "All known values."
  @spec values() :: [t()]
  def values, do: [:and, :or]

  @doc "Casts a wire string to its atom; unknown values pass through unchanged."
  @spec cast(String.t() | nil) :: t() | String.t() | nil
  def cast("and"), do: :and
  def cast("or"), do: :or
  def cast(other), do: other

  @doc "Dumps an atom back to its wire string."
  @spec dump(t() | String.t()) :: String.t()
  def dump(:and), do: "and"
  def dump(:or), do: "or"
  def dump(other) when is_binary(other), do: other
end
