# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.Tickets do
  @moduledoc """
  Operations for the Tickets API.
  """

  @doc """
  List all tickets

  List your store's support tickets, 15 per page by default.

  ## Parameters

    * `params` — query parameters: `:limit`, `:page`
    * `opts` — per-request options (see `SellApp.Client.request/5`)
  """
  @spec list(SellApp.Client.t(), map(), keyword()) ::
          {:ok,
           SellApp.Page.t(SellApp.ListTicketsResponseValue200ApplicationJsonPropertyDataItem.t())}
          | {:error, SellApp.Error.error()}
  def list(client, params \\ %{}, opts \\ []) do
    with {:ok, body} <-
           SellApp.Client.request(
             client,
             :get,
             "/v1/tickets",
             params,
             Keyword.put(opts, :operation_id, "listTickets")
           ) do
      raw_response = if match?(%SellApp.Response{}, body), do: body, else: nil
      body = if raw_response, do: raw_response.data, else: body

      fetch_next = fn cursor ->
        list(
          client,
          SellApp.Page.next_params(params, "page", cursor),
          Keyword.delete(opts, :with_response)
        )
      end

      result =
        SellApp.Page.from_map(
          body,
          "data",
          &SellApp.ListTicketsResponseValue200ApplicationJsonPropertyDataItem.from_map/1,
          fetch_next,
          base_url: client.base_url,
          path: "/v1/tickets",
          pagination_param: "page"
        )

      {:ok, if(raw_response, do: %{raw_response | data: result}, else: result)}
    end
  end

  @doc """
  Retrieve specific ticket

  Retrieve a support ticket by its ID.

  ## Parameters

    * `ticket` — The ticket path parameter.
    * `opts` — per-request options (see `SellApp.Client.request/5`)
  """
  @spec get(SellApp.Client.t(), String.t(), keyword()) ::
          {:ok, SellApp.SdkGetTicketResponseValue200ApplicationJson.t()}
          | {:error, SellApp.Error.error()}
  def get(client, ticket, opts \\ []) do
    with {:ok, body} <-
           SellApp.Client.request(
             client,
             :get,
             "/v1/tickets/#{URI.encode(ticket, &URI.char_unreserved?/1)}",
             %{},
             Keyword.put(opts, :operation_id, "getTicket")
           ) do
      raw_response = if match?(%SellApp.Response{}, body), do: body, else: nil
      body = if raw_response, do: raw_response.data, else: body

      SellApp.Schema.validate_value!(
        body,
        %{kind: :model, module: SellApp.SdkGetTicketResponseValue200ApplicationJson},
        :response,
        "$response"
      )

      result =
        SellApp.Cast.nested(body, &SellApp.SdkGetTicketResponseValue200ApplicationJson.from_map/1)

      {:ok, if(raw_response, do: %{raw_response | data: result}, else: result)}
    end
  end

  @doc """
  Search tickets

  Search tickets using JSON body filters, search terms, includes, and sort instructions.

  ## Parameters

    * `params` — request body map
    * `opts` — per-request options (see `SellApp.Client.request/5`)
  """
  @spec search(SellApp.Client.t(), map(), keyword()) ::
          {:ok,
           SellApp.Page.t(
             SellApp.SearchTicketsResponseValue200ApplicationJsonPropertyDataItem.t()
           )}
          | {:error, SellApp.Error.error()}
  def search(client, params \\ %{}, opts \\ []) do
    SellApp.Schema.validate_value!(
      params,
      %{kind: :model, module: SellApp.SdkSearchTicketsRequestApplicationJson},
      :request,
      "$request.body"
    )

    with {:ok, body} <-
           SellApp.Client.request(
             client,
             :post,
             "/v1/tickets/search",
             params,
             Keyword.put(Keyword.put(opts, :request_body, true), :operation_id, "searchTickets")
           ) do
      raw_response = if match?(%SellApp.Response{}, body), do: body, else: nil
      body = if raw_response, do: raw_response.data, else: body

      fetch_next = fn cursor ->
        search(
          client,
          SellApp.Page.next_params(params, "after", cursor),
          Keyword.delete(opts, :with_response)
        )
      end

      result =
        SellApp.Page.from_map(
          body,
          "data",
          &SellApp.SearchTicketsResponseValue200ApplicationJsonPropertyDataItem.from_map/1,
          fetch_next,
          base_url: client.base_url,
          path: "/v1/tickets/search",
          pagination_param: "after"
        )

      {:ok, if(raw_response, do: %{raw_response | data: result}, else: result)}
    end
  end

  @doc """
  List all tickets

  List your store's support tickets, 15 per page by default. This v2 route is store-scoped. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.

  ## Parameters

    * `params` — query parameters: `:limit`, `:page`
    * `opts` — per-request options (see `SellApp.Client.request/5`)
  """
  @spec v2_list_tickets(SellApp.Client.t(), map(), keyword()) ::
          {:ok,
           SellApp.Page.t(
             SellApp.V2ListTicketsResponseValue200ApplicationJsonPropertyDataItem.t()
           )}
          | {:error, SellApp.Error.error()}
  def v2_list_tickets(client, params \\ %{}, opts \\ []) do
    with {:ok, body} <-
           SellApp.Client.request(
             client,
             :get,
             "/v2/tickets",
             params,
             Keyword.put(opts, :operation_id, "v2ListTickets")
           ) do
      raw_response = if match?(%SellApp.Response{}, body), do: body, else: nil
      body = if raw_response, do: raw_response.data, else: body

      fetch_next = fn cursor ->
        v2_list_tickets(
          client,
          SellApp.Page.next_params(params, "page", cursor),
          Keyword.delete(opts, :with_response)
        )
      end

      result =
        SellApp.Page.from_map(
          body,
          "data",
          &SellApp.V2ListTicketsResponseValue200ApplicationJsonPropertyDataItem.from_map/1,
          fetch_next,
          base_url: client.base_url,
          path: "/v2/tickets",
          pagination_param: "page"
        )

      {:ok, if(raw_response, do: %{raw_response | data: result}, else: result)}
    end
  end

  @doc """
  Search tickets

  Search tickets using JSON body filters, search terms, includes, and sort instructions. This v2 route is store-scoped. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.

  ## Parameters

    * `params` — request body map
    * `opts` — per-request options (see `SellApp.Client.request/5`)
  """
  @spec v2_search_tickets(SellApp.Client.t(), map(), keyword()) ::
          {:ok,
           SellApp.Page.t(
             SellApp.V2SearchTicketsResponseValue200ApplicationJsonPropertyDataItem.t()
           )}
          | {:error, SellApp.Error.error()}
  def v2_search_tickets(client, params \\ %{}, opts \\ []) do
    SellApp.Schema.validate_value!(
      params,
      %{kind: :model, module: SellApp.SdkV2SearchTicketsRequestApplicationJson},
      :request,
      "$request.body"
    )

    with {:ok, body} <-
           SellApp.Client.request(
             client,
             :post,
             "/v2/tickets/search",
             params,
             Keyword.put(Keyword.put(opts, :request_body, true), :operation_id, "v2SearchTickets")
           ) do
      raw_response = if match?(%SellApp.Response{}, body), do: body, else: nil
      body = if raw_response, do: raw_response.data, else: body

      fetch_next = fn cursor ->
        v2_search_tickets(
          client,
          SellApp.Page.next_params(params, "after", cursor),
          Keyword.delete(opts, :with_response)
        )
      end

      result =
        SellApp.Page.from_map(
          body,
          "data",
          &SellApp.V2SearchTicketsResponseValue200ApplicationJsonPropertyDataItem.from_map/1,
          fetch_next,
          base_url: client.base_url,
          path: "/v2/tickets/search",
          pagination_param: "after"
        )

      {:ok, if(raw_response, do: %{raw_response | data: result}, else: result)}
    end
  end

  @doc """
  Retrieve specific ticket

  Retrieve a support ticket by its ID. This v2 route is store-scoped. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.

  ## Parameters

    * `ticket` — The ticket path parameter.
    * `opts` — per-request options (see `SellApp.Client.request/5`)
  """
  @spec v2_get_ticket(SellApp.Client.t(), String.t(), keyword()) ::
          {:ok, SellApp.SdkV2GetTicketResponseValue200ApplicationJson.t()}
          | {:error, SellApp.Error.error()}
  def v2_get_ticket(client, ticket, opts \\ []) do
    with {:ok, body} <-
           SellApp.Client.request(
             client,
             :get,
             "/v2/tickets/#{URI.encode(ticket, &URI.char_unreserved?/1)}",
             %{},
             Keyword.put(opts, :operation_id, "v2GetTicket")
           ) do
      raw_response = if match?(%SellApp.Response{}, body), do: body, else: nil
      body = if raw_response, do: raw_response.data, else: body

      SellApp.Schema.validate_value!(
        body,
        %{kind: :model, module: SellApp.SdkV2GetTicketResponseValue200ApplicationJson},
        :response,
        "$response"
      )

      result =
        SellApp.Cast.nested(
          body,
          &SellApp.SdkV2GetTicketResponseValue200ApplicationJson.from_map/1
        )

      {:ok, if(raw_response, do: %{raw_response | data: result}, else: result)}
    end
  end

  @doc """
  Close, reopen, or archive a ticket

  Change ticket status or archive state in the selected store. Requires the ticket API-key ability and store ticket permission. Send status OPEN to reopen or CLOSED to close; closing sends the existing customer notification only when the status changes. Send archived true to archive or false to restore. You may send both fields together; omitted fields stay unchanged. Use the same optional Idempotency-Key and identical body after a lost response. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.

  ## Parameters

    * `ticket` — path parameter
    * `params` — request body map
    * `opts` — per-request options (see `SellApp.Client.request/5`)
  """
  @spec update(SellApp.Client.t(), String.t(), map(), keyword()) ::
          {:ok, SellApp.SdkUpdateTicketResponseValue200ApplicationJson.t()}
          | {:error, SellApp.Error.error()}
  def update(client, ticket, params \\ %{}, opts \\ []) do
    SellApp.Schema.validate_value!(
      params,
      %{kind: :model, module: SellApp.SdkUpdateTicketRequestApplicationJson},
      :request,
      "$request.body"
    )

    with {:ok, body} <-
           SellApp.Client.request(
             client,
             :patch,
             "/v2/tickets/#{URI.encode(ticket, &URI.char_unreserved?/1)}",
             params,
             Keyword.put(
               Keyword.put(Keyword.put(opts, :idempotency_supported, true), :request_body, true),
               :operation_id,
               "updateTicket"
             )
           ) do
      raw_response = if match?(%SellApp.Response{}, body), do: body, else: nil
      body = if raw_response, do: raw_response.data, else: body

      SellApp.Schema.validate_value!(
        body,
        %{kind: :model, module: SellApp.SdkUpdateTicketResponseValue200ApplicationJson},
        :response,
        "$response"
      )

      result =
        SellApp.Cast.nested(
          body,
          &SellApp.SdkUpdateTicketResponseValue200ApplicationJson.from_map/1
        )

      {:ok, if(raw_response, do: %{raw_response | data: result}, else: result)}
    end
  end
end
