# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.UpdateOrderStatusResponseValue200ApplicationJsonPropertyDataPropertyLineItemsItem do
  @moduledoc """
  UpdateOrderStatusResponseValue200ApplicationJsonPropertyDataPropertyLineItemsItem model.
  """

  defstruct [
    :id,
    :product_id,
    :product_variant_id,
    :product_title,
    :variant_title,
    :quantity,
    :status,
    :currency,
    :subtotal_cents,
    :total_exclusive_cents,
    :total_cents,
    :subscription_id,
    :created_at,
    __additional_properties__: %{},
    __present_fields__: []
  ]

  @type t :: %__MODULE__{
          id: integer(),
          product_id: integer() | nil,
          product_variant_id: integer() | nil,
          product_title: String.t() | nil,
          variant_title: String.t() | nil,
          quantity: integer(),
          status:
            SellApp.UpdateOrderStatusResponseValue200ApplicationJsonPropertyDataPropertyLineItemsItemStatus.t(),
          currency: String.t() | nil,
          subtotal_cents: integer() | nil,
          total_exclusive_cents: integer() | nil,
          total_cents: integer(),
          subscription_id: integer() | nil,
          created_at: String.t() | nil,
          __additional_properties__: map(),
          __present_fields__: [String.t()]
        }

  @schema %{
    name: "UpdateOrderStatusResponseValue200ApplicationJsonPropertyDataPropertyLineItemsItem",
    properties: %{
      "id" => %{required: true, schema: %{kind: :integer}},
      "product_id" => %{required: true, schema: %{kind: :nullable, inner: %{kind: :integer}}},
      "product_variant_id" => %{
        required: true,
        schema: %{kind: :nullable, inner: %{kind: :integer}}
      },
      "product_title" => %{required: true, schema: %{kind: :nullable, inner: %{kind: :string}}},
      "variant_title" => %{required: true, schema: %{kind: :nullable, inner: %{kind: :string}}},
      "quantity" => %{required: true, schema: %{kind: :integer, minimum: 1}},
      "status" => %{
        required: true,
        schema: %{
          kind: :enum,
          values: [
            "PENDING",
            "REVERSED",
            "PARTIAL",
            "VOIDED",
            "REFUNDED",
            "PAID",
            "COMPLETED",
            "DISPUTING",
            "REVIEW",
            "FAILED"
          ]
        }
      },
      "currency" => %{
        required: true,
        schema: %{kind: :nullable, inner: %{kind: :string, min_length: 3, max_length: 8}}
      },
      "subtotal_cents" => %{
        required: true,
        schema: %{kind: :nullable, inner: %{kind: :integer, minimum: 0}}
      },
      "total_exclusive_cents" => %{
        required: true,
        schema: %{kind: :nullable, inner: %{kind: :integer, minimum: 0}}
      },
      "total_cents" => %{required: true, schema: %{kind: :integer, minimum: 0}},
      "subscription_id" => %{required: true, schema: %{kind: :nullable, inner: %{kind: :integer}}},
      "created_at" => %{
        required: true,
        schema: %{kind: :nullable, inner: %{kind: :string, format: "date-time"}}
      }
    },
    additional_properties: true
  }
  @doc false
  def schema, do: @schema

  @doc false
  @spec from_map(map()) :: t()
  def from_map(map) when is_map(map) do
    SellApp.Schema.validate_model!(map, @schema, :response)

    %__MODULE__{
      id: map["id"],
      product_id: map["product_id"],
      product_variant_id: map["product_variant_id"],
      product_title: map["product_title"],
      variant_title: map["variant_title"],
      quantity: map["quantity"],
      status:
        SellApp.Cast.enum(
          map["status"],
          &SellApp.UpdateOrderStatusResponseValue200ApplicationJsonPropertyDataPropertyLineItemsItemStatus.cast/1
        ),
      currency: map["currency"],
      subtotal_cents: map["subtotal_cents"],
      total_exclusive_cents: map["total_exclusive_cents"],
      total_cents: map["total_cents"],
      subscription_id: map["subscription_id"],
      created_at: map["created_at"],
      __additional_properties__:
        Map.drop(map, [
          "id",
          "product_id",
          "product_variant_id",
          "product_title",
          "variant_title",
          "quantity",
          "status",
          "currency",
          "subtotal_cents",
          "total_exclusive_cents",
          "total_cents",
          "subscription_id",
          "created_at"
        ]),
      __present_fields__: Map.keys(map)
    }
  end

  @doc false
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    known =
      SellApp.Cast.keep_present(
        %{
          "id" => struct.id,
          "product_id" => struct.product_id,
          "product_variant_id" => struct.product_variant_id,
          "product_title" => struct.product_title,
          "variant_title" => struct.variant_title,
          "quantity" => struct.quantity,
          "status" =>
            SellApp.Cast.enum(
              struct.status,
              &SellApp.UpdateOrderStatusResponseValue200ApplicationJsonPropertyDataPropertyLineItemsItemStatus.dump/1
            ),
          "currency" => struct.currency,
          "subtotal_cents" => struct.subtotal_cents,
          "total_exclusive_cents" => struct.total_exclusive_cents,
          "total_cents" => struct.total_cents,
          "subscription_id" => struct.subscription_id,
          "created_at" => struct.created_at
        },
        [
          "id",
          "product_id",
          "product_variant_id",
          "product_title",
          "variant_title",
          "quantity",
          "status",
          "currency",
          "subtotal_cents",
          "total_exclusive_cents",
          "total_cents",
          "subscription_id",
          "created_at"
        ],
        struct.__present_fields__
      )

    Map.merge(struct.__additional_properties__, known)
  end
end
