# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.UpdateCustomerWalletStatusResponseValue200ApplicationJsonPropertyData do
  @moduledoc """
  UpdateCustomerWalletStatusResponseValue200ApplicationJsonPropertyData model.
  """

  defstruct [
    :id,
    :customer_id,
    :balance_cents,
    :status,
    :customer_email,
    :held_cents,
    :available_cents,
    :created_at,
    :updated_at,
    __additional_properties__: %{},
    __present_fields__: []
  ]

  @type t :: %__MODULE__{
          id: integer(),
          customer_id: integer(),
          balance_cents: integer(),
          status:
            SellApp.UpdateCustomerWalletStatusResponseValue200ApplicationJsonPropertyDataStatus.t(),
          customer_email: String.t() | nil,
          held_cents: integer() | nil,
          available_cents: integer() | nil,
          created_at: String.t() | nil,
          updated_at: String.t() | nil,
          __additional_properties__: map(),
          __present_fields__: [String.t()]
        }

  @schema %{
    name: "UpdateCustomerWalletStatusResponseValue200ApplicationJsonPropertyData",
    properties: %{
      "id" => %{required: true, schema: %{kind: :integer}},
      "customer_id" => %{required: true, schema: %{kind: :integer}},
      "balance_cents" => %{required: true, schema: %{kind: :integer, minimum: 0}},
      "status" => %{required: true, schema: %{kind: :enum, values: ["active", "frozen"]}},
      "customer_email" => %{required: false, schema: %{kind: :string, format: "email"}},
      "held_cents" => %{required: false, schema: %{kind: :integer, minimum: 0}},
      "available_cents" => %{required: false, schema: %{kind: :integer, minimum: 0}},
      "created_at" => %{
        required: false,
        schema: %{kind: :nullable, inner: %{kind: :string, format: "date-time"}}
      },
      "updated_at" => %{
        required: false,
        schema: %{kind: :nullable, inner: %{kind: :string, format: "date-time"}}
      }
    },
    additional_properties: true
  }
  @doc false
  def schema, do: @schema

  @doc false
  @spec from_map(map()) :: t()
  def from_map(map) when is_map(map) do
    SellApp.Schema.validate_model!(map, @schema, :response)

    %__MODULE__{
      id: map["id"],
      customer_id: map["customer_id"],
      balance_cents: map["balance_cents"],
      status:
        SellApp.Cast.enum(
          map["status"],
          &SellApp.UpdateCustomerWalletStatusResponseValue200ApplicationJsonPropertyDataStatus.cast/1
        ),
      customer_email: map["customer_email"],
      held_cents: map["held_cents"],
      available_cents: map["available_cents"],
      created_at: map["created_at"],
      updated_at: map["updated_at"],
      __additional_properties__:
        Map.drop(map, [
          "id",
          "customer_id",
          "balance_cents",
          "status",
          "customer_email",
          "held_cents",
          "available_cents",
          "created_at",
          "updated_at"
        ]),
      __present_fields__: Map.keys(map)
    }
  end

  @doc false
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    known =
      SellApp.Cast.keep_present(
        %{
          "id" => struct.id,
          "customer_id" => struct.customer_id,
          "balance_cents" => struct.balance_cents,
          "status" =>
            SellApp.Cast.enum(
              struct.status,
              &SellApp.UpdateCustomerWalletStatusResponseValue200ApplicationJsonPropertyDataStatus.dump/1
            ),
          "customer_email" => struct.customer_email,
          "held_cents" => struct.held_cents,
          "available_cents" => struct.available_cents,
          "created_at" => struct.created_at,
          "updated_at" => struct.updated_at
        },
        ["id", "customer_id", "balance_cents", "status"],
        struct.__present_fields__
      )

    Map.merge(struct.__additional_properties__, known)
  end
end
