# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.UpdateUpsellOfferResponseValue200ApplicationJsonPropertyData do
  @moduledoc """
  A store-scoped post-purchase offer. Target products and variants are always validated against the offer's store and parent product.
  """

  defstruct [
    :id,
    :name,
    :description,
    :is_active,
    :source_listing_id,
    :source_variant_id,
    :minimum_order_total_usd_cents,
    :maximum_order_total_usd_cents,
    :starts_at,
    :ends_at,
    :available_for_days,
    :max_accepts_per_customer,
    :sort_order,
    :version,
    :source_product,
    :source_variant,
    :items,
    :created_at,
    :updated_at,
    :deleted_at,
    __additional_properties__: %{},
    __present_fields__: []
  ]

  @type t :: %__MODULE__{
          id: integer(),
          name: String.t(),
          description: String.t() | nil,
          is_active: boolean(),
          source_listing_id: integer(),
          source_variant_id: integer() | nil,
          minimum_order_total_usd_cents: integer() | nil,
          maximum_order_total_usd_cents: integer() | nil,
          starts_at: String.t() | nil,
          ends_at: String.t() | nil,
          available_for_days: integer() | nil,
          max_accepts_per_customer: integer() | nil,
          sort_order: integer(),
          version: integer(),
          source_product:
            SellApp.UpdateUpsellOfferResponseValue200ApplicationJsonPropertyDataPropertySourceProduct.t()
            | nil,
          source_variant:
            SellApp.UpdateUpsellOfferResponseValue200ApplicationJsonPropertyDataPropertySourceVariant.t()
            | nil,
          items: [
            SellApp.UpdateUpsellOfferResponseValue200ApplicationJsonPropertyDataPropertyItemsItem.t()
          ],
          created_at: String.t() | nil,
          updated_at: String.t() | nil,
          deleted_at: String.t() | nil,
          __additional_properties__: map(),
          __present_fields__: [String.t()]
        }

  @schema %{
    name: "UpdateUpsellOfferResponseValue200ApplicationJsonPropertyData",
    properties: %{
      "id" => %{required: true, schema: %{kind: :integer}},
      "name" => %{required: true, schema: %{kind: :string, max_length: 120}},
      "description" => %{
        required: true,
        schema: %{kind: :nullable, inner: %{kind: :string, max_length: 255}}
      },
      "is_active" => %{required: true, schema: %{kind: :boolean}},
      "source_listing_id" => %{required: true, schema: %{kind: :integer}},
      "source_variant_id" => %{
        required: true,
        schema: %{kind: :nullable, inner: %{kind: :integer}}
      },
      "minimum_order_total_usd_cents" => %{
        required: true,
        schema: %{kind: :nullable, inner: %{kind: :integer, minimum: 1}}
      },
      "maximum_order_total_usd_cents" => %{
        required: true,
        schema: %{kind: :nullable, inner: %{kind: :integer, minimum: 1}}
      },
      "starts_at" => %{
        required: true,
        schema: %{kind: :nullable, inner: %{kind: :string, format: "date-time"}}
      },
      "ends_at" => %{
        required: true,
        schema: %{kind: :nullable, inner: %{kind: :string, format: "date-time"}}
      },
      "available_for_days" => %{
        required: true,
        schema: %{kind: :nullable, inner: %{kind: :integer, minimum: 1, maximum: 4_294_967_295}}
      },
      "max_accepts_per_customer" => %{
        required: true,
        schema: %{kind: :nullable, inner: %{kind: :integer, minimum: 1, maximum: 4_294_967_295}}
      },
      "sort_order" => %{required: true, schema: %{kind: :integer, minimum: 0}},
      "version" => %{required: true, schema: %{kind: :integer, minimum: 1}},
      "source_product" => %{
        required: true,
        schema: %{
          kind: :nullable,
          inner: %{
            kind: :model,
            module:
              SellApp.UpdateUpsellOfferResponseValue200ApplicationJsonPropertyDataPropertySourceProduct
          }
        }
      },
      "source_variant" => %{
        required: true,
        schema: %{
          kind: :nullable,
          inner: %{
            kind: :model,
            module:
              SellApp.UpdateUpsellOfferResponseValue200ApplicationJsonPropertyDataPropertySourceVariant
          }
        }
      },
      "items" => %{
        required: true,
        schema: %{
          kind: :array,
          items: %{
            kind: :model,
            module:
              SellApp.UpdateUpsellOfferResponseValue200ApplicationJsonPropertyDataPropertyItemsItem
          },
          min_items: 1
        }
      },
      "created_at" => %{
        required: true,
        schema: %{kind: :nullable, inner: %{kind: :string, format: "date-time"}}
      },
      "updated_at" => %{
        required: true,
        schema: %{kind: :nullable, inner: %{kind: :string, format: "date-time"}}
      },
      "deleted_at" => %{
        required: true,
        schema: %{kind: :nullable, inner: %{kind: :string, format: "date-time"}}
      }
    },
    additional_properties: true
  }
  @doc false
  def schema, do: @schema

  @doc false
  @spec from_map(map()) :: t()
  def from_map(map) when is_map(map) do
    SellApp.Schema.validate_model!(map, @schema, :response)

    %__MODULE__{
      id: map["id"],
      name: map["name"],
      description: map["description"],
      is_active: map["is_active"],
      source_listing_id: map["source_listing_id"],
      source_variant_id: map["source_variant_id"],
      minimum_order_total_usd_cents: map["minimum_order_total_usd_cents"],
      maximum_order_total_usd_cents: map["maximum_order_total_usd_cents"],
      starts_at: map["starts_at"],
      ends_at: map["ends_at"],
      available_for_days: map["available_for_days"],
      max_accepts_per_customer: map["max_accepts_per_customer"],
      sort_order: map["sort_order"],
      version: map["version"],
      source_product:
        SellApp.Cast.nested(
          map["source_product"],
          &SellApp.UpdateUpsellOfferResponseValue200ApplicationJsonPropertyDataPropertySourceProduct.from_map/1
        ),
      source_variant:
        SellApp.Cast.nested(
          map["source_variant"],
          &SellApp.UpdateUpsellOfferResponseValue200ApplicationJsonPropertyDataPropertySourceVariant.from_map/1
        ),
      items:
        SellApp.Cast.list(
          map["items"],
          &SellApp.UpdateUpsellOfferResponseValue200ApplicationJsonPropertyDataPropertyItemsItem.from_map/1
        ),
      created_at: map["created_at"],
      updated_at: map["updated_at"],
      deleted_at: map["deleted_at"],
      __additional_properties__:
        Map.drop(map, [
          "id",
          "name",
          "description",
          "is_active",
          "source_listing_id",
          "source_variant_id",
          "minimum_order_total_usd_cents",
          "maximum_order_total_usd_cents",
          "starts_at",
          "ends_at",
          "available_for_days",
          "max_accepts_per_customer",
          "sort_order",
          "version",
          "source_product",
          "source_variant",
          "items",
          "created_at",
          "updated_at",
          "deleted_at"
        ]),
      __present_fields__: Map.keys(map)
    }
  end

  @doc false
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    known =
      SellApp.Cast.keep_present(
        %{
          "id" => struct.id,
          "name" => struct.name,
          "description" => struct.description,
          "is_active" => struct.is_active,
          "source_listing_id" => struct.source_listing_id,
          "source_variant_id" => struct.source_variant_id,
          "minimum_order_total_usd_cents" => struct.minimum_order_total_usd_cents,
          "maximum_order_total_usd_cents" => struct.maximum_order_total_usd_cents,
          "starts_at" => struct.starts_at,
          "ends_at" => struct.ends_at,
          "available_for_days" => struct.available_for_days,
          "max_accepts_per_customer" => struct.max_accepts_per_customer,
          "sort_order" => struct.sort_order,
          "version" => struct.version,
          "source_product" =>
            SellApp.Cast.dump_struct(
              struct.source_product,
              &SellApp.UpdateUpsellOfferResponseValue200ApplicationJsonPropertyDataPropertySourceProduct.to_map/1
            ),
          "source_variant" =>
            SellApp.Cast.dump_struct(
              struct.source_variant,
              &SellApp.UpdateUpsellOfferResponseValue200ApplicationJsonPropertyDataPropertySourceVariant.to_map/1
            ),
          "items" =>
            SellApp.Cast.list(struct.items, fn item ->
              SellApp.Cast.dump_struct(
                item,
                &SellApp.UpdateUpsellOfferResponseValue200ApplicationJsonPropertyDataPropertyItemsItem.to_map/1
              )
            end),
          "created_at" => struct.created_at,
          "updated_at" => struct.updated_at,
          "deleted_at" => struct.deleted_at
        },
        [
          "id",
          "name",
          "description",
          "is_active",
          "source_listing_id",
          "source_variant_id",
          "minimum_order_total_usd_cents",
          "maximum_order_total_usd_cents",
          "starts_at",
          "ends_at",
          "available_for_days",
          "max_accepts_per_customer",
          "sort_order",
          "version",
          "source_product",
          "source_variant",
          "items",
          "created_at",
          "updated_at",
          "deleted_at"
        ],
        struct.__present_fields__
      )

    Map.merge(struct.__additional_properties__, known)
  end
end
