# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.UpdateUpsellOfferRequestApplicationJsonPropertyItemsItem do
  @moduledoc """
  UpdateUpsellOfferRequestApplicationJsonPropertyItemsItem model.
  """

  defstruct [
    :target_listing_id,
    :target_variant_id,
    :id,
    :headline,
    :description,
    :discount_type,
    :discount_value,
    :maximum_discount_amount,
    __additional_properties__: %{},
    __present_fields__: []
  ]

  @type t :: %__MODULE__{
          target_listing_id: integer(),
          target_variant_id: integer(),
          id: integer() | nil,
          headline: String.t() | nil,
          description: String.t() | nil,
          discount_type: SellApp.DiscountType.t() | nil,
          discount_value: number() | String.t() | nil,
          maximum_discount_amount: number() | String.t() | nil,
          __additional_properties__: map(),
          __present_fields__: [String.t()]
        }

  @schema %{
    name: "UpdateUpsellOfferRequestApplicationJsonPropertyItemsItem",
    properties: %{
      "target_listing_id" => %{required: true, schema: %{kind: :integer}},
      "target_variant_id" => %{required: true, schema: %{kind: :integer}},
      "id" => %{required: false, schema: %{kind: :nullable, inner: %{kind: :integer}}},
      "headline" => %{
        required: false,
        schema: %{kind: :nullable, inner: %{kind: :string, max_length: 120}}
      },
      "description" => %{
        required: false,
        schema: %{kind: :nullable, inner: %{kind: :string, max_length: 255}}
      },
      "discount_type" => %{
        required: false,
        schema: %{kind: :nullable, inner: %{kind: :enum, values: ["percentage", "fixed", "null"]}}
      },
      "discount_value" => %{
        required: false,
        schema: %{
          kind: :nullable,
          inner: %{
            kind: :union,
            variants: [
              %{kind: :number, maximum: 99_999_999.99, exclusive_minimum: 0, multiple_of: 0.01},
              %{kind: :string, maximum: 99_999_999.99, exclusive_minimum: 0, multiple_of: 0.01}
            ]
          }
        }
      },
      "maximum_discount_amount" => %{
        required: false,
        schema: %{
          kind: :nullable,
          inner: %{
            kind: :union,
            variants: [
              %{kind: :number, maximum: 99_999_999.99, exclusive_minimum: 0, multiple_of: 0.01},
              %{kind: :string, maximum: 99_999_999.99, exclusive_minimum: 0, multiple_of: 0.01}
            ]
          }
        }
      }
    },
    additional_properties: true
  }
  @doc false
  def schema, do: @schema

  @doc false
  @spec from_map(map()) :: t()
  def from_map(map) when is_map(map) do
    SellApp.Schema.validate_model!(map, @schema, :response)

    %__MODULE__{
      target_listing_id: map["target_listing_id"],
      target_variant_id: map["target_variant_id"],
      id: map["id"],
      headline: map["headline"],
      description: map["description"],
      discount_type: SellApp.Cast.enum(map["discount_type"], &SellApp.DiscountType.cast/1),
      discount_value: map["discount_value"],
      maximum_discount_amount: map["maximum_discount_amount"],
      __additional_properties__:
        Map.drop(map, [
          "target_listing_id",
          "target_variant_id",
          "id",
          "headline",
          "description",
          "discount_type",
          "discount_value",
          "maximum_discount_amount"
        ]),
      __present_fields__: Map.keys(map)
    }
  end

  @doc false
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    known =
      SellApp.Cast.keep_present(
        %{
          "target_listing_id" => struct.target_listing_id,
          "target_variant_id" => struct.target_variant_id,
          "id" => struct.id,
          "headline" => struct.headline,
          "description" => struct.description,
          "discount_type" =>
            SellApp.Cast.enum(struct.discount_type, &SellApp.DiscountType.dump/1),
          "discount_value" => SellApp.Cast.dump_union(struct.discount_value),
          "maximum_discount_amount" => SellApp.Cast.dump_union(struct.maximum_discount_amount)
        },
        ["target_listing_id", "target_variant_id"],
        struct.__present_fields__
      )

    Map.merge(struct.__additional_properties__, known)
  end
end
