# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.UpdateCourseLessonResponseValue200ApplicationJsonPropertyDataType do
  @moduledoc """
  UpdateCourseLessonResponseValue200ApplicationJsonPropertyDataType enum.
  """

  @type t :: :lecture | :video | :text | :quiz | :assignment

  @doc "All known values."
  @spec values() :: [t()]
  def values, do: [:lecture, :video, :text, :quiz, :assignment]

  @doc "Casts a wire string to its atom; unknown values pass through unchanged."
  @spec cast(String.t() | nil) :: t() | String.t() | nil
  def cast("lecture"), do: :lecture
  def cast("video"), do: :video
  def cast("text"), do: :text
  def cast("quiz"), do: :quiz
  def cast("assignment"), do: :assignment
  def cast(other), do: other

  @doc "Dumps an atom back to its wire string."
  @spec dump(t() | String.t()) :: String.t()
  def dump(:lecture), do: "lecture"
  def dump(:video), do: "video"
  def dump(:text), do: "text"
  def dump(:quiz), do: "quiz"
  def dump(:assignment), do: "assignment"
  def dump(other) when is_binary(other), do: other
end
