# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.UpdateAppointmentResponseValue200ApplicationJsonPropertyData do
  @moduledoc """
  UpdateAppointmentResponseValue200ApplicationJsonPropertyData model.
  """

  defstruct [
    :id,
    :product_id,
    :product_variant_id,
    :order_id,
    :invoice_id,
    :customer_id,
    :customer_email,
    :slot_start_at,
    :slot_end_at,
    :timezone,
    :quantity,
    :status,
    :calendar_sync_status,
    :external_event_link,
    :video_join_url,
    :confirmed_at,
    :cancelled_at,
    :created_at,
    :updated_at,
    :product,
    :variant,
    __additional_properties__: %{},
    __present_fields__: []
  ]

  @type t :: %__MODULE__{
          id: String.t(),
          product_id: integer(),
          product_variant_id: integer(),
          order_id: integer(),
          invoice_id: integer(),
          customer_id: integer() | nil,
          customer_email: String.t() | nil,
          slot_start_at: String.t(),
          slot_end_at: String.t(),
          timezone: String.t(),
          quantity: integer(),
          status: SellApp.UpdateAppointmentResponseValue200ApplicationJsonPropertyDataStatus.t(),
          calendar_sync_status:
            SellApp.UpdateAppointmentResponseValue200ApplicationJsonPropertyDataCalendarSyncStatus.t(),
          external_event_link: String.t() | nil,
          video_join_url: String.t() | nil,
          confirmed_at: String.t() | nil,
          cancelled_at: String.t() | nil,
          created_at: String.t(),
          updated_at: String.t(),
          product:
            SellApp.UpdateAppointmentResponseValue200ApplicationJsonPropertyDataPropertyProduct.t()
            | nil,
          variant:
            SellApp.UpdateAppointmentResponseValue200ApplicationJsonPropertyDataPropertyVariant.t()
            | nil,
          __additional_properties__: map(),
          __present_fields__: [String.t()]
        }

  @schema %{
    name: "UpdateAppointmentResponseValue200ApplicationJsonPropertyData",
    properties: %{
      "id" => %{required: true, schema: %{kind: :string, format: "uuid"}},
      "product_id" => %{required: true, schema: %{kind: :integer}},
      "product_variant_id" => %{required: true, schema: %{kind: :integer}},
      "order_id" => %{required: true, schema: %{kind: :integer}},
      "invoice_id" => %{required: true, schema: %{kind: :integer}},
      "customer_id" => %{required: true, schema: %{kind: :nullable, inner: %{kind: :integer}}},
      "customer_email" => %{
        required: true,
        schema: %{kind: :nullable, inner: %{kind: :string, format: "email"}}
      },
      "slot_start_at" => %{required: true, schema: %{kind: :string, format: "date-time"}},
      "slot_end_at" => %{required: true, schema: %{kind: :string, format: "date-time"}},
      "timezone" => %{required: true, schema: %{kind: :string}},
      "quantity" => %{required: true, schema: %{kind: :integer, minimum: 1}},
      "status" => %{
        required: true,
        schema: %{
          kind: :enum,
          values: ["pending", "confirmed", "cancelled", "needs_reschedule", "failed"]
        }
      },
      "calendar_sync_status" => %{
        required: true,
        schema: %{kind: :enum, values: ["pending", "synced", "skipped", "cancelled", "failed"]}
      },
      "external_event_link" => %{
        required: true,
        schema: %{kind: :nullable, inner: %{kind: :string, format: "uri"}}
      },
      "video_join_url" => %{
        required: true,
        schema: %{kind: :nullable, inner: %{kind: :string, format: "uri"}}
      },
      "confirmed_at" => %{
        required: true,
        schema: %{kind: :nullable, inner: %{kind: :string, format: "date-time"}}
      },
      "cancelled_at" => %{
        required: true,
        schema: %{kind: :nullable, inner: %{kind: :string, format: "date-time"}}
      },
      "created_at" => %{required: true, schema: %{kind: :string, format: "date-time"}},
      "updated_at" => %{required: true, schema: %{kind: :string, format: "date-time"}},
      "product" => %{
        required: true,
        schema: %{
          kind: :nullable,
          inner: %{
            kind: :model,
            module:
              SellApp.UpdateAppointmentResponseValue200ApplicationJsonPropertyDataPropertyProduct
          }
        }
      },
      "variant" => %{
        required: true,
        schema: %{
          kind: :nullable,
          inner: %{
            kind: :model,
            module:
              SellApp.UpdateAppointmentResponseValue200ApplicationJsonPropertyDataPropertyVariant
          }
        }
      }
    },
    additional_properties: true
  }
  @doc false
  def schema, do: @schema

  @doc false
  @spec from_map(map()) :: t()
  def from_map(map) when is_map(map) do
    SellApp.Schema.validate_model!(map, @schema, :response)

    %__MODULE__{
      id: map["id"],
      product_id: map["product_id"],
      product_variant_id: map["product_variant_id"],
      order_id: map["order_id"],
      invoice_id: map["invoice_id"],
      customer_id: map["customer_id"],
      customer_email: map["customer_email"],
      slot_start_at: map["slot_start_at"],
      slot_end_at: map["slot_end_at"],
      timezone: map["timezone"],
      quantity: map["quantity"],
      status:
        SellApp.Cast.enum(
          map["status"],
          &SellApp.UpdateAppointmentResponseValue200ApplicationJsonPropertyDataStatus.cast/1
        ),
      calendar_sync_status:
        SellApp.Cast.enum(
          map["calendar_sync_status"],
          &SellApp.UpdateAppointmentResponseValue200ApplicationJsonPropertyDataCalendarSyncStatus.cast/1
        ),
      external_event_link: map["external_event_link"],
      video_join_url: map["video_join_url"],
      confirmed_at: map["confirmed_at"],
      cancelled_at: map["cancelled_at"],
      created_at: map["created_at"],
      updated_at: map["updated_at"],
      product:
        SellApp.Cast.nested(
          map["product"],
          &SellApp.UpdateAppointmentResponseValue200ApplicationJsonPropertyDataPropertyProduct.from_map/1
        ),
      variant:
        SellApp.Cast.nested(
          map["variant"],
          &SellApp.UpdateAppointmentResponseValue200ApplicationJsonPropertyDataPropertyVariant.from_map/1
        ),
      __additional_properties__:
        Map.drop(map, [
          "id",
          "product_id",
          "product_variant_id",
          "order_id",
          "invoice_id",
          "customer_id",
          "customer_email",
          "slot_start_at",
          "slot_end_at",
          "timezone",
          "quantity",
          "status",
          "calendar_sync_status",
          "external_event_link",
          "video_join_url",
          "confirmed_at",
          "cancelled_at",
          "created_at",
          "updated_at",
          "product",
          "variant"
        ]),
      __present_fields__: Map.keys(map)
    }
  end

  @doc false
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    known =
      SellApp.Cast.keep_present(
        %{
          "id" => struct.id,
          "product_id" => struct.product_id,
          "product_variant_id" => struct.product_variant_id,
          "order_id" => struct.order_id,
          "invoice_id" => struct.invoice_id,
          "customer_id" => struct.customer_id,
          "customer_email" => struct.customer_email,
          "slot_start_at" => struct.slot_start_at,
          "slot_end_at" => struct.slot_end_at,
          "timezone" => struct.timezone,
          "quantity" => struct.quantity,
          "status" =>
            SellApp.Cast.enum(
              struct.status,
              &SellApp.UpdateAppointmentResponseValue200ApplicationJsonPropertyDataStatus.dump/1
            ),
          "calendar_sync_status" =>
            SellApp.Cast.enum(
              struct.calendar_sync_status,
              &SellApp.UpdateAppointmentResponseValue200ApplicationJsonPropertyDataCalendarSyncStatus.dump/1
            ),
          "external_event_link" => struct.external_event_link,
          "video_join_url" => struct.video_join_url,
          "confirmed_at" => struct.confirmed_at,
          "cancelled_at" => struct.cancelled_at,
          "created_at" => struct.created_at,
          "updated_at" => struct.updated_at,
          "product" =>
            SellApp.Cast.dump_struct(
              struct.product,
              &SellApp.UpdateAppointmentResponseValue200ApplicationJsonPropertyDataPropertyProduct.to_map/1
            ),
          "variant" =>
            SellApp.Cast.dump_struct(
              struct.variant,
              &SellApp.UpdateAppointmentResponseValue200ApplicationJsonPropertyDataPropertyVariant.to_map/1
            )
        },
        [
          "id",
          "product_id",
          "product_variant_id",
          "order_id",
          "invoice_id",
          "customer_id",
          "customer_email",
          "slot_start_at",
          "slot_end_at",
          "timezone",
          "quantity",
          "status",
          "calendar_sync_status",
          "external_event_link",
          "video_join_url",
          "confirmed_at",
          "cancelled_at",
          "created_at",
          "updated_at",
          "product",
          "variant"
        ],
        struct.__present_fields__
      )

    Map.merge(struct.__additional_properties__, known)
  end
end
