# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.UpdateVariantDeliverableFolderResponseValue200ApplicationJsonPropertyData do
  @moduledoc """
  UpdateVariantDeliverableFolderResponseValue200ApplicationJsonPropertyData model.
  """

  defstruct [
    :id,
    :name,
    :variant_id,
    :sort_order,
    :description,
    :parent_id,
    :created_at,
    :updated_at,
    __additional_properties__: %{},
    __present_fields__: []
  ]

  @type t :: %__MODULE__{
          id: integer(),
          name: String.t(),
          variant_id: integer(),
          sort_order: integer(),
          description: String.t() | nil,
          parent_id: integer() | nil,
          created_at: String.t() | nil,
          updated_at: String.t() | nil,
          __additional_properties__: map(),
          __present_fields__: [String.t()]
        }

  @schema %{
    name: "UpdateVariantDeliverableFolderResponseValue200ApplicationJsonPropertyData",
    properties: %{
      "id" => %{required: true, schema: %{kind: :integer}},
      "name" => %{required: true, schema: %{kind: :string, max_length: 255}},
      "variant_id" => %{required: true, schema: %{kind: :integer}},
      "sort_order" => %{required: true, schema: %{kind: :integer, minimum: 0}},
      "description" => %{
        required: false,
        schema: %{kind: :nullable, inner: %{kind: :string, max_length: 255}}
      },
      "parent_id" => %{required: false, schema: %{kind: :nullable, inner: %{kind: :integer}}},
      "created_at" => %{required: false, schema: %{kind: :string, format: "date-time"}},
      "updated_at" => %{required: false, schema: %{kind: :string, format: "date-time"}}
    },
    additional_properties: true
  }
  @doc false
  def schema, do: @schema

  @doc false
  @spec from_map(map()) :: t()
  def from_map(map) when is_map(map) do
    SellApp.Schema.validate_model!(map, @schema, :response)

    %__MODULE__{
      id: map["id"],
      name: map["name"],
      variant_id: map["variant_id"],
      sort_order: map["sort_order"],
      description: map["description"],
      parent_id: map["parent_id"],
      created_at: map["created_at"],
      updated_at: map["updated_at"],
      __additional_properties__:
        Map.drop(map, [
          "id",
          "name",
          "variant_id",
          "sort_order",
          "description",
          "parent_id",
          "created_at",
          "updated_at"
        ]),
      __present_fields__: Map.keys(map)
    }
  end

  @doc false
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    known =
      SellApp.Cast.keep_present(
        %{
          "id" => struct.id,
          "name" => struct.name,
          "variant_id" => struct.variant_id,
          "sort_order" => struct.sort_order,
          "description" => struct.description,
          "parent_id" => struct.parent_id,
          "created_at" => struct.created_at,
          "updated_at" => struct.updated_at
        },
        ["id", "name", "variant_id", "sort_order"],
        struct.__present_fields__
      )

    Map.merge(struct.__additional_properties__, known)
  end
end
