# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.V2SearchSectionsRequestApplicationJsonPropertyFiltersItem do
  @moduledoc """
  V2SearchSectionsRequestApplicationJsonPropertyFiltersItem model.
  """

  defstruct [
    :field,
    :operator,
    :value,
    :type,
    :nested,
    __additional_properties__: %{},
    __present_fields__: []
  ]

  @type t :: %__MODULE__{
          field: String.t() | nil,
          operator: String.t() | nil,
          value: term(),
          type: SellApp.V2SearchSectionsRequestApplicationJsonPropertyFiltersItemType.t() | nil,
          nested:
            [
              SellApp.V2SearchSectionsRequestApplicationJsonPropertyFiltersItemPropertyNestedItem.t()
            ]
            | nil,
          __additional_properties__: map(),
          __present_fields__: [String.t()]
        }

  @schema %{
    name: "V2SearchSectionsRequestApplicationJsonPropertyFiltersItem",
    properties: %{
      "field" => %{required: false, schema: %{kind: :string}},
      "operator" => %{required: false, schema: %{kind: :string}},
      "value" => %{required: false, schema: %{kind: :any}},
      "type" => %{required: false, schema: %{kind: :enum, values: ["and", "or"]}},
      "nested" => %{
        required: false,
        schema: %{
          kind: :array,
          items: %{
            kind: :model,
            module:
              SellApp.V2SearchSectionsRequestApplicationJsonPropertyFiltersItemPropertyNestedItem
          }
        }
      }
    },
    additional_properties: true
  }
  @doc false
  def schema, do: @schema

  @doc false
  @spec from_map(map()) :: t()
  def from_map(map) when is_map(map) do
    SellApp.Schema.validate_model!(map, @schema, :response)

    %__MODULE__{
      field: map["field"],
      operator: map["operator"],
      value: map["value"],
      type:
        SellApp.Cast.enum(
          map["type"],
          &SellApp.V2SearchSectionsRequestApplicationJsonPropertyFiltersItemType.cast/1
        ),
      nested:
        SellApp.Cast.list(
          map["nested"],
          &SellApp.V2SearchSectionsRequestApplicationJsonPropertyFiltersItemPropertyNestedItem.from_map/1
        ),
      __additional_properties__: Map.drop(map, ["field", "operator", "value", "type", "nested"]),
      __present_fields__: Map.keys(map)
    }
  end

  @doc false
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    known =
      SellApp.Cast.keep_present(
        %{
          "field" => struct.field,
          "operator" => struct.operator,
          "value" => struct.value,
          "type" =>
            SellApp.Cast.enum(
              struct.type,
              &SellApp.V2SearchSectionsRequestApplicationJsonPropertyFiltersItemType.dump/1
            ),
          "nested" =>
            SellApp.Cast.list(struct.nested, fn item ->
              SellApp.Cast.dump_struct(
                item,
                &SellApp.V2SearchSectionsRequestApplicationJsonPropertyFiltersItemPropertyNestedItem.to_map/1
              )
            end)
        },
        [],
        struct.__present_fields__
      )

    Map.merge(struct.__additional_properties__, known)
  end
end
