# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.ValidateAndSavePaymentMethodConfigurationRequestApplicationJsonOneOfValue4 do
  @moduledoc """
  ValidateAndSavePaymentMethodConfigurationRequestApplicationJsonOneOfValue4 model.
  """

  defstruct [
    :api_key,
    __additional_properties__: %{},
    __present_fields__: []
  ]

  @type t :: %__MODULE__{
          api_key: String.t(),
          __additional_properties__: map(),
          __present_fields__: [String.t()]
        }

  @schema %{
    name: "ValidateAndSavePaymentMethodConfigurationRequestApplicationJsonOneOfValue4",
    properties: %{"api_key" => %{required: true, schema: %{kind: :string}}},
    additional_properties: true
  }
  @doc false
  def schema, do: @schema

  @doc false
  @spec from_map(map()) :: t()
  def from_map(map) when is_map(map) do
    SellApp.Schema.validate_model!(map, @schema, :response)

    %__MODULE__{
      api_key: map["api_key"],
      __additional_properties__: Map.drop(map, ["api_key"]),
      __present_fields__: Map.keys(map)
    }
  end

  @doc false
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    known =
      SellApp.Cast.keep_present(
        %{
          "api_key" => struct.api_key
        },
        ["api_key"],
        struct.__present_fields__
      )

    Map.merge(struct.__additional_properties__, known)
  end
end
