# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.ValidateAndSavePaymentMethodConfigurationRequestApplicationJsonOneOfValue2 do
  @moduledoc """
  ValidateAndSavePaymentMethodConfigurationRequestApplicationJsonOneOfValue2 model.
  """

  defstruct [
    :public_key,
    :access_token,
    :webhook_secret,
    __additional_properties__: %{},
    __present_fields__: []
  ]

  @type t :: %__MODULE__{
          public_key: String.t(),
          access_token: String.t(),
          webhook_secret: String.t(),
          __additional_properties__: map(),
          __present_fields__: [String.t()]
        }

  @schema %{
    name: "ValidateAndSavePaymentMethodConfigurationRequestApplicationJsonOneOfValue2",
    properties: %{
      "public_key" => %{required: true, schema: %{kind: :string}},
      "access_token" => %{required: true, schema: %{kind: :string}},
      "webhook_secret" => %{required: true, schema: %{kind: :string}}
    },
    additional_properties: true
  }
  @doc false
  def schema, do: @schema

  @doc false
  @spec from_map(map()) :: t()
  def from_map(map) when is_map(map) do
    SellApp.Schema.validate_model!(map, @schema, :response)

    %__MODULE__{
      public_key: map["public_key"],
      access_token: map["access_token"],
      webhook_secret: map["webhook_secret"],
      __additional_properties__: Map.drop(map, ["public_key", "access_token", "webhook_secret"]),
      __present_fields__: Map.keys(map)
    }
  end

  @doc false
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = struct) do
    known =
      SellApp.Cast.keep_present(
        %{
          "public_key" => struct.public_key,
          "access_token" => struct.access_token,
          "webhook_secret" => struct.webhook_secret
        },
        ["public_key", "access_token", "webhook_secret"],
        struct.__present_fields__
      )

    Map.merge(struct.__additional_properties__, known)
  end
end
