# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.WalletSettings do
  @moduledoc """
  Operations for the WalletSettings API.
  """

  @doc """
  Retrieve wallet settings

  Retrieve wallet settings for the authenticated store. Requires the `wallet` or `wallet:write` API ability. Payment methods are returned as their effective configurable values when no explicit restriction is stored. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.

  ## Parameters

    * `opts` — per-request options (see `SellApp.Client.request/5`)
  """
  @spec get(SellApp.Client.t(), keyword()) ::
          {:ok, SellApp.SdkGetWalletSettingsResponseValue200ApplicationJson.t()}
          | {:error, SellApp.Error.error()}
  def get(client, opts \\ []) do
    with {:ok, body} <-
           SellApp.Client.request(
             client,
             :get,
             "/v2/wallet/settings",
             %{},
             Keyword.put(opts, :operation_id, "getWalletSettings")
           ) do
      raw_response = if match?(%SellApp.Response{}, body), do: body, else: nil
      body = if raw_response, do: raw_response.data, else: body

      SellApp.Schema.validate_value!(
        body,
        %{kind: :model, module: SellApp.SdkGetWalletSettingsResponseValue200ApplicationJson},
        :response,
        "$response"
      )

      result =
        SellApp.Cast.nested(
          body,
          &SellApp.SdkGetWalletSettingsResponseValue200ApplicationJson.from_map/1
        )

      {:ok, if(raw_response, do: %{raw_response | data: result}, else: result)}
    end
  end

  @doc """
  Update wallet settings

  Update wallet settings. Requires the `wallet:write` API ability and the store wallet permission. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.

  ## Parameters

    * `params` — request body map
    * `opts` — per-request options (see `SellApp.Client.request/5`)
  """
  @spec replace(SellApp.Client.t(), map(), keyword()) ::
          {:ok, SellApp.SdkReplaceWalletSettingsResponseValue200ApplicationJson.t()}
          | {:error, SellApp.Error.error()}
  def replace(client, params \\ %{}, opts \\ []) do
    SellApp.Schema.validate_value!(
      params,
      %{kind: :model, module: SellApp.SdkReplaceWalletSettingsRequestApplicationJson},
      :request,
      "$request.body"
    )

    with {:ok, body} <-
           SellApp.Client.request(
             client,
             :put,
             "/v2/wallet/settings",
             params,
             Keyword.put(
               Keyword.put(opts, :request_body, true),
               :operation_id,
               "replaceWalletSettings"
             )
           ) do
      raw_response = if match?(%SellApp.Response{}, body), do: body, else: nil
      body = if raw_response, do: raw_response.data, else: body

      SellApp.Schema.validate_value!(
        body,
        %{kind: :model, module: SellApp.SdkReplaceWalletSettingsResponseValue200ApplicationJson},
        :response,
        "$response"
      )

      result =
        SellApp.Cast.nested(
          body,
          &SellApp.SdkReplaceWalletSettingsResponseValue200ApplicationJson.from_map/1
        )

      {:ok, if(raw_response, do: %{raw_response | data: result}, else: result)}
    end
  end
end
