# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.WebhookPlatform do
  @moduledoc """
  Operations for the WebhookPlatform API.
  """

  @doc """
  List webhook event types

  List versioned outbound event types. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.

  ## Parameters

    * `opts` — per-request options (see `SellApp.Client.request/5`)
  """
  @spec list_webhook_event_types(SellApp.Client.t(), keyword()) ::
          {:ok, SellApp.SdkListWebhookEventTypesResponseValue200ApplicationJson.t()}
          | {:error, SellApp.Error.error()}
  def list_webhook_event_types(client, opts \\ []) do
    with {:ok, body} <-
           SellApp.Client.request(
             client,
             :get,
             "/v2/webhook-event-types",
             %{},
             Keyword.put(opts, :operation_id, "listWebhookEventTypes")
           ) do
      raw_response = if match?(%SellApp.Response{}, body), do: body, else: nil
      body = if raw_response, do: raw_response.data, else: body

      SellApp.Schema.validate_value!(
        body,
        %{kind: :model, module: SellApp.SdkListWebhookEventTypesResponseValue200ApplicationJson},
        :response,
        "$response"
      )

      result =
        SellApp.Cast.nested(
          body,
          &SellApp.SdkListWebhookEventTypesResponseValue200ApplicationJson.from_map/1
        )

      {:ok, if(raw_response, do: %{raw_response | data: result}, else: result)}
    end
  end

  @doc """
  List webhook deliveries

  Destination origin only; response bodies are redacted and capped. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.

  ## Parameters

    * `params` — query parameters
    * `opts` — per-request options (see `SellApp.Client.request/5`)
  """
  @spec list_webhook_deliveries(SellApp.Client.t(), map(), keyword()) ::
          {:ok,
           SellApp.Page.t(
             SellApp.ListWebhookDeliveriesResponseValue200ApplicationJsonPropertyDataItem.t()
           )}
          | {:error, SellApp.Error.error()}
  def list_webhook_deliveries(client, params \\ %{}, opts \\ []) do
    with {:ok, body} <-
           SellApp.Client.request(
             client,
             :get,
             "/v2/webhook-deliveries",
             params,
             Keyword.put(opts, :operation_id, "listWebhookDeliveries")
           ) do
      raw_response = if match?(%SellApp.Response{}, body), do: body, else: nil
      body = if raw_response, do: raw_response.data, else: body

      fetch_next = fn cursor ->
        list_webhook_deliveries(
          client,
          SellApp.Page.next_params(params, "after", cursor),
          Keyword.delete(opts, :with_response)
        )
      end

      result =
        SellApp.Page.from_map(
          body,
          "data",
          &SellApp.ListWebhookDeliveriesResponseValue200ApplicationJsonPropertyDataItem.from_map/1,
          fetch_next,
          base_url: client.base_url,
          path: "/v2/webhook-deliveries",
          pagination_param: "after"
        )

      {:ok, if(raw_response, do: %{raw_response | data: result}, else: result)}
    end
  end

  @doc """
  Retrieve a webhook delivery

  Retrieve one redacted delivery. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.

  ## Parameters

    * `delivery` — The delivery identifier.
    * `opts` — per-request options (see `SellApp.Client.request/5`)
  """
  @spec get_webhook_delivery(SellApp.Client.t(), String.t(), keyword()) ::
          {:ok, SellApp.SdkGetWebhookDeliveryResponseValue200ApplicationJson.t()}
          | {:error, SellApp.Error.error()}
  def get_webhook_delivery(client, delivery, opts \\ []) do
    with {:ok, body} <-
           SellApp.Client.request(
             client,
             :get,
             "/v2/webhook-deliveries/#{URI.encode(delivery, &URI.char_unreserved?/1)}",
             %{},
             Keyword.put(opts, :operation_id, "getWebhookDelivery")
           ) do
      raw_response = if match?(%SellApp.Response{}, body), do: body, else: nil
      body = if raw_response, do: raw_response.data, else: body

      SellApp.Schema.validate_value!(
        body,
        %{kind: :model, module: SellApp.SdkGetWebhookDeliveryResponseValue200ApplicationJson},
        :response,
        "$response"
      )

      result =
        SellApp.Cast.nested(
          body,
          &SellApp.SdkGetWebhookDeliveryResponseValue200ApplicationJson.from_map/1
        )

      {:ok, if(raw_response, do: %{raw_response | data: result}, else: result)}
    end
  end

  @doc """
  Replay a webhook delivery

  Accept no URL, payload, or query overrides. Resolve the current channel server-side, create a new delivery ID, retain the integration-event ID, and sign with a new timestamp. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.

  ## Parameters

    * `delivery` — The delivery identifier.
    * `params` — request body map
    * `opts` — per-request options (see `SellApp.Client.request/5`)
  """
  @spec replay_webhook_delivery(SellApp.Client.t(), String.t(), map(), keyword()) ::
          {:ok, SellApp.SdkReplayWebhookDeliveryResponseValue201ApplicationJson.t()}
          | {:error, SellApp.Error.error()}
  def replay_webhook_delivery(client, delivery, params \\ %{}, opts \\ []) do
    SellApp.Schema.validate_value!(
      params,
      %{kind: :model, module: SellApp.SdkReplayWebhookDeliveryRequestApplicationJson},
      :request,
      "$request.body"
    )

    with {:ok, body} <-
           SellApp.Client.request(
             client,
             :post,
             "/v2/webhook-deliveries/#{URI.encode(delivery, &URI.char_unreserved?/1)}/replay",
             params,
             Keyword.put(
               Keyword.put(Keyword.put(opts, :idempotency_supported, true), :request_body, true),
               :operation_id,
               "replayWebhookDelivery"
             )
           ) do
      raw_response = if match?(%SellApp.Response{}, body), do: body, else: nil
      body = if raw_response, do: raw_response.data, else: body

      SellApp.Schema.validate_value!(
        body,
        %{kind: :model, module: SellApp.SdkReplayWebhookDeliveryResponseValue201ApplicationJson},
        :response,
        "$response"
      )

      result =
        SellApp.Cast.nested(
          body,
          &SellApp.SdkReplayWebhookDeliveryResponseValue201ApplicationJson.from_map/1
        )

      {:ok, if(raw_response, do: %{raw_response | data: result}, else: result)}
    end
  end
end
