# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.AccountTest do
  use ExUnit.Case, async: true

  setup do
    client =
      SellApp.Client.new(
        api_key: "sk_test_key",
        access_token: "oauth_test",
        customer_session: "customer_test",
        browser_session: "sell_session=test",
        store: "test-store",
        req_options: [plug: {Req.Test, SellApp.Client}]
      )

    {:ok, client: client}
  end

  test "get_account succeeds", %{client: client} do
    Req.Test.stub(SellApp.Client, fn conn ->
      assert conn.method == "GET"
      assert String.ends_with?(conn.request_path, "/v2/me")
      Req.Test.json(conn, SellApp.TestFixtures.fixture("account/get_account"))
    end)

    assert {:ok, %SellApp.SdkGetAccountResponseValue200ApplicationJson{}} =
             SellApp.Account.get_account(client)
  end

  test "list_stores succeeds", %{client: client} do
    Req.Test.stub(SellApp.Client, fn conn ->
      assert conn.method == "GET"
      assert String.ends_with?(conn.request_path, "/v2/stores")
      Req.Test.json(conn, SellApp.TestFixtures.fixture("account/list_stores"))
    end)

    assert {:ok, %SellApp.SdkListStoresResponseValue200ApplicationJson{}} =
             SellApp.Account.list_stores(client)
  end

  test "create_store succeeds", %{client: client} do
    Req.Test.stub(SellApp.Client, fn conn ->
      assert conn.method == "POST"
      assert String.ends_with?(conn.request_path, "/v2/stores")
      Req.Test.json(conn, SellApp.TestFixtures.fixture("account/create_store"))
    end)

    assert {:ok, %SellApp.SdkCreateStoreResponseValue201ApplicationJson{}} =
             SellApp.Account.create_store(client, %{
               "name" => "name",
               "slug" => "slug",
               "visibility" => "PUBLIC"
             })
  end

  test "get_store succeeds", %{client: client} do
    Req.Test.stub(SellApp.Client, fn conn ->
      assert conn.method == "GET"
      assert String.ends_with?(conn.request_path, "/v2/stores/test_store")
      Req.Test.json(conn, SellApp.TestFixtures.fixture("account/get_store"))
    end)

    assert {:ok, %SellApp.SdkGetStoreResponseValue200ApplicationJson{}} =
             SellApp.Account.get_store(client, "test_store")
  end

  test "get_store_permissions succeeds", %{client: client} do
    Req.Test.stub(SellApp.Client, fn conn ->
      assert conn.method == "GET"
      assert String.ends_with?(conn.request_path, "/v2/permissions")
      Req.Test.json(conn, SellApp.TestFixtures.fixture("account/get_store_permissions"))
    end)

    assert {:ok, %SellApp.SdkGetStorePermissionsResponseValue200ApplicationJson{}} =
             SellApp.Account.get_store_permissions(client)
  end

  test "get_account honors per-request options", %{client: client} do
    Req.Test.stub(SellApp.Client, fn conn ->
      assert Plug.Conn.get_req_header(conn, "x-custom") == ["value"]
      assert conn.host == "override.example.com"
      Req.Test.json(conn, SellApp.TestFixtures.fixture("account/get_account"))
    end)

    SellApp.Account.get_account(
      client,
      headers: [{"x-custom", "value"}],
      base_url: "https://override.example.com"
    )
  end

  test "surfaces API errors as tagged tuples", %{client: client} do
    Req.Test.stub(SellApp.Client, fn conn ->
      conn
      |> Plug.Conn.put_status(401)
      |> Req.Test.json(%{"message" => "Unauthorized"})
    end)

    assert {:error, %SellApp.Error.Authentication{status: 401}} =
             SellApp.Account.get_account(client)
  end
end
