# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.AffiliateReferralSessionsRoundTripTest do
  use ExUnit.Case, async: true

  test "ListAffiliateReferralSessionsResponseValue200ApplicationJsonPropertyDataItem round-trips between wire and struct" do
    data = %{
      "id" => 1,
      "session_id" => "session_id",
      "affiliate_id" => 1,
      "affiliate_email" => "affiliate_email",
      "expires_at" => nil,
      "created_at" => "2024-01-01T00:00:00.000Z",
      "updated_at" => "2024-01-01T00:00:00.000Z"
    }

    serialized =
      data
      |> SellApp.ListAffiliateReferralSessionsResponseValue200ApplicationJsonPropertyDataItem.from_map()
      |> SellApp.ListAffiliateReferralSessionsResponseValue200ApplicationJsonPropertyDataItem.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.ListAffiliateReferralSessionsResponseValue200ApplicationJsonPropertyDataItem.from_map()
           |> SellApp.ListAffiliateReferralSessionsResponseValue200ApplicationJsonPropertyDataItem.to_map() ==
             serialized
  end

  test "SdkGetAffiliateReferralSessionResponseValue200ApplicationJson round-trips between wire and struct" do
    data = %{
      "data" => %{
        "id" => 1,
        "session_id" => "session_id",
        "affiliate_id" => 1,
        "affiliate_email" => "affiliate_email",
        "expires_at" => nil,
        "created_at" => "2024-01-01T00:00:00.000Z",
        "updated_at" => "2024-01-01T00:00:00.000Z"
      }
    }

    serialized =
      data
      |> SellApp.SdkGetAffiliateReferralSessionResponseValue200ApplicationJson.from_map()
      |> SellApp.SdkGetAffiliateReferralSessionResponseValue200ApplicationJson.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.SdkGetAffiliateReferralSessionResponseValue200ApplicationJson.from_map()
           |> SellApp.SdkGetAffiliateReferralSessionResponseValue200ApplicationJson.to_map() ==
             serialized
  end

  test "SdkListAffiliateReferralSessionsResponseValue200ApplicationJson round-trips between wire and struct" do
    data = %{
      "data" => [
        %{
          "id" => 1,
          "session_id" => "session_id",
          "affiliate_id" => 1,
          "affiliate_email" => "affiliate_email",
          "expires_at" => nil,
          "created_at" => "2024-01-01T00:00:00.000Z",
          "updated_at" => "2024-01-01T00:00:00.000Z"
        }
      ],
      "links" => %{"first" => "first", "last" => "last", "prev" => nil, "next" => nil},
      "meta" => %{
        "current_page" => 1,
        "from" => nil,
        "last_page" => 1,
        "links" => [%{"url" => nil, "label" => "label", "active" => true}],
        "path" => "path",
        "per_page" => 1,
        "to" => nil,
        "total" => 1
      }
    }

    serialized =
      data
      |> SellApp.SdkListAffiliateReferralSessionsResponseValue200ApplicationJson.from_map()
      |> SellApp.SdkListAffiliateReferralSessionsResponseValue200ApplicationJson.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.SdkListAffiliateReferralSessionsResponseValue200ApplicationJson.from_map()
           |> SellApp.SdkListAffiliateReferralSessionsResponseValue200ApplicationJson.to_map() ==
             serialized
  end
end
