# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.BlacklistsRoundTripTest do
  use ExUnit.Case, async: true

  test "Blacklist round-trips between wire and struct" do
    data = %{
      "id" => 1,
      "type" => "ASN",
      "data" => "data",
      "description" => "description",
      "created_at" => "2024-01-01T00:00:00.000Z",
      "updated_at" => "2024-01-01T00:00:00.000Z",
      "store_id" => 1
    }

    serialized = data |> SellApp.Blacklist.from_map() |> SellApp.Blacklist.to_map()
    assert serialized == data

    assert serialized |> SellApp.Blacklist.from_map() |> SellApp.Blacklist.to_map() == serialized
  end

  test "BlacklistListResponse round-trips between wire and struct" do
    data = %{
      "data" => [
        %{
          "id" => 1,
          "type" => "ASN",
          "data" => "data",
          "description" => "description",
          "created_at" => "2024-01-01T00:00:00.000Z",
          "updated_at" => "2024-01-01T00:00:00.000Z",
          "store_id" => 1
        }
      ],
      "links" => %{"first" => "first", "last" => "last", "prev" => nil, "next" => nil},
      "meta" => %{
        "current_page" => 1,
        "from" => nil,
        "last_page" => 1,
        "links" => [%{"url" => nil, "label" => "label", "active" => true}],
        "path" => "path",
        "per_page" => 1,
        "to" => nil,
        "total" => 1
      }
    }

    serialized =
      data |> SellApp.BlacklistListResponse.from_map() |> SellApp.BlacklistListResponse.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.BlacklistListResponse.from_map()
           |> SellApp.BlacklistListResponse.to_map() == serialized
  end

  test "BlacklistResponse round-trips between wire and struct" do
    data = %{
      "data" => %{
        "id" => 1,
        "type" => "ASN",
        "data" => "data",
        "description" => "description",
        "created_at" => "2024-01-01T00:00:00.000Z",
        "updated_at" => "2024-01-01T00:00:00.000Z",
        "store_id" => 1
      }
    }

    serialized =
      data |> SellApp.BlacklistResponse.from_map() |> SellApp.BlacklistResponse.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.BlacklistResponse.from_map()
           |> SellApp.BlacklistResponse.to_map() == serialized
  end
end
