# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.BookingsCalendarEventsTest do
  use ExUnit.Case, async: true

  setup do
    client =
      SellApp.Client.new(
        api_key: "sk_test_key",
        access_token: "oauth_test",
        customer_session: "customer_test",
        browser_session: "sell_session=test",
        store: "test-store",
        req_options: [plug: {Req.Test, SellApp.Client}]
      )

    {:ok, client: client}
  end

  test "list succeeds", %{client: client} do
    Req.Test.stub(SellApp.Client, fn conn ->
      assert conn.method == "GET"
      assert String.ends_with?(conn.request_path, "/v2/booking-calendar-events")
      Req.Test.json(conn, SellApp.TestFixtures.fixture("bookings_calendar_events/list"))
    end)

    assert {:ok,
            %SellApp.Page{
              data: [%SellApp.SdkListBookingDateOverridesResponseValue200ApplicationJson{} | _]
            }} = SellApp.BookingsCalendarEvents.list(client)
  end

  test "list handles an empty page", %{client: client} do
    Req.Test.stub(SellApp.Client, fn conn ->
      Req.Test.json(conn, %{"data" => [], "list_metadata" => %{"after" => nil}})
    end)

    assert {:ok, %SellApp.Page{data: []} = page} = SellApp.BookingsCalendarEvents.list(client)
    refute SellApp.Page.has_more?(page)
    assert page |> SellApp.Page.stream() |> Enum.to_list() == []
  end

  test "set succeeds", %{client: client} do
    Req.Test.stub(SellApp.Client, fn conn ->
      assert conn.method == "POST"
      assert String.ends_with?(conn.request_path, "/v2/booking-calendar-events")
      Req.Test.json(conn, SellApp.TestFixtures.fixture("bookings_calendar_events/set"))
    end)

    assert {:ok, %SellApp.SdkSetBookingDateAvailabilityResponseValue201ApplicationJson{}} =
             SellApp.BookingsCalendarEvents.set(client, %{
               "product_variant_id" => nil,
               "dates" => ["2024-01-01"],
               "available" => true
             })
  end

  test "list encodes query parameters", %{client: client} do
    Req.Test.stub(SellApp.Client, fn conn ->
      params = Plug.Conn.fetch_query_params(conn).query_params
      assert params["product_variant_id"] == "hello world&x"
      refute Map.has_key?(params, "from")
      Req.Test.json(conn, SellApp.TestFixtures.fixture("bookings_calendar_events/list"))
    end)

    assert {:ok, _} =
             SellApp.BookingsCalendarEvents.list(client, %{product_variant_id: "hello world&x"})
  end

  test "list honors per-request options", %{client: client} do
    Req.Test.stub(SellApp.Client, fn conn ->
      assert Plug.Conn.get_req_header(conn, "x-custom") == ["value"]
      assert conn.host == "override.example.com"
      Req.Test.json(conn, SellApp.TestFixtures.fixture("bookings_calendar_events/list"))
    end)

    SellApp.BookingsCalendarEvents.list(
      client,
      %{},
      headers: [{"x-custom", "value"}],
      base_url: "https://override.example.com"
    )
  end

  test "surfaces API errors as tagged tuples", %{client: client} do
    Req.Test.stub(SellApp.Client, fn conn ->
      conn
      |> Plug.Conn.put_status(401)
      |> Req.Test.json(%{"message" => "Unauthorized"})
    end)

    assert {:error, %SellApp.Error.Authentication{status: 401}} =
             SellApp.BookingsCalendarEvents.list(client)
  end
end
