# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.BookingsRoundTripTest do
  use ExUnit.Case, async: true

  test "SdkCancelAppointmentResponseValue200ApplicationJson round-trips between wire and struct" do
    data = %{
      "data" => %{
        "id" => "00000000-0000-4000-8000-000000000000",
        "product_id" => 1,
        "product_variant_id" => 1,
        "order_id" => 1,
        "invoice_id" => 1,
        "customer_id" => nil,
        "customer_email" => nil,
        "slot_start_at" => "2024-01-01T00:00:00.000Z",
        "slot_end_at" => "2024-01-01T00:00:00.000Z",
        "timezone" => "timezone",
        "quantity" => 1,
        "status" => "pending",
        "calendar_sync_status" => "pending",
        "external_event_link" => nil,
        "video_join_url" => nil,
        "confirmed_at" => nil,
        "cancelled_at" => nil,
        "created_at" => "2024-01-01T00:00:00.000Z",
        "updated_at" => "2024-01-01T00:00:00.000Z",
        "product" => nil,
        "variant" => nil
      }
    }

    serialized =
      data
      |> SellApp.SdkCancelAppointmentResponseValue200ApplicationJson.from_map()
      |> SellApp.SdkCancelAppointmentResponseValue200ApplicationJson.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.SdkCancelAppointmentResponseValue200ApplicationJson.from_map()
           |> SellApp.SdkCancelAppointmentResponseValue200ApplicationJson.to_map() == serialized
  end

  test "SdkGetAppointmentResponseValue200ApplicationJson round-trips between wire and struct" do
    data = %{
      "data" => %{
        "id" => "00000000-0000-4000-8000-000000000000",
        "product_id" => 1,
        "product_variant_id" => 1,
        "order_id" => 1,
        "invoice_id" => 1,
        "customer_id" => nil,
        "customer_email" => nil,
        "slot_start_at" => "2024-01-01T00:00:00.000Z",
        "slot_end_at" => "2024-01-01T00:00:00.000Z",
        "timezone" => "timezone",
        "quantity" => 1,
        "status" => "pending",
        "calendar_sync_status" => "pending",
        "external_event_link" => nil,
        "video_join_url" => nil,
        "confirmed_at" => nil,
        "cancelled_at" => nil,
        "created_at" => "2024-01-01T00:00:00.000Z",
        "updated_at" => "2024-01-01T00:00:00.000Z",
        "product" => nil,
        "variant" => nil
      }
    }

    serialized =
      data
      |> SellApp.SdkGetAppointmentResponseValue200ApplicationJson.from_map()
      |> SellApp.SdkGetAppointmentResponseValue200ApplicationJson.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.SdkGetAppointmentResponseValue200ApplicationJson.from_map()
           |> SellApp.SdkGetAppointmentResponseValue200ApplicationJson.to_map() == serialized
  end

  test "SdkUpdateAppointmentResponseValue200ApplicationJson round-trips between wire and struct" do
    data = %{
      "data" => %{
        "id" => "00000000-0000-4000-8000-000000000000",
        "product_id" => 1,
        "product_variant_id" => 1,
        "order_id" => 1,
        "invoice_id" => 1,
        "customer_id" => nil,
        "customer_email" => nil,
        "slot_start_at" => "2024-01-01T00:00:00.000Z",
        "slot_end_at" => "2024-01-01T00:00:00.000Z",
        "timezone" => "timezone",
        "quantity" => 1,
        "status" => "pending",
        "calendar_sync_status" => "pending",
        "external_event_link" => nil,
        "video_join_url" => nil,
        "confirmed_at" => nil,
        "cancelled_at" => nil,
        "created_at" => "2024-01-01T00:00:00.000Z",
        "updated_at" => "2024-01-01T00:00:00.000Z",
        "product" => nil,
        "variant" => nil
      }
    }

    serialized =
      data
      |> SellApp.SdkUpdateAppointmentResponseValue200ApplicationJson.from_map()
      |> SellApp.SdkUpdateAppointmentResponseValue200ApplicationJson.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.SdkUpdateAppointmentResponseValue200ApplicationJson.from_map()
           |> SellApp.SdkUpdateAppointmentResponseValue200ApplicationJson.to_map() == serialized
  end
end
