# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.CashbackRulesRoundTripTest do
  use ExUnit.Case, async: true

  test "SdkArchiveCashbackRuleResponseValue200ApplicationJson round-trips between wire and struct" do
    data = %{
      "data" => %{
        "id" => 1,
        "percent_basis" => 1,
        "maximum_cashback_cents" => nil,
        "is_active" => true,
        "product_ids" => [1],
        "created_at" => nil,
        "updated_at" => nil,
        "deleted_at" => nil
      }
    }

    serialized =
      data
      |> SellApp.SdkArchiveCashbackRuleResponseValue200ApplicationJson.from_map()
      |> SellApp.SdkArchiveCashbackRuleResponseValue200ApplicationJson.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.SdkArchiveCashbackRuleResponseValue200ApplicationJson.from_map()
           |> SellApp.SdkArchiveCashbackRuleResponseValue200ApplicationJson.to_map() == serialized
  end

  test "SdkCreateCashbackRuleResponseValue201ApplicationJson round-trips between wire and struct" do
    data = %{
      "data" => %{
        "id" => 1,
        "percent_basis" => 1,
        "maximum_cashback_cents" => nil,
        "is_active" => true,
        "product_ids" => [1],
        "created_at" => nil,
        "updated_at" => nil,
        "deleted_at" => nil
      }
    }

    serialized =
      data
      |> SellApp.SdkCreateCashbackRuleResponseValue201ApplicationJson.from_map()
      |> SellApp.SdkCreateCashbackRuleResponseValue201ApplicationJson.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.SdkCreateCashbackRuleResponseValue201ApplicationJson.from_map()
           |> SellApp.SdkCreateCashbackRuleResponseValue201ApplicationJson.to_map() == serialized
  end

  test "SdkListCashbackRulesResponseValue200ApplicationJson round-trips between wire and struct" do
    data = %{
      "data" => [
        %{
          "id" => 1,
          "percent_basis" => 1,
          "maximum_cashback_cents" => nil,
          "is_active" => true,
          "product_ids" => [1],
          "created_at" => nil,
          "updated_at" => nil,
          "deleted_at" => nil
        }
      ]
    }

    serialized =
      data
      |> SellApp.SdkListCashbackRulesResponseValue200ApplicationJson.from_map()
      |> SellApp.SdkListCashbackRulesResponseValue200ApplicationJson.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.SdkListCashbackRulesResponseValue200ApplicationJson.from_map()
           |> SellApp.SdkListCashbackRulesResponseValue200ApplicationJson.to_map() == serialized
  end

  test "SdkReplaceCashbackRuleResponseValue200ApplicationJson round-trips between wire and struct" do
    data = %{
      "data" => %{
        "id" => 1,
        "percent_basis" => 1,
        "maximum_cashback_cents" => nil,
        "is_active" => true,
        "product_ids" => [1],
        "created_at" => nil,
        "updated_at" => nil,
        "deleted_at" => nil
      }
    }

    serialized =
      data
      |> SellApp.SdkReplaceCashbackRuleResponseValue200ApplicationJson.from_map()
      |> SellApp.SdkReplaceCashbackRuleResponseValue200ApplicationJson.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.SdkReplaceCashbackRuleResponseValue200ApplicationJson.from_map()
           |> SellApp.SdkReplaceCashbackRuleResponseValue200ApplicationJson.to_map() == serialized
  end

  test "SdkRestoreCashbackRuleResponseValue200ApplicationJson round-trips between wire and struct" do
    data = %{
      "data" => %{
        "id" => 1,
        "percent_basis" => 1,
        "maximum_cashback_cents" => nil,
        "is_active" => true,
        "product_ids" => [1],
        "created_at" => nil,
        "updated_at" => nil,
        "deleted_at" => nil
      }
    }

    serialized =
      data
      |> SellApp.SdkRestoreCashbackRuleResponseValue200ApplicationJson.from_map()
      |> SellApp.SdkRestoreCashbackRuleResponseValue200ApplicationJson.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.SdkRestoreCashbackRuleResponseValue200ApplicationJson.from_map()
           |> SellApp.SdkRestoreCashbackRuleResponseValue200ApplicationJson.to_map() == serialized
  end

  test "SdkUpdateCashbackRuleResponseValue200ApplicationJson round-trips between wire and struct" do
    data = %{
      "data" => %{
        "id" => 1,
        "percent_basis" => 1,
        "maximum_cashback_cents" => nil,
        "is_active" => true,
        "product_ids" => [1],
        "created_at" => nil,
        "updated_at" => nil,
        "deleted_at" => nil
      }
    }

    serialized =
      data
      |> SellApp.SdkUpdateCashbackRuleResponseValue200ApplicationJson.from_map()
      |> SellApp.SdkUpdateCashbackRuleResponseValue200ApplicationJson.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.SdkUpdateCashbackRuleResponseValue200ApplicationJson.from_map()
           |> SellApp.SdkUpdateCashbackRuleResponseValue200ApplicationJson.to_map() == serialized
  end
end
