# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.CommunityConnectionsRoundTripTest do
  use ExUnit.Case, async: true

  test "SdkCompleteCommunityConnectionResponseValue200ApplicationJson round-trips between wire and struct" do
    data = %{
      "data" => %{
        "platform" => "whatsapp",
        "connected" => true,
        "server" => %{
          "id" => "id",
          "name" => "name",
          "type" => nil,
          "health_status" => nil,
          "health_checked_at" => nil,
          "roles" => [%{"id" => "id", "name" => "name", "color" => "color"}]
        }
      }
    }

    serialized =
      data
      |> SellApp.SdkCompleteCommunityConnectionResponseValue200ApplicationJson.from_map()
      |> SellApp.SdkCompleteCommunityConnectionResponseValue200ApplicationJson.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.SdkCompleteCommunityConnectionResponseValue200ApplicationJson.from_map()
           |> SellApp.SdkCompleteCommunityConnectionResponseValue200ApplicationJson.to_map() ==
             serialized
  end

  test "SdkDisconnectCommunityPlatformResponseValue200ApplicationJson round-trips between wire and struct" do
    data = %{"data" => %{"platform" => "discord", "disconnected" => true}}

    serialized =
      data
      |> SellApp.SdkDisconnectCommunityPlatformResponseValue200ApplicationJson.from_map()
      |> SellApp.SdkDisconnectCommunityPlatformResponseValue200ApplicationJson.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.SdkDisconnectCommunityPlatformResponseValue200ApplicationJson.from_map()
           |> SellApp.SdkDisconnectCommunityPlatformResponseValue200ApplicationJson.to_map() ==
             serialized
  end

  test "SdkListCommunityConnectionsResponseValue200ApplicationJson round-trips between wire and struct" do
    data = %{
      "data" => [
        %{
          "platform" => "discord",
          "label" => "label",
          "configured" => true,
          "healthy" => true,
          "credential_health_status" => nil,
          "credential_health_checked_at" => nil,
          "pending_grant_count" => 1,
          "failed_grant_count" => 1,
          "issues" => [%{}],
          "accounts" => [
            %{"id" => "id", "username" => nil, "display_name" => nil, "avatar_url" => nil}
          ],
          "servers" => [
            %{
              "id" => "id",
              "name" => "name",
              "type" => nil,
              "health_status" => nil,
              "health_checked_at" => nil,
              "roles" => [%{"id" => "id", "name" => "name", "color" => "color"}]
            }
          ]
        }
      ]
    }

    serialized =
      data
      |> SellApp.SdkListCommunityConnectionsResponseValue200ApplicationJson.from_map()
      |> SellApp.SdkListCommunityConnectionsResponseValue200ApplicationJson.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.SdkListCommunityConnectionsResponseValue200ApplicationJson.from_map()
           |> SellApp.SdkListCommunityConnectionsResponseValue200ApplicationJson.to_map() ==
             serialized
  end

  test "SdkPollCommunityConnectionResponseValue200ApplicationJson round-trips between wire and struct" do
    data = %{
      "data" => %{
        "platform" => "telegram",
        "status" => "pending",
        "expires_at" => nil,
        "qr_code" => nil,
        "server" => nil,
        "groups_loaded" => true,
        "available_servers" => [%{"id" => "id", "name" => "name", "type" => "group"}]
      }
    }

    serialized =
      data
      |> SellApp.SdkPollCommunityConnectionResponseValue200ApplicationJson.from_map()
      |> SellApp.SdkPollCommunityConnectionResponseValue200ApplicationJson.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.SdkPollCommunityConnectionResponseValue200ApplicationJson.from_map()
           |> SellApp.SdkPollCommunityConnectionResponseValue200ApplicationJson.to_map() ==
             serialized
  end

  test "SdkStartCommunityConnectionResponseValue200ApplicationJson round-trips between wire and struct" do
    data = %{
      "data" => %{
        "platform" => "discord",
        "type" => "oauth",
        "mode" => "mode",
        "connect_url" => "connect_url",
        "verification_token" => "verification_token",
        "status_token" => "status_token",
        "expires_at" => nil,
        "bot_username" => nil,
        "qr_code" => "qr_code"
      }
    }

    serialized =
      data
      |> SellApp.SdkStartCommunityConnectionResponseValue200ApplicationJson.from_map()
      |> SellApp.SdkStartCommunityConnectionResponseValue200ApplicationJson.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.SdkStartCommunityConnectionResponseValue200ApplicationJson.from_map()
           |> SellApp.SdkStartCommunityConnectionResponseValue200ApplicationJson.to_map() ==
             serialized
  end

  test "SdkVerifyCommunityConnectionResponseValue200ApplicationJson round-trips between wire and struct" do
    data = %{
      "data" => %{
        "platform" => "discord",
        "healthy_count" => 1,
        "issue_count" => 1,
        "retried_count" => 1,
        "skipped_count" => 1,
        "skipped_products" => ["skipped_products"],
        "unchanged_products" => ["unchanged_products"]
      }
    }

    serialized =
      data
      |> SellApp.SdkVerifyCommunityConnectionResponseValue200ApplicationJson.from_map()
      |> SellApp.SdkVerifyCommunityConnectionResponseValue200ApplicationJson.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.SdkVerifyCommunityConnectionResponseValue200ApplicationJson.from_map()
           |> SellApp.SdkVerifyCommunityConnectionResponseValue200ApplicationJson.to_map() ==
             serialized
  end
end
