# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.CreditsProductsTest do
  use ExUnit.Case, async: true

  setup do
    client =
      SellApp.Client.new(
        api_key: "sk_test_key",
        access_token: "oauth_test",
        customer_session: "customer_test",
        browser_session: "sell_session=test",
        store: "test-store",
        req_options: [plug: {Req.Test, SellApp.Client}]
      )

    {:ok, client: client}
  end

  test "list succeeds", %{client: client} do
    Req.Test.stub(SellApp.Client, fn conn ->
      assert conn.method == "GET"
      assert String.ends_with?(conn.request_path, "/v2/credit-products")
      Req.Test.json(conn, SellApp.TestFixtures.fixture("credits_products/list"))
    end)

    assert {:ok,
            %SellApp.Page{
              data: [%SellApp.SdkListCreditsProductsResponseValue200ApplicationJson{} | _]
            }} = SellApp.CreditsProducts.list(client)
  end

  test "list handles an empty page", %{client: client} do
    Req.Test.stub(SellApp.Client, fn conn ->
      Req.Test.json(conn, %{"data" => [], "list_metadata" => %{"after" => nil}})
    end)

    assert {:ok, %SellApp.Page{data: []} = page} = SellApp.CreditsProducts.list(client)
    refute SellApp.Page.has_more?(page)
    assert page |> SellApp.Page.stream() |> Enum.to_list() == []
  end

  test "create succeeds", %{client: client} do
    Req.Test.stub(SellApp.Client, fn conn ->
      assert conn.method == "POST"
      assert String.ends_with?(conn.request_path, "/v2/credit-products")
      Req.Test.json(conn, SellApp.TestFixtures.fixture("credits_products/create"))
    end)

    assert {:ok, %SellApp.SdkCreateCreditsProductResponseValue201ApplicationJson{}} =
             SellApp.CreditsProducts.create(client, %{
               "title" => "title",
               "slug" => "slug",
               "description" => nil,
               "visibility" => "PUBLIC",
               "section_id" => nil,
               "is_draft" => true,
               "price_cents" => 1,
               "currency" => "cur",
               "minimum_purchase_quantity" => 1,
               "maximum_purchase_quantity" => nil,
               "quantity_increment" => 1,
               "stock" => nil,
               "payment_methods" => ["AUTHNET"],
               "rate_tiers" => [
                 %{
                   "min_quantity" => 1,
                   "max_quantity" => nil,
                   "unit_price" => "00000000000000000000000000"
                 }
               ],
               "expected_updated_at" => "2024-01-01T00:00:00.000Z"
             })
  end

  test "search succeeds", %{client: client} do
    Req.Test.stub(SellApp.Client, fn conn ->
      assert conn.method == "POST"
      assert String.ends_with?(conn.request_path, "/v2/credit-products/search")
      Req.Test.json(conn, SellApp.TestFixtures.fixture("credits_products/search"))
    end)

    assert {:ok,
            %SellApp.Page{
              data: [%SellApp.SdkSearchCreditsProductsResponseValue200ApplicationJson{} | _]
            }} =
             SellApp.CreditsProducts.search(client, %{
               "filters" => [
                 %{
                   "field" => "id",
                   "operator" => "operator",
                   "value" => nil,
                   "type" => "and",
                   "nested" => [%{}]
                 }
               ],
               "sort" => [%{"field" => "id", "direction" => "asc"}],
               "search" => %{"value" => nil, "case_sensitive" => true},
               "includes" => []
             })
  end

  test "search handles an empty page", %{client: client} do
    Req.Test.stub(SellApp.Client, fn conn ->
      Req.Test.json(conn, %{"data" => [], "list_metadata" => %{"after" => nil}})
    end)

    assert {:ok, %SellApp.Page{data: []} = page} =
             SellApp.CreditsProducts.search(client, %{
               "filters" => [
                 %{
                   "field" => "id",
                   "operator" => "operator",
                   "value" => nil,
                   "type" => "and",
                   "nested" => [%{}]
                 }
               ],
               "sort" => [%{"field" => "id", "direction" => "asc"}],
               "search" => %{"value" => nil, "case_sensitive" => true},
               "includes" => []
             })

    refute SellApp.Page.has_more?(page)
    assert page |> SellApp.Page.stream() |> Enum.to_list() == []
  end

  test "get succeeds", %{client: client} do
    Req.Test.stub(SellApp.Client, fn conn ->
      assert conn.method == "GET"
      assert String.ends_with?(conn.request_path, "/v2/credit-products/test_credit_product")
      Req.Test.json(conn, SellApp.TestFixtures.fixture("credits_products/get"))
    end)

    assert {:ok, %SellApp.SdkGetCreditsProductResponseValue200ApplicationJson{}} =
             SellApp.CreditsProducts.get(client, "test_credit_product")
  end

  test "replace succeeds", %{client: client} do
    Req.Test.stub(SellApp.Client, fn conn ->
      assert conn.method == "PUT"
      assert String.ends_with?(conn.request_path, "/v2/credit-products/test_credit_product")
      Req.Test.json(conn, SellApp.TestFixtures.fixture("credits_products/replace"))
    end)

    assert {:ok, %SellApp.SdkReplaceCreditsProductResponseValue200ApplicationJson{}} =
             SellApp.CreditsProducts.replace(client, "test_credit_product", %{
               "title" => "title",
               "slug" => "slug",
               "description" => "description",
               "visibility" => "PUBLIC",
               "section_id" => nil,
               "is_draft" => true,
               "price_cents" => 1,
               "currency" => "cur",
               "minimum_purchase_quantity" => 1,
               "maximum_purchase_quantity" => nil,
               "quantity_increment" => 1,
               "stock" => nil,
               "payment_methods" => ["AUTHNET"],
               "rate_tiers" => [
                 %{
                   "min_quantity" => 1,
                   "max_quantity" => nil,
                   "unit_price" => "00000000000000000000000000"
                 }
               ],
               "expected_updated_at" => "2024-01-01T00:00:00.000Z"
             })
  end

  test "update succeeds", %{client: client} do
    Req.Test.stub(SellApp.Client, fn conn ->
      assert conn.method == "PATCH"
      assert String.ends_with?(conn.request_path, "/v2/credit-products/test_credit_product")
      Req.Test.json(conn, SellApp.TestFixtures.fixture("credits_products/update"))
    end)

    assert {:ok, %SellApp.SdkUpdateCreditsProductResponseValue200ApplicationJson{}} =
             SellApp.CreditsProducts.update(client, "test_credit_product", %{
               "title" => "title",
               "slug" => "slug",
               "description" => "description",
               "visibility" => "PUBLIC",
               "section_id" => nil,
               "is_draft" => true,
               "price_cents" => 1,
               "currency" => "cur",
               "minimum_purchase_quantity" => 1,
               "maximum_purchase_quantity" => nil,
               "quantity_increment" => 1,
               "stock" => nil,
               "payment_methods" => ["AUTHNET"],
               "rate_tiers" => [
                 %{
                   "min_quantity" => 1,
                   "max_quantity" => nil,
                   "unit_price" => "00000000000000000000000000"
                 }
               ],
               "expected_updated_at" => "2024-01-01T00:00:00.000Z"
             })
  end

  test "delete succeeds", %{client: client} do
    Req.Test.stub(SellApp.Client, fn conn ->
      assert conn.method == "DELETE"
      assert String.ends_with?(conn.request_path, "/v2/credit-products/test_credit_product")
      Req.Test.json(conn, SellApp.TestFixtures.fixture("credits_products/delete"))
    end)

    assert {:ok, %SellApp.SdkDeleteCreditsProductResponseValue200ApplicationJson{}} =
             SellApp.CreditsProducts.delete(client, "test_credit_product", %{
               "expected_updated_at" => "2024-01-01T00:00:00.000Z"
             })
  end

  test "list encodes query parameters", %{client: client} do
    Req.Test.stub(SellApp.Client, fn conn ->
      params = Plug.Conn.fetch_query_params(conn).query_params
      assert params["limit"] == "hello world&x"
      refute Map.has_key?(params, "page")
      Req.Test.json(conn, SellApp.TestFixtures.fixture("credits_products/list"))
    end)

    assert {:ok, _} = SellApp.CreditsProducts.list(client, %{limit: "hello world&x"})
  end

  test "list honors per-request options", %{client: client} do
    Req.Test.stub(SellApp.Client, fn conn ->
      assert Plug.Conn.get_req_header(conn, "x-custom") == ["value"]
      assert conn.host == "override.example.com"
      Req.Test.json(conn, SellApp.TestFixtures.fixture("credits_products/list"))
    end)

    SellApp.CreditsProducts.list(
      client,
      %{},
      headers: [{"x-custom", "value"}],
      base_url: "https://override.example.com"
    )
  end

  test "surfaces API errors as tagged tuples", %{client: client} do
    Req.Test.stub(SellApp.Client, fn conn ->
      conn
      |> Plug.Conn.put_status(401)
      |> Req.Test.json(%{"message" => "Unauthorized"})
    end)

    assert {:error, %SellApp.Error.Authentication{status: 401}} =
             SellApp.CreditsProducts.list(client)
  end
end
