# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.CustomersTest do
  use ExUnit.Case, async: true

  setup do
    client =
      SellApp.Client.new(
        api_key: "sk_test_key",
        access_token: "oauth_test",
        customer_session: "customer_test",
        browser_session: "sell_session=test",
        store: "test-store",
        req_options: [plug: {Req.Test, SellApp.Client}]
      )

    {:ok, client: client}
  end

  test "list succeeds", %{client: client} do
    Req.Test.stub(SellApp.Client, fn conn ->
      assert conn.method == "GET"
      assert String.ends_with?(conn.request_path, "/v2/customers")
      Req.Test.json(conn, SellApp.TestFixtures.fixture("customers/list"))
    end)

    assert {:ok,
            %SellApp.Page{data: [%SellApp.SdkListCustomersResponseValue200ApplicationJson{} | _]}} =
             SellApp.Customers.list(client)
  end

  test "list handles an empty page", %{client: client} do
    Req.Test.stub(SellApp.Client, fn conn ->
      Req.Test.json(conn, %{"data" => [], "list_metadata" => %{"after" => nil}})
    end)

    assert {:ok, %SellApp.Page{data: []} = page} = SellApp.Customers.list(client)
    refute SellApp.Page.has_more?(page)
    assert page |> SellApp.Page.stream() |> Enum.to_list() == []
  end

  test "create_customer succeeds", %{client: client} do
    Req.Test.stub(SellApp.Client, fn conn ->
      assert conn.method == "POST"
      assert String.ends_with?(conn.request_path, "/v2/customers")
      Req.Test.json(conn, SellApp.TestFixtures.fixture("customers/create_customer"))
    end)

    assert {:ok, %SellApp.SdkCreateCustomerResponseValue201ApplicationJson{}} =
             SellApp.Customers.create_customer(client, %{
               "external_id" => "external_id",
               "email" => "email",
               "name" => nil,
               "locale" => nil,
               "metadata" => %{}
             })
  end

  test "search succeeds", %{client: client} do
    Req.Test.stub(SellApp.Client, fn conn ->
      assert conn.method == "POST"
      assert String.ends_with?(conn.request_path, "/v2/customers/search")
      Req.Test.json(conn, SellApp.TestFixtures.fixture("customers/search"))
    end)

    assert {:ok,
            %SellApp.Page{
              data: [%SellApp.SdkSearchCustomersResponseValue200ApplicationJson{} | _]
            }} =
             SellApp.Customers.search(client, %{
               "filters" => [%{"field" => "id", "operator" => "=", "value" => nil}],
               "sort" => [%{"field" => "id", "direction" => "asc"}],
               "search" => %{"value" => nil},
               "includes" => []
             })
  end

  test "search handles an empty page", %{client: client} do
    Req.Test.stub(SellApp.Client, fn conn ->
      Req.Test.json(conn, %{"data" => [], "list_metadata" => %{"after" => nil}})
    end)

    assert {:ok, %SellApp.Page{data: []} = page} =
             SellApp.Customers.search(client, %{
               "filters" => [%{"field" => "id", "operator" => "=", "value" => nil}],
               "sort" => [%{"field" => "id", "direction" => "asc"}],
               "search" => %{"value" => nil},
               "includes" => []
             })

    refute SellApp.Page.has_more?(page)
    assert page |> SellApp.Page.stream() |> Enum.to_list() == []
  end

  test "get succeeds", %{client: client} do
    Req.Test.stub(SellApp.Client, fn conn ->
      assert conn.method == "GET"
      assert String.ends_with?(conn.request_path, "/v2/customers/test_customer")
      Req.Test.json(conn, SellApp.TestFixtures.fixture("customers/get"))
    end)

    assert {:ok, %SellApp.SdkGetCustomerResponseValue200ApplicationJson{}} =
             SellApp.Customers.get(client, "test_customer")
  end

  test "update_customer succeeds", %{client: client} do
    Req.Test.stub(SellApp.Client, fn conn ->
      assert conn.method == "PATCH"
      assert String.ends_with?(conn.request_path, "/v2/customers/test_customer")
      Req.Test.json(conn, SellApp.TestFixtures.fixture("customers/update_customer"))
    end)

    assert {:ok, %SellApp.SdkUpdateCustomerResponseValue200ApplicationJson{}} =
             SellApp.Customers.update_customer(client, "test_customer", %{
               "email" => "email",
               "name" => nil,
               "locale" => nil,
               "metadata" => %{},
               "external_id" => "external_id"
             })
  end

  test "get_customer_by_external_id succeeds", %{client: client} do
    Req.Test.stub(SellApp.Client, fn conn ->
      assert conn.method == "GET"
      assert String.ends_with?(conn.request_path, "/v2/customers/external/test_external_id")
      Req.Test.json(conn, SellApp.TestFixtures.fixture("customers/get_customer_by_external_id"))
    end)

    assert {:ok, %SellApp.SdkGetCustomerResponseValue200ApplicationJson{}} =
             SellApp.Customers.get_customer_by_external_id(client, "test_external_id")
  end

  test "upsert_by_external_id succeeds", %{client: client} do
    Req.Test.stub(SellApp.Client, fn conn ->
      assert conn.method == "PUT"
      assert String.ends_with?(conn.request_path, "/v2/customers/external/test_external_id")
      Req.Test.json(conn, SellApp.TestFixtures.fixture("customers/upsert_by_external_id"))
    end)

    assert {:ok, %SellApp.SdkUpsertCustomerResponseValue200ApplicationJson{}} =
             SellApp.Customers.upsert_by_external_id(client, "test_external_id", %{
               "email" => "email",
               "name" => nil,
               "locale" => nil,
               "metadata" => %{}
             })
  end

  test "update_customer_by_external_id succeeds", %{client: client} do
    Req.Test.stub(SellApp.Client, fn conn ->
      assert conn.method == "PATCH"
      assert String.ends_with?(conn.request_path, "/v2/customers/external/test_external_id")

      Req.Test.json(
        conn,
        SellApp.TestFixtures.fixture("customers/update_customer_by_external_id")
      )
    end)

    assert {:ok, %SellApp.SdkUpdateCustomerResponseValue200ApplicationJson{}} =
             SellApp.Customers.update_customer_by_external_id(client, "test_external_id", %{
               "email" => "email",
               "name" => nil,
               "locale" => nil,
               "metadata" => %{},
               "external_id" => "external_id"
             })
  end

  test "list encodes query parameters", %{client: client} do
    Req.Test.stub(SellApp.Client, fn conn ->
      params = Plug.Conn.fetch_query_params(conn).query_params
      assert params["limit"] == "hello world&x"
      refute Map.has_key?(params, "page")
      Req.Test.json(conn, SellApp.TestFixtures.fixture("customers/list"))
    end)

    assert {:ok, _} = SellApp.Customers.list(client, %{limit: "hello world&x"})
  end

  test "list honors per-request options", %{client: client} do
    Req.Test.stub(SellApp.Client, fn conn ->
      assert Plug.Conn.get_req_header(conn, "x-custom") == ["value"]
      assert conn.host == "override.example.com"
      Req.Test.json(conn, SellApp.TestFixtures.fixture("customers/list"))
    end)

    SellApp.Customers.list(
      client,
      %{},
      headers: [{"x-custom", "value"}],
      base_url: "https://override.example.com"
    )
  end

  test "surfaces API errors as tagged tuples", %{client: client} do
    Req.Test.stub(SellApp.Client, fn conn ->
      conn
      |> Plug.Conn.put_status(401)
      |> Req.Test.json(%{"message" => "Unauthorized"})
    end)

    assert {:error, %SellApp.Error.Authentication{status: 401}} = SellApp.Customers.list(client)
  end
end
