# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.DisputesRoundTripTest do
  use ExUnit.Case, async: true

  test "ListDisputesResponseValue200ApplicationJsonPropertyDataItem round-trips between wire and struct" do
    data = %{
      "id" => "00000000-0000-4000-8000-000000000000",
      "source" => %{"type" => nil, "id" => 1},
      "provider" => "provider",
      "provider_dispute_id" => "provider_dispute_id",
      "amount" => 1,
      "currency" => "currency",
      "status" => "open",
      "reason" => nil
    }

    serialized =
      data
      |> SellApp.ListDisputesResponseValue200ApplicationJsonPropertyDataItem.from_map()
      |> SellApp.ListDisputesResponseValue200ApplicationJsonPropertyDataItem.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.ListDisputesResponseValue200ApplicationJsonPropertyDataItem.from_map()
           |> SellApp.ListDisputesResponseValue200ApplicationJsonPropertyDataItem.to_map() ==
             serialized
  end

  test "SdkGetDisputeResponseValue200ApplicationJson round-trips between wire and struct" do
    data = %{
      "data" => %{
        "id" => "00000000-0000-4000-8000-000000000000",
        "source" => %{"type" => nil, "id" => 1},
        "provider" => "provider",
        "provider_dispute_id" => "provider_dispute_id",
        "amount" => 1,
        "currency" => "currency",
        "status" => "open",
        "reason" => nil
      }
    }

    serialized =
      data
      |> SellApp.SdkGetDisputeResponseValue200ApplicationJson.from_map()
      |> SellApp.SdkGetDisputeResponseValue200ApplicationJson.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.SdkGetDisputeResponseValue200ApplicationJson.from_map()
           |> SellApp.SdkGetDisputeResponseValue200ApplicationJson.to_map() == serialized
  end

  test "SdkListDisputesResponseValue200ApplicationJson round-trips between wire and struct" do
    data = %{
      "data" => [
        %{
          "id" => "00000000-0000-4000-8000-000000000000",
          "source" => %{"type" => nil, "id" => 1},
          "provider" => "provider",
          "provider_dispute_id" => "provider_dispute_id",
          "amount" => 1,
          "currency" => "currency",
          "status" => "open",
          "reason" => nil
        }
      ],
      "links" => %{"first" => "first", "last" => "last", "prev" => nil, "next" => nil},
      "meta" => %{
        "current_page" => 1,
        "from" => nil,
        "last_page" => 1,
        "links" => [%{"url" => nil, "label" => "label", "active" => true}],
        "path" => "path",
        "per_page" => 1,
        "to" => nil,
        "total" => 1
      }
    }

    serialized =
      data
      |> SellApp.SdkListDisputesResponseValue200ApplicationJson.from_map()
      |> SellApp.SdkListDisputesResponseValue200ApplicationJson.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.SdkListDisputesResponseValue200ApplicationJson.from_map()
           |> SellApp.SdkListDisputesResponseValue200ApplicationJson.to_map() == serialized
  end
end
