# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.ProductVariantsBookingTest do
  use ExUnit.Case, async: true

  setup do
    client =
      SellApp.Client.new(
        api_key: "sk_test_key",
        access_token: "oauth_test",
        customer_session: "customer_test",
        browser_session: "sell_session=test",
        store: "test-store",
        req_options: [plug: {Req.Test, SellApp.Client}]
      )

    {:ok, client: client}
  end

  test "list_availability succeeds", %{client: client} do
    Req.Test.stub(SellApp.Client, fn conn ->
      assert conn.method == "GET"

      assert String.ends_with?(
               conn.request_path,
               "/v2/products/test_product/variants/test_variant/booking/availability"
             )

      Req.Test.json(
        conn,
        SellApp.TestFixtures.fixture("product_variants_booking/list_availability")
      )
    end)

    assert {:ok, %SellApp.SdkListBookingAvailabilityResponseValue200ApplicationJson{}} =
             SellApp.ProductVariantsBooking.list_availability(
               client,
               "test_product",
               "test_variant"
             )
  end

  test "create_hold succeeds", %{client: client} do
    Req.Test.stub(SellApp.Client, fn conn ->
      assert conn.method == "POST"

      assert String.ends_with?(
               conn.request_path,
               "/v2/products/test_product/variants/test_variant/booking/holds"
             )

      Req.Test.json(conn, SellApp.TestFixtures.fixture("product_variants_booking/create_hold"))
    end)

    assert {:ok, %SellApp.SdkCreateBookingHoldResponseValue201ApplicationJson{}} =
             SellApp.ProductVariantsBooking.create_hold(client, "test_product", "test_variant", %{
               "slot_start_at" => "2024-01-01T00:00:00.000Z",
               "quantity" => 1,
               "customer_key" => nil,
               "meta" => %{}
             })
  end

  test "release_hold succeeds", %{client: client} do
    Req.Test.stub(SellApp.Client, fn conn ->
      assert conn.method == "DELETE"

      assert String.ends_with?(
               conn.request_path,
               "/v2/products/test_product/variants/booking/holds/test_hold"
             )

      Req.Test.json(conn, SellApp.TestFixtures.fixture("product_variants_booking/release_hold"))
    end)

    assert {:ok, %SellApp.SdkReleaseBookingHoldResponseValue200ApplicationJson{ok: true}} =
             SellApp.ProductVariantsBooking.release_hold(client, "test_product", "test_hold", %{
               "customer_key" => nil
             })
  end

  test "get succeeds", %{client: client} do
    Req.Test.stub(SellApp.Client, fn conn ->
      assert conn.method == "GET"

      assert String.ends_with?(
               conn.request_path,
               "/v2/products/test_product/variants/test_variant/booking"
             )

      Req.Test.json(conn, SellApp.TestFixtures.fixture("product_variants_booking/get"))
    end)

    assert {:ok, %SellApp.SdkGetBookingConfigurationResponseValue200ApplicationJson{}} =
             SellApp.ProductVariantsBooking.get(client, "test_product", "test_variant")
  end

  test "replace succeeds", %{client: client} do
    Req.Test.stub(SellApp.Client, fn conn ->
      assert conn.method == "PUT"

      assert String.ends_with?(
               conn.request_path,
               "/v2/products/test_product/variants/test_variant/booking"
             )

      Req.Test.json(conn, SellApp.TestFixtures.fixture("product_variants_booking/replace"))
    end)

    assert {:ok, %SellApp.SdkReplaceBookingConfigurationResponseValue200ApplicationJson{}} =
             SellApp.ProductVariantsBooking.replace(client, "test_product", "test_variant", %{
               "mode" => "native",
               "conflict_scope" => "product",
               "timezone" => "timezone",
               "duration_minutes" => 30,
               "capacity_per_slot" => 1,
               "min_notice_minutes" => 1,
               "max_advance_days" => 1,
               "buffer_before_minutes" => 30,
               "buffer_after_minutes" => 30,
               "availability" => [
                 %{"day" => 1, "enabled" => true, "start" => "start", "end" => "end"},
                 %{"day" => 1, "enabled" => true, "start" => "start", "end" => "end"},
                 %{"day" => 1, "enabled" => true, "start" => "start", "end" => "end"},
                 %{"day" => 1, "enabled" => true, "start" => "start", "end" => "end"},
                 %{"day" => 1, "enabled" => true, "start" => "start", "end" => "end"},
                 %{"day" => 1, "enabled" => true, "start" => "start", "end" => "end"},
                 %{"day" => 1, "enabled" => true, "start" => "start", "end" => "end"}
               ],
               "provider_connection_ids" => [1],
               "video_provider" => "none",
               "video_provider_connection_id" => nil,
               "reminders_enabled" => true,
               "reminder_offset_value" => 1,
               "reminder_offset_unit" => "minutes",
               "meta" => %{}
             })
  end

  test "update succeeds", %{client: client} do
    Req.Test.stub(SellApp.Client, fn conn ->
      assert conn.method == "PATCH"

      assert String.ends_with?(
               conn.request_path,
               "/v2/products/test_product/variants/test_variant/booking"
             )

      Req.Test.json(conn, SellApp.TestFixtures.fixture("product_variants_booking/update"))
    end)

    assert {:ok, %SellApp.SdkUpdateBookingConfigurationResponseValue200ApplicationJson{}} =
             SellApp.ProductVariantsBooking.update(client, "test_product", "test_variant", %{
               "mode" => "native",
               "conflict_scope" => "product",
               "timezone" => "timezone",
               "duration_minutes" => 30,
               "capacity_per_slot" => 1,
               "min_notice_minutes" => 1,
               "max_advance_days" => 1,
               "buffer_before_minutes" => 30,
               "buffer_after_minutes" => 30,
               "availability" => [
                 %{"day" => 1, "enabled" => true, "start" => "start", "end" => "end"},
                 %{"day" => 1, "enabled" => true, "start" => "start", "end" => "end"},
                 %{"day" => 1, "enabled" => true, "start" => "start", "end" => "end"},
                 %{"day" => 1, "enabled" => true, "start" => "start", "end" => "end"},
                 %{"day" => 1, "enabled" => true, "start" => "start", "end" => "end"},
                 %{"day" => 1, "enabled" => true, "start" => "start", "end" => "end"},
                 %{"day" => 1, "enabled" => true, "start" => "start", "end" => "end"}
               ],
               "provider_connection_ids" => [1],
               "video_provider" => "none",
               "video_provider_connection_id" => nil,
               "reminders_enabled" => true,
               "reminder_offset_value" => 1,
               "reminder_offset_unit" => "minutes",
               "meta" => %{}
             })
  end

  test "list_availability encodes query parameters", %{client: client} do
    Req.Test.stub(SellApp.Client, fn conn ->
      params = Plug.Conn.fetch_query_params(conn).query_params
      assert params["from"] == "hello world&x"
      refute Map.has_key?(params, "to")

      Req.Test.json(
        conn,
        SellApp.TestFixtures.fixture("product_variants_booking/list_availability")
      )
    end)

    assert {:ok, _} =
             SellApp.ProductVariantsBooking.list_availability(
               client,
               "test_product",
               "test_variant",
               %{from: "hello world&x"}
             )
  end

  test "list_availability honors per-request options", %{client: client} do
    Req.Test.stub(SellApp.Client, fn conn ->
      assert Plug.Conn.get_req_header(conn, "x-custom") == ["value"]
      assert conn.host == "override.example.com"

      Req.Test.json(
        conn,
        SellApp.TestFixtures.fixture("product_variants_booking/list_availability")
      )
    end)

    SellApp.ProductVariantsBooking.list_availability(
      client,
      "test_product",
      "test_variant",
      %{},
      headers: [{"x-custom", "value"}],
      base_url: "https://override.example.com"
    )
  end

  test "surfaces API errors as tagged tuples", %{client: client} do
    Req.Test.stub(SellApp.Client, fn conn ->
      conn
      |> Plug.Conn.put_status(401)
      |> Req.Test.json(%{"message" => "Unauthorized"})
    end)

    assert {:error, %SellApp.Error.Authentication{status: 401}} =
             SellApp.ProductVariantsBooking.list_availability(
               client,
               "test_product",
               "test_variant"
             )
  end
end
