# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.ProductsRoundTripTest do
  use ExUnit.Case, async: true

  test "ListProductsResponseValue200ApplicationJsonPropertyDataItem round-trips between wire and struct" do
    data = %{
      "id" => 1,
      "title" => "title",
      "slug" => "slug",
      "description" => "description",
      "images" => [
        %{
          "path" => "path",
          "metadata" => %{
            "size" => 1,
            "filename" => "filename",
            "extension" => "extension",
            "mime_type" => "mime_type"
          }
        }
      ],
      "order" => nil,
      "visibility" => "visibility",
      "delivery_text" => nil,
      "additional_information" => [
        %{"required" => true, "key" => "key", "type" => "type", "label" => "label"}
      ],
      "other_settings" => %{
        "faq" => [%{"question" => "question", "answer" => "answer"}],
        "video_url" => "video_url",
        "redirect_url" => "redirect_url",
        "product_title" => "product_title",
        "product_description" => "product_description"
      },
      "deleted_at" => nil,
      "created_at" => "2024-01-01T00:00:00.000Z",
      "updated_at" => "2024-01-01T00:00:00.000Z",
      "store_id" => 1,
      "section_id" => nil,
      "section_order" => nil,
      "is_discoverable" => true,
      "variants" => [%{"id" => 1, "title" => "title"}],
      "url" => "url"
    }

    serialized =
      data
      |> SellApp.ListProductsResponseValue200ApplicationJsonPropertyDataItem.from_map()
      |> SellApp.ListProductsResponseValue200ApplicationJsonPropertyDataItem.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.ListProductsResponseValue200ApplicationJsonPropertyDataItem.from_map()
           |> SellApp.ListProductsResponseValue200ApplicationJsonPropertyDataItem.to_map() ==
             serialized
  end

  test "SdkBatchCreateProductsResponseValue200ApplicationJson round-trips between wire and struct" do
    data = %{
      "data" => [
        %{
          "id" => 1,
          "title" => "title",
          "slug" => "slug",
          "description" => "description",
          "images" => [
            %{
              "path" => "path",
              "metadata" => %{
                "size" => 1,
                "filename" => "filename",
                "extension" => "extension",
                "mime_type" => "mime_type"
              }
            }
          ],
          "order" => nil,
          "visibility" => "visibility",
          "delivery_text" => nil,
          "additional_information" => [
            %{"required" => true, "key" => "key", "type" => "type", "label" => "label"}
          ],
          "other_settings" => %{
            "faq" => [%{"question" => "question", "answer" => "answer"}],
            "video_url" => "video_url",
            "redirect_url" => "redirect_url",
            "product_title" => "product_title",
            "product_description" => "product_description"
          },
          "deleted_at" => nil,
          "created_at" => "2024-01-01T00:00:00.000Z",
          "updated_at" => "2024-01-01T00:00:00.000Z",
          "store_id" => 1,
          "section_id" => nil,
          "section_order" => nil,
          "is_discoverable" => true,
          "variants" => [%{"id" => 1, "title" => "title"}],
          "url" => "url"
        }
      ]
    }

    serialized =
      data
      |> SellApp.SdkBatchCreateProductsResponseValue200ApplicationJson.from_map()
      |> SellApp.SdkBatchCreateProductsResponseValue200ApplicationJson.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.SdkBatchCreateProductsResponseValue200ApplicationJson.from_map()
           |> SellApp.SdkBatchCreateProductsResponseValue200ApplicationJson.to_map() == serialized
  end

  test "SdkBatchDeleteProductsResponseValue200ApplicationJson round-trips between wire and struct" do
    data = %{
      "data" => [
        %{
          "id" => 1,
          "title" => "title",
          "slug" => "slug",
          "description" => "description",
          "images" => [
            %{
              "path" => "path",
              "metadata" => %{
                "size" => 1,
                "filename" => "filename",
                "extension" => "extension",
                "mime_type" => "mime_type"
              }
            }
          ],
          "order" => nil,
          "visibility" => "visibility",
          "delivery_text" => nil,
          "additional_information" => [
            %{"required" => true, "key" => "key", "type" => "type", "label" => "label"}
          ],
          "other_settings" => %{
            "faq" => [%{"question" => "question", "answer" => "answer"}],
            "video_url" => "video_url",
            "redirect_url" => "redirect_url",
            "product_title" => "product_title",
            "product_description" => "product_description"
          },
          "deleted_at" => nil,
          "created_at" => "2024-01-01T00:00:00.000Z",
          "updated_at" => "2024-01-01T00:00:00.000Z",
          "store_id" => 1,
          "section_id" => nil,
          "section_order" => nil,
          "is_discoverable" => true,
          "variants" => [%{"id" => 1, "title" => "title"}],
          "url" => "url"
        }
      ]
    }

    serialized =
      data
      |> SellApp.SdkBatchDeleteProductsResponseValue200ApplicationJson.from_map()
      |> SellApp.SdkBatchDeleteProductsResponseValue200ApplicationJson.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.SdkBatchDeleteProductsResponseValue200ApplicationJson.from_map()
           |> SellApp.SdkBatchDeleteProductsResponseValue200ApplicationJson.to_map() == serialized
  end

  test "SdkBatchUpdateProductsResponseValue200ApplicationJson round-trips between wire and struct" do
    data = %{
      "data" => [
        %{
          "id" => 1,
          "title" => "title",
          "slug" => "slug",
          "description" => "description",
          "images" => [
            %{
              "path" => "path",
              "metadata" => %{
                "size" => 1,
                "filename" => "filename",
                "extension" => "extension",
                "mime_type" => "mime_type"
              }
            }
          ],
          "order" => nil,
          "visibility" => "visibility",
          "delivery_text" => nil,
          "additional_information" => [
            %{"required" => true, "key" => "key", "type" => "type", "label" => "label"}
          ],
          "other_settings" => %{
            "faq" => [%{"question" => "question", "answer" => "answer"}],
            "video_url" => "video_url",
            "redirect_url" => "redirect_url",
            "product_title" => "product_title",
            "product_description" => "product_description"
          },
          "deleted_at" => nil,
          "created_at" => "2024-01-01T00:00:00.000Z",
          "updated_at" => "2024-01-01T00:00:00.000Z",
          "store_id" => 1,
          "section_id" => nil,
          "section_order" => nil,
          "is_discoverable" => true,
          "variants" => [%{"id" => 1, "title" => "title"}],
          "url" => "url"
        }
      ]
    }

    serialized =
      data
      |> SellApp.SdkBatchUpdateProductsResponseValue200ApplicationJson.from_map()
      |> SellApp.SdkBatchUpdateProductsResponseValue200ApplicationJson.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.SdkBatchUpdateProductsResponseValue200ApplicationJson.from_map()
           |> SellApp.SdkBatchUpdateProductsResponseValue200ApplicationJson.to_map() == serialized
  end

  test "SdkCreateProductResponseValue201ApplicationJson round-trips between wire and struct" do
    data = %{
      "data" => %{
        "id" => 1,
        "title" => "title",
        "slug" => "slug",
        "description" => "description",
        "images" => [
          %{
            "path" => "path",
            "metadata" => %{
              "size" => 1,
              "filename" => "filename",
              "extension" => "extension",
              "mime_type" => "mime_type"
            }
          }
        ],
        "order" => nil,
        "visibility" => "visibility",
        "delivery_text" => nil,
        "additional_information" => [
          %{"required" => true, "key" => "key", "type" => "type", "label" => "label"}
        ],
        "other_settings" => %{
          "faq" => [%{"question" => "question", "answer" => "answer"}],
          "video_url" => "video_url",
          "redirect_url" => "redirect_url",
          "product_title" => "product_title",
          "product_description" => "product_description"
        },
        "deleted_at" => nil,
        "created_at" => "2024-01-01T00:00:00.000Z",
        "updated_at" => "2024-01-01T00:00:00.000Z",
        "store_id" => 1,
        "section_id" => nil,
        "section_order" => nil,
        "is_discoverable" => true,
        "variants" => [%{"id" => 1, "title" => "title"}],
        "url" => "url"
      }
    }

    serialized =
      data
      |> SellApp.SdkCreateProductResponseValue201ApplicationJson.from_map()
      |> SellApp.SdkCreateProductResponseValue201ApplicationJson.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.SdkCreateProductResponseValue201ApplicationJson.from_map()
           |> SellApp.SdkCreateProductResponseValue201ApplicationJson.to_map() == serialized
  end

  test "SdkDeleteProductResponseValue200ApplicationJson round-trips between wire and struct" do
    data = %{
      "data" => %{
        "id" => 1,
        "title" => "title",
        "slug" => "slug",
        "description" => "description",
        "images" => [
          %{
            "path" => "path",
            "metadata" => %{
              "size" => 1,
              "filename" => "filename",
              "extension" => "extension",
              "mime_type" => "mime_type"
            }
          }
        ],
        "order" => nil,
        "visibility" => "visibility",
        "delivery_text" => nil,
        "additional_information" => [
          %{"required" => true, "key" => "key", "type" => "type", "label" => "label"}
        ],
        "other_settings" => %{
          "faq" => [%{"question" => "question", "answer" => "answer"}],
          "video_url" => "video_url",
          "redirect_url" => "redirect_url",
          "product_title" => "product_title",
          "product_description" => "product_description"
        },
        "deleted_at" => nil,
        "created_at" => "2024-01-01T00:00:00.000Z",
        "updated_at" => "2024-01-01T00:00:00.000Z",
        "store_id" => 1,
        "section_id" => nil,
        "section_order" => nil,
        "is_discoverable" => true,
        "variants" => [%{"id" => 1, "title" => "title"}],
        "url" => "url"
      }
    }

    serialized =
      data
      |> SellApp.SdkDeleteProductResponseValue200ApplicationJson.from_map()
      |> SellApp.SdkDeleteProductResponseValue200ApplicationJson.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.SdkDeleteProductResponseValue200ApplicationJson.from_map()
           |> SellApp.SdkDeleteProductResponseValue200ApplicationJson.to_map() == serialized
  end

  test "SdkGetProductResponseValue200ApplicationJson round-trips between wire and struct" do
    data = %{
      "data" => %{
        "id" => 1,
        "title" => "title",
        "slug" => "slug",
        "description" => "description",
        "images" => [
          %{
            "path" => "path",
            "metadata" => %{
              "size" => 1,
              "filename" => "filename",
              "extension" => "extension",
              "mime_type" => "mime_type"
            }
          }
        ],
        "order" => nil,
        "visibility" => "visibility",
        "delivery_text" => nil,
        "additional_information" => [
          %{"required" => true, "key" => "key", "type" => "type", "label" => "label"}
        ],
        "other_settings" => %{
          "faq" => [%{"question" => "question", "answer" => "answer"}],
          "video_url" => "video_url",
          "redirect_url" => "redirect_url",
          "product_title" => "product_title",
          "product_description" => "product_description"
        },
        "deleted_at" => nil,
        "created_at" => "2024-01-01T00:00:00.000Z",
        "updated_at" => "2024-01-01T00:00:00.000Z",
        "store_id" => 1,
        "section_id" => nil,
        "section_order" => nil,
        "is_discoverable" => true,
        "variants" => [%{"id" => 1, "title" => "title"}],
        "url" => "url"
      }
    }

    serialized =
      data
      |> SellApp.SdkGetProductResponseValue200ApplicationJson.from_map()
      |> SellApp.SdkGetProductResponseValue200ApplicationJson.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.SdkGetProductResponseValue200ApplicationJson.from_map()
           |> SellApp.SdkGetProductResponseValue200ApplicationJson.to_map() == serialized
  end

  test "SdkListProductsResponseValue200ApplicationJson round-trips between wire and struct" do
    data = %{
      "data" => [
        %{
          "id" => 1,
          "title" => "title",
          "slug" => "slug",
          "description" => "description",
          "images" => [
            %{
              "path" => "path",
              "metadata" => %{
                "size" => 1,
                "filename" => "filename",
                "extension" => "extension",
                "mime_type" => "mime_type"
              }
            }
          ],
          "order" => nil,
          "visibility" => "visibility",
          "delivery_text" => nil,
          "additional_information" => [
            %{"required" => true, "key" => "key", "type" => "type", "label" => "label"}
          ],
          "other_settings" => %{
            "faq" => [%{"question" => "question", "answer" => "answer"}],
            "video_url" => "video_url",
            "redirect_url" => "redirect_url",
            "product_title" => "product_title",
            "product_description" => "product_description"
          },
          "deleted_at" => nil,
          "created_at" => "2024-01-01T00:00:00.000Z",
          "updated_at" => "2024-01-01T00:00:00.000Z",
          "store_id" => 1,
          "section_id" => nil,
          "section_order" => nil,
          "is_discoverable" => true,
          "variants" => [%{"id" => 1, "title" => "title"}],
          "url" => "url"
        }
      ],
      "links" => %{"first" => "first", "last" => "last", "prev" => nil, "next" => nil},
      "meta" => %{
        "current_page" => 1,
        "from" => nil,
        "last_page" => 1,
        "links" => [%{"url" => nil, "label" => "label", "active" => true}],
        "path" => "path",
        "per_page" => 1,
        "to" => nil,
        "total" => 1
      }
    }

    serialized =
      data
      |> SellApp.SdkListProductsResponseValue200ApplicationJson.from_map()
      |> SellApp.SdkListProductsResponseValue200ApplicationJson.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.SdkListProductsResponseValue200ApplicationJson.from_map()
           |> SellApp.SdkListProductsResponseValue200ApplicationJson.to_map() == serialized
  end

  test "SdkReplaceProductResponseValue200ApplicationJson round-trips between wire and struct" do
    data = %{
      "data" => %{
        "id" => 1,
        "title" => "title",
        "slug" => "slug",
        "description" => "description",
        "images" => [
          %{
            "path" => "path",
            "metadata" => %{
              "size" => 1,
              "filename" => "filename",
              "extension" => "extension",
              "mime_type" => "mime_type"
            }
          }
        ],
        "order" => nil,
        "visibility" => "visibility",
        "delivery_text" => nil,
        "additional_information" => [
          %{"required" => true, "key" => "key", "type" => "type", "label" => "label"}
        ],
        "other_settings" => %{
          "faq" => [%{"question" => "question", "answer" => "answer"}],
          "video_url" => "video_url",
          "redirect_url" => "redirect_url",
          "product_title" => "product_title",
          "product_description" => "product_description"
        },
        "deleted_at" => nil,
        "created_at" => "2024-01-01T00:00:00.000Z",
        "updated_at" => "2024-01-01T00:00:00.000Z",
        "store_id" => 1,
        "section_id" => nil,
        "section_order" => nil,
        "is_discoverable" => true,
        "variants" => [%{"id" => 1, "title" => "title"}],
        "url" => "url"
      }
    }

    serialized =
      data
      |> SellApp.SdkReplaceProductResponseValue200ApplicationJson.from_map()
      |> SellApp.SdkReplaceProductResponseValue200ApplicationJson.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.SdkReplaceProductResponseValue200ApplicationJson.from_map()
           |> SellApp.SdkReplaceProductResponseValue200ApplicationJson.to_map() == serialized
  end

  test "SdkSearchProductsResponseValue200ApplicationJson round-trips between wire and struct" do
    data = %{
      "data" => [
        %{
          "id" => 1,
          "title" => "title",
          "slug" => "slug",
          "description" => "description",
          "images" => [
            %{
              "path" => "path",
              "metadata" => %{
                "size" => 1,
                "filename" => "filename",
                "extension" => "extension",
                "mime_type" => "mime_type"
              }
            }
          ],
          "order" => nil,
          "visibility" => "visibility",
          "delivery_text" => "delivery_text",
          "additional_information" => [
            %{"required" => true, "key" => "key", "type" => "type", "label" => "label"}
          ],
          "other_settings" => %{
            "faq" => [%{"question" => "question", "answer" => "answer"}],
            "video_url" => "video_url",
            "redirect_url" => "redirect_url",
            "product_title" => "product_title",
            "product_description" => "product_description"
          },
          "deleted_at" => nil,
          "created_at" => "2024-01-01T00:00:00.000Z",
          "updated_at" => "2024-01-01T00:00:00.000Z",
          "store_id" => 1,
          "section_id" => nil,
          "section_order" => nil,
          "is_discoverable" => true,
          "variants" => [%{"id" => 1, "title" => "title"}],
          "url" => "url"
        }
      ],
      "links" => %{},
      "meta" => %{}
    }

    serialized =
      data
      |> SellApp.SdkSearchProductsResponseValue200ApplicationJson.from_map()
      |> SellApp.SdkSearchProductsResponseValue200ApplicationJson.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.SdkSearchProductsResponseValue200ApplicationJson.from_map()
           |> SellApp.SdkSearchProductsResponseValue200ApplicationJson.to_map() == serialized
  end

  test "SdkUpdateProductResponseValue200ApplicationJson round-trips between wire and struct" do
    data = %{
      "data" => %{
        "id" => 1,
        "title" => "title",
        "slug" => "slug",
        "description" => "description",
        "images" => [
          %{
            "path" => "path",
            "metadata" => %{
              "size" => 1,
              "filename" => "filename",
              "extension" => "extension",
              "mime_type" => "mime_type"
            }
          }
        ],
        "order" => nil,
        "visibility" => "visibility",
        "delivery_text" => nil,
        "additional_information" => [
          %{"required" => true, "key" => "key", "type" => "type", "label" => "label"}
        ],
        "other_settings" => %{
          "faq" => [%{"question" => "question", "answer" => "answer"}],
          "video_url" => "video_url",
          "redirect_url" => "redirect_url",
          "product_title" => "product_title",
          "product_description" => "product_description"
        },
        "deleted_at" => nil,
        "created_at" => "2024-01-01T00:00:00.000Z",
        "updated_at" => "2024-01-01T00:00:00.000Z",
        "store_id" => 1,
        "section_id" => nil,
        "section_order" => nil,
        "is_discoverable" => true,
        "variants" => [%{"id" => 1, "title" => "title"}],
        "url" => "url"
      }
    }

    serialized =
      data
      |> SellApp.SdkUpdateProductResponseValue200ApplicationJson.from_map()
      |> SellApp.SdkUpdateProductResponseValue200ApplicationJson.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.SdkUpdateProductResponseValue200ApplicationJson.from_map()
           |> SellApp.SdkUpdateProductResponseValue200ApplicationJson.to_map() == serialized
  end

  test "SearchProductsResponseValue200ApplicationJsonPropertyDataItem round-trips between wire and struct" do
    data = %{
      "id" => 1,
      "title" => "title",
      "slug" => "slug",
      "description" => "description",
      "images" => [
        %{
          "path" => "path",
          "metadata" => %{
            "size" => 1,
            "filename" => "filename",
            "extension" => "extension",
            "mime_type" => "mime_type"
          }
        }
      ],
      "order" => nil,
      "visibility" => "visibility",
      "delivery_text" => "delivery_text",
      "additional_information" => [
        %{"required" => true, "key" => "key", "type" => "type", "label" => "label"}
      ],
      "other_settings" => %{
        "faq" => [%{"question" => "question", "answer" => "answer"}],
        "video_url" => "video_url",
        "redirect_url" => "redirect_url",
        "product_title" => "product_title",
        "product_description" => "product_description"
      },
      "deleted_at" => nil,
      "created_at" => "2024-01-01T00:00:00.000Z",
      "updated_at" => "2024-01-01T00:00:00.000Z",
      "store_id" => 1,
      "section_id" => nil,
      "section_order" => nil,
      "is_discoverable" => true,
      "variants" => [%{"id" => 1, "title" => "title"}],
      "url" => "url"
    }

    serialized =
      data
      |> SellApp.SearchProductsResponseValue200ApplicationJsonPropertyDataItem.from_map()
      |> SellApp.SearchProductsResponseValue200ApplicationJsonPropertyDataItem.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.SearchProductsResponseValue200ApplicationJsonPropertyDataItem.from_map()
           |> SellApp.SearchProductsResponseValue200ApplicationJsonPropertyDataItem.to_map() ==
             serialized
  end
end
