# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.ProductsTest do
  use ExUnit.Case, async: true

  setup do
    client =
      SellApp.Client.new(
        api_key: "sk_test_key",
        access_token: "oauth_test",
        customer_session: "customer_test",
        browser_session: "sell_session=test",
        store: "test-store",
        req_options: [plug: {Req.Test, SellApp.Client}]
      )

    {:ok, client: client}
  end

  test "list succeeds", %{client: client} do
    Req.Test.stub(SellApp.Client, fn conn ->
      assert conn.method == "GET"
      assert String.ends_with?(conn.request_path, "/v2/products")
      Req.Test.json(conn, SellApp.TestFixtures.fixture("products/list"))
    end)

    assert {:ok,
            %SellApp.Page{
              data: [
                %SellApp.ListProductsResponseValue200ApplicationJsonPropertyDataItem{
                  id: 1,
                  title: "title"
                }
                | _
              ]
            }} = SellApp.Products.list(client)
  end

  test "list handles an empty page", %{client: client} do
    Req.Test.stub(SellApp.Client, fn conn ->
      Req.Test.json(conn, %{"data" => [], "list_metadata" => %{"after" => nil}})
    end)

    assert {:ok, %SellApp.Page{data: []} = page} = SellApp.Products.list(client)
    refute SellApp.Page.has_more?(page)
    assert page |> SellApp.Page.stream() |> Enum.to_list() == []
  end

  test "create succeeds", %{client: client} do
    Req.Test.stub(SellApp.Client, fn conn ->
      assert conn.method == "POST"
      assert String.ends_with?(conn.request_path, "/v2/products")
      Req.Test.json(conn, SellApp.TestFixtures.fixture("products/create"))
    end)

    assert {:ok, %SellApp.SdkCreateProductResponseValue201ApplicationJson{}} =
             SellApp.Products.create(client, %{
               "title" => "title",
               "description" => "description",
               "visibility" => "PUBLIC",
               "slug" => "slug",
               "type" => "product",
               "section" => nil,
               "additional_information" => [
                 %{
                   "type" => "text",
                   "required" => true,
                   "label" => "label",
                   "key" => "key",
                   "options" => ["options"],
                   "placeholder" => "placeholder",
                   "description" => "description",
                   "variant" => "variant",
                   "date_options" => %{}
                 }
               ],
               "other_settings" => %{
                 "redirect_url" => "redirect_url",
                 "video_url" => "video_url",
                 "product_title" => "product_title",
                 "product_description" => "product_description",
                 "faq" => [%{"question" => "question", "answer" => "answer"}]
               },
               "variants" => [
                 %{
                   "title" => "title",
                   "description" => "description",
                   "deliverable" => %{
                     "types" => ["DOWNLOADABLE"],
                     "data" => %{
                       "stock" => nil,
                       "serials" => ["serials"],
                       "removeDuplicate" => true,
                       "parsingMode" => "COMMA",
                       "comment" => "comment",
                       "webhook" => "webhook",
                       "booking" => %{
                         "mode" => "native",
                         "conflict_scope" => "product",
                         "timezone" => "timezone",
                         "duration_minutes" => 30,
                         "capacity_per_slot" => 1,
                         "min_notice_minutes" => 1,
                         "max_advance_days" => 1,
                         "buffer_before_minutes" => 30,
                         "buffer_after_minutes" => 30,
                         "availability" => [
                           %{"day" => 1, "enabled" => true, "start" => "start", "end" => "end"},
                           %{"day" => 1, "enabled" => true, "start" => "start", "end" => "end"},
                           %{"day" => 1, "enabled" => true, "start" => "start", "end" => "end"},
                           %{"day" => 1, "enabled" => true, "start" => "start", "end" => "end"},
                           %{"day" => 1, "enabled" => true, "start" => "start", "end" => "end"},
                           %{"day" => 1, "enabled" => true, "start" => "start", "end" => "end"},
                           %{"day" => 1, "enabled" => true, "start" => "start", "end" => "end"}
                         ],
                         "provider_connection_ids" => [1],
                         "video_provider" => "none",
                         "video_provider_connection_id" => nil,
                         "reminders_enabled" => true,
                         "reminder_offset_value" => 1,
                         "reminder_offset_unit" => "minutes",
                         "meta" => %{}
                       },
                       "credit_rate_tiers" => [
                         %{
                           "min_quantity" => 1,
                           "max_quantity" => nil,
                           "unit_price" => "unit_price"
                         }
                       ]
                     }
                   },
                   "pricing" => %{
                     "humble" => true,
                     "price" => %{"price" => 1, "currency" => "currency"}
                   },
                   "minimum_purchase_quantity" => 1,
                   "maximum_purchase_quantity" => nil,
                   "bulk_discount" => [
                     %{"minimum_purchase_amount" => 1, "discount_percentage" => 1}
                   ],
                   "payment_methods" => ["AUTHNET"],
                   "other_settings" => %{"quantity_increments" => 1},
                   "expected_updated_at" => "2024-01-01T00:00:00.000Z"
                 }
               ],
               "bundle_items" => [%{"product_variant_id" => 1, "quantity" => 1}]
             })
  end

  test "get succeeds", %{client: client} do
    Req.Test.stub(SellApp.Client, fn conn ->
      assert conn.method == "GET"
      assert String.ends_with?(conn.request_path, "/v2/products/test_product")
      Req.Test.json(conn, SellApp.TestFixtures.fixture("products/get"))
    end)

    assert {:ok, %SellApp.SdkGetProductResponseValue200ApplicationJson{}} =
             SellApp.Products.get(client, "test_product")
  end

  test "replace succeeds", %{client: client} do
    Req.Test.stub(SellApp.Client, fn conn ->
      assert conn.method == "PUT"
      assert String.ends_with?(conn.request_path, "/v2/products/test_product")
      Req.Test.json(conn, SellApp.TestFixtures.fixture("products/replace"))
    end)

    assert {:ok, %SellApp.SdkReplaceProductResponseValue200ApplicationJson{}} =
             SellApp.Products.replace(client, "test_product", %{
               "title" => "title",
               "description" => "description",
               "visibility" => "PUBLIC",
               "slug" => "slug",
               "section" => nil,
               "additional_information" => [
                 %{
                   "type" => "text",
                   "required" => true,
                   "label" => "label",
                   "key" => "key",
                   "options" => ["options"],
                   "placeholder" => "placeholder",
                   "description" => "description",
                   "variant" => "variant",
                   "date_options" => %{}
                 }
               ],
               "other_settings" => %{
                 "redirect_url" => "redirect_url",
                 "video_url" => "video_url",
                 "product_title" => "product_title",
                 "product_description" => "product_description",
                 "faq" => [%{"question" => "question", "answer" => "answer"}]
               },
               "expected_updated_at" => "2024-01-01T00:00:00.000Z"
             })
  end

  test "update succeeds", %{client: client} do
    Req.Test.stub(SellApp.Client, fn conn ->
      assert conn.method == "PATCH"
      assert String.ends_with?(conn.request_path, "/v2/products/test_product")
      Req.Test.json(conn, SellApp.TestFixtures.fixture("products/update"))
    end)

    assert {:ok, %SellApp.SdkUpdateProductResponseValue200ApplicationJson{}} =
             SellApp.Products.update(client, "test_product", %{
               "title" => "title",
               "description" => "description",
               "visibility" => "PUBLIC",
               "slug" => "slug",
               "section" => nil,
               "additional_information" => [
                 %{
                   "type" => "text",
                   "required" => true,
                   "label" => "label",
                   "key" => "key",
                   "options" => ["options"],
                   "placeholder" => "placeholder",
                   "description" => "description",
                   "variant" => "variant",
                   "date_options" => %{}
                 }
               ],
               "other_settings" => %{
                 "redirect_url" => "redirect_url",
                 "video_url" => "video_url",
                 "product_title" => "product_title",
                 "product_description" => "product_description",
                 "faq" => [%{"question" => "question", "answer" => "answer"}]
               },
               "expected_updated_at" => "2024-01-01T00:00:00.000Z"
             })
  end

  test "delete succeeds", %{client: client} do
    Req.Test.stub(SellApp.Client, fn conn ->
      assert conn.method == "DELETE"
      assert String.ends_with?(conn.request_path, "/v2/products/test_product")
      Req.Test.json(conn, SellApp.TestFixtures.fixture("products/delete"))
    end)

    assert {:ok, %SellApp.SdkDeleteProductResponseValue200ApplicationJson{}} =
             SellApp.Products.delete(client, "test_product", %{
               "expected_updated_at" => "2024-01-01T00:00:00.000Z"
             })
  end

  test "search succeeds", %{client: client} do
    Req.Test.stub(SellApp.Client, fn conn ->
      assert conn.method == "POST"
      assert String.ends_with?(conn.request_path, "/v2/products/search")
      Req.Test.json(conn, SellApp.TestFixtures.fixture("products/search"))
    end)

    assert {:ok,
            %SellApp.Page{
              data: [
                %SellApp.SearchProductsResponseValue200ApplicationJsonPropertyDataItem{
                  id: 1,
                  title: "title"
                }
                | _
              ]
            }} =
             SellApp.Products.search(client, %{
               "filters" => [
                 %{
                   "field" => "field",
                   "operator" => "operator",
                   "value" => nil,
                   "type" => "and",
                   "nested" => [%{}]
                 }
               ],
               "sort" => [%{"field" => "field", "direction" => "asc"}],
               "search" => %{"value" => nil, "case_sensitive" => true},
               "includes" => [%{"relation" => "relation"}]
             })
  end

  test "search handles an empty page", %{client: client} do
    Req.Test.stub(SellApp.Client, fn conn ->
      Req.Test.json(conn, %{"data" => [], "list_metadata" => %{"after" => nil}})
    end)

    assert {:ok, %SellApp.Page{data: []} = page} =
             SellApp.Products.search(client, %{
               "filters" => [
                 %{
                   "field" => "field",
                   "operator" => "operator",
                   "value" => nil,
                   "type" => "and",
                   "nested" => [%{}]
                 }
               ],
               "sort" => [%{"field" => "field", "direction" => "asc"}],
               "search" => %{"value" => nil, "case_sensitive" => true},
               "includes" => [%{"relation" => "relation"}]
             })

    refute SellApp.Page.has_more?(page)
    assert page |> SellApp.Page.stream() |> Enum.to_list() == []
  end

  test "batch_create succeeds", %{client: client} do
    Req.Test.stub(SellApp.Client, fn conn ->
      assert conn.method == "POST"
      assert String.ends_with?(conn.request_path, "/v2/products/batch")
      Req.Test.json(conn, SellApp.TestFixtures.fixture("products/batch_create"))
    end)

    assert {:ok, %SellApp.SdkBatchCreateProductsResponseValue200ApplicationJson{}} =
             SellApp.Products.batch_create(client, %{
               "resources" => [
                 %{
                   "title" => "title",
                   "description" => "description",
                   "visibility" => "PUBLIC",
                   "slug" => "slug",
                   "type" => "product",
                   "section" => nil,
                   "additional_information" => [
                     %{
                       "type" => "text",
                       "required" => true,
                       "label" => "label",
                       "key" => "key",
                       "options" => ["options"],
                       "placeholder" => "placeholder",
                       "description" => "description",
                       "variant" => "variant",
                       "date_options" => %{}
                     }
                   ],
                   "other_settings" => %{
                     "redirect_url" => "redirect_url",
                     "video_url" => "video_url",
                     "product_title" => "product_title",
                     "product_description" => "product_description",
                     "faq" => [%{"question" => "question", "answer" => "answer"}]
                   }
                 }
               ]
             })
  end

  test "batch_update succeeds", %{client: client} do
    Req.Test.stub(SellApp.Client, fn conn ->
      assert conn.method == "PATCH"
      assert String.ends_with?(conn.request_path, "/v2/products/batch")
      Req.Test.json(conn, SellApp.TestFixtures.fixture("products/batch_update"))
    end)

    assert {:ok, %SellApp.SdkBatchUpdateProductsResponseValue200ApplicationJson{}} =
             SellApp.Products.batch_update(client, %{"resources" => %{}})
  end

  test "batch_delete succeeds", %{client: client} do
    Req.Test.stub(SellApp.Client, fn conn ->
      assert conn.method == "DELETE"
      assert String.ends_with?(conn.request_path, "/v2/products/batch")
      Req.Test.json(conn, SellApp.TestFixtures.fixture("products/batch_delete"))
    end)

    assert {:ok, %SellApp.SdkBatchDeleteProductsResponseValue200ApplicationJson{}} =
             SellApp.Products.batch_delete(client, %{"resources" => [1]})
  end

  test "list encodes query parameters", %{client: client} do
    Req.Test.stub(SellApp.Client, fn conn ->
      params = Plug.Conn.fetch_query_params(conn).query_params
      assert params["limit"] == "hello world&x"
      refute Map.has_key?(params, "page")
      Req.Test.json(conn, SellApp.TestFixtures.fixture("products/list"))
    end)

    assert {:ok, _} = SellApp.Products.list(client, %{limit: "hello world&x"})
  end

  test "list honors per-request options", %{client: client} do
    Req.Test.stub(SellApp.Client, fn conn ->
      assert Plug.Conn.get_req_header(conn, "x-custom") == ["value"]
      assert conn.host == "override.example.com"
      Req.Test.json(conn, SellApp.TestFixtures.fixture("products/list"))
    end)

    SellApp.Products.list(
      client,
      %{},
      headers: [{"x-custom", "value"}],
      base_url: "https://override.example.com"
    )
  end

  test "surfaces API errors as tagged tuples", %{client: client} do
    Req.Test.stub(SellApp.Client, fn conn ->
      conn
      |> Plug.Conn.put_status(401)
      |> Req.Test.json(%{"message" => "Unauthorized"})
    end)

    assert {:error, %SellApp.Error.Authentication{status: 401}} = SellApp.Products.list(client)
  end
end
