# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.PromotionsPhasesRoundTripTest do
  use ExUnit.Case, async: true

  test "SdkListPromotionPhasesResponseValue200ApplicationJson round-trips between wire and struct" do
    data = %{
      "data" => [
        %{
          "id" => 1,
          "promotion_id" => 1,
          "sort_order" => 1,
          "discount_type" => "percentage",
          "discount_value" => "discount_value",
          "ends_at" => nil,
          "max_redemptions" => nil,
          "minimum_amount" => nil,
          "created_at" => nil,
          "updated_at" => nil,
          "deleted_at" => nil
        }
      ]
    }

    serialized =
      data
      |> SellApp.SdkListPromotionPhasesResponseValue200ApplicationJson.from_map()
      |> SellApp.SdkListPromotionPhasesResponseValue200ApplicationJson.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.SdkListPromotionPhasesResponseValue200ApplicationJson.from_map()
           |> SellApp.SdkListPromotionPhasesResponseValue200ApplicationJson.to_map() == serialized
  end

  test "SdkReplacePromotionPhasesResponseValue200ApplicationJson round-trips between wire and struct" do
    data = %{
      "data" => [
        %{
          "id" => 1,
          "promotion_id" => 1,
          "sort_order" => 1,
          "discount_type" => "percentage",
          "discount_value" => "discount_value",
          "ends_at" => nil,
          "max_redemptions" => nil,
          "minimum_amount" => nil,
          "created_at" => nil,
          "updated_at" => nil,
          "deleted_at" => nil
        }
      ]
    }

    serialized =
      data
      |> SellApp.SdkReplacePromotionPhasesResponseValue200ApplicationJson.from_map()
      |> SellApp.SdkReplacePromotionPhasesResponseValue200ApplicationJson.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.SdkReplacePromotionPhasesResponseValue200ApplicationJson.from_map()
           |> SellApp.SdkReplacePromotionPhasesResponseValue200ApplicationJson.to_map() ==
             serialized
  end
end
