# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.SectionsRoundTripTest do
  use ExUnit.Case, async: true

  test "ListSectionsResponseValue200ApplicationJsonPropertyDataItem round-trips between wire and struct" do
    data = %{
      "id" => 1,
      "title" => "title",
      "slug" => nil,
      "hidden" => true,
      "order" => 1,
      "created_at" => "2024-01-01T00:00:00.000Z",
      "updated_at" => "2024-01-01T00:00:00.000Z",
      "store_id" => 1,
      "groups_linked" => 1,
      "products_linked" => 1,
      "groups" => [%{"id" => 1, "title" => "title", "group_products" => 1}],
      "products" => [%{"id" => "id", "title" => "title", "description" => "description"}]
    }

    serialized =
      data
      |> SellApp.ListSectionsResponseValue200ApplicationJsonPropertyDataItem.from_map()
      |> SellApp.ListSectionsResponseValue200ApplicationJsonPropertyDataItem.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.ListSectionsResponseValue200ApplicationJsonPropertyDataItem.from_map()
           |> SellApp.ListSectionsResponseValue200ApplicationJsonPropertyDataItem.to_map() ==
             serialized
  end

  test "SdkBatchCreateSectionsResponseValue200ApplicationJson round-trips between wire and struct" do
    data = %{
      "data" => [
        %{
          "id" => 1,
          "title" => "title",
          "slug" => nil,
          "hidden" => true,
          "order" => 1,
          "created_at" => "2024-01-01T00:00:00.000Z",
          "updated_at" => "2024-01-01T00:00:00.000Z",
          "store_id" => 1,
          "groups_linked" => 1,
          "products_linked" => 1,
          "groups" => [%{"id" => 1, "title" => "title", "group_products" => 1}],
          "products" => [%{"id" => "id", "title" => "title", "description" => "description"}]
        }
      ]
    }

    serialized =
      data
      |> SellApp.SdkBatchCreateSectionsResponseValue200ApplicationJson.from_map()
      |> SellApp.SdkBatchCreateSectionsResponseValue200ApplicationJson.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.SdkBatchCreateSectionsResponseValue200ApplicationJson.from_map()
           |> SellApp.SdkBatchCreateSectionsResponseValue200ApplicationJson.to_map() == serialized
  end

  test "SdkBatchDeleteSectionsResponseValue200ApplicationJson round-trips between wire and struct" do
    data = %{
      "data" => [
        %{
          "id" => 1,
          "title" => "title",
          "slug" => nil,
          "hidden" => true,
          "order" => 1,
          "created_at" => "2024-01-01T00:00:00.000Z",
          "updated_at" => "2024-01-01T00:00:00.000Z",
          "store_id" => 1,
          "groups_linked" => 1,
          "products_linked" => 1,
          "groups" => [%{"id" => 1, "title" => "title", "group_products" => 1}],
          "products" => [%{"id" => "id", "title" => "title", "description" => "description"}]
        }
      ]
    }

    serialized =
      data
      |> SellApp.SdkBatchDeleteSectionsResponseValue200ApplicationJson.from_map()
      |> SellApp.SdkBatchDeleteSectionsResponseValue200ApplicationJson.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.SdkBatchDeleteSectionsResponseValue200ApplicationJson.from_map()
           |> SellApp.SdkBatchDeleteSectionsResponseValue200ApplicationJson.to_map() == serialized
  end

  test "SdkBatchUpdateSectionsResponseValue200ApplicationJson round-trips between wire and struct" do
    data = %{
      "data" => [
        %{
          "id" => 1,
          "title" => "title",
          "slug" => nil,
          "hidden" => true,
          "order" => 1,
          "created_at" => "2024-01-01T00:00:00.000Z",
          "updated_at" => "2024-01-01T00:00:00.000Z",
          "store_id" => 1,
          "groups_linked" => 1,
          "products_linked" => 1,
          "groups" => [%{"id" => 1, "title" => "title", "group_products" => 1}],
          "products" => [%{"id" => "id", "title" => "title", "description" => "description"}]
        }
      ]
    }

    serialized =
      data
      |> SellApp.SdkBatchUpdateSectionsResponseValue200ApplicationJson.from_map()
      |> SellApp.SdkBatchUpdateSectionsResponseValue200ApplicationJson.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.SdkBatchUpdateSectionsResponseValue200ApplicationJson.from_map()
           |> SellApp.SdkBatchUpdateSectionsResponseValue200ApplicationJson.to_map() == serialized
  end

  test "SdkCreateSectionResponseValue201ApplicationJson round-trips between wire and struct" do
    data = %{
      "data" => %{
        "id" => 1,
        "title" => "title",
        "slug" => nil,
        "hidden" => true,
        "order" => 1,
        "created_at" => "2024-01-01T00:00:00.000Z",
        "updated_at" => "2024-01-01T00:00:00.000Z",
        "store_id" => 1,
        "groups_linked" => 1,
        "products_linked" => 1,
        "groups" => [%{"id" => 1, "title" => "title", "group_products" => 1}],
        "products" => [%{"id" => "id", "title" => "title", "description" => "description"}]
      }
    }

    serialized =
      data
      |> SellApp.SdkCreateSectionResponseValue201ApplicationJson.from_map()
      |> SellApp.SdkCreateSectionResponseValue201ApplicationJson.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.SdkCreateSectionResponseValue201ApplicationJson.from_map()
           |> SellApp.SdkCreateSectionResponseValue201ApplicationJson.to_map() == serialized
  end

  test "SdkDeleteSectionResponseValue200ApplicationJson round-trips between wire and struct" do
    data = %{
      "data" => %{
        "id" => 1,
        "title" => "title",
        "slug" => nil,
        "hidden" => true,
        "order" => 1,
        "created_at" => "2024-01-01T00:00:00.000Z",
        "updated_at" => "2024-01-01T00:00:00.000Z",
        "store_id" => 1,
        "groups_linked" => 1,
        "products_linked" => 1,
        "groups" => [%{"id" => 1, "title" => "title", "group_products" => 1}],
        "products" => [%{"id" => "id", "title" => "title", "description" => "description"}]
      }
    }

    serialized =
      data
      |> SellApp.SdkDeleteSectionResponseValue200ApplicationJson.from_map()
      |> SellApp.SdkDeleteSectionResponseValue200ApplicationJson.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.SdkDeleteSectionResponseValue200ApplicationJson.from_map()
           |> SellApp.SdkDeleteSectionResponseValue200ApplicationJson.to_map() == serialized
  end

  test "SdkGetSectionResponseValue200ApplicationJson round-trips between wire and struct" do
    data = %{
      "data" => %{
        "id" => 1,
        "title" => "title",
        "slug" => nil,
        "hidden" => true,
        "order" => 1,
        "created_at" => "2024-01-01T00:00:00.000Z",
        "updated_at" => "2024-01-01T00:00:00.000Z",
        "store_id" => 1,
        "groups_linked" => 1,
        "products_linked" => 1,
        "groups" => [%{"id" => 1, "title" => "title", "group_products" => 1}],
        "products" => [%{"id" => "id", "title" => "title", "description" => "description"}]
      }
    }

    serialized =
      data
      |> SellApp.SdkGetSectionResponseValue200ApplicationJson.from_map()
      |> SellApp.SdkGetSectionResponseValue200ApplicationJson.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.SdkGetSectionResponseValue200ApplicationJson.from_map()
           |> SellApp.SdkGetSectionResponseValue200ApplicationJson.to_map() == serialized
  end

  test "SdkListSectionsResponseValue200ApplicationJson round-trips between wire and struct" do
    data = %{
      "data" => [
        %{
          "id" => 1,
          "title" => "title",
          "slug" => nil,
          "hidden" => true,
          "order" => 1,
          "created_at" => "2024-01-01T00:00:00.000Z",
          "updated_at" => "2024-01-01T00:00:00.000Z",
          "store_id" => 1,
          "groups_linked" => 1,
          "products_linked" => 1,
          "groups" => [%{"id" => 1, "title" => "title", "group_products" => 1}],
          "products" => [%{"id" => "id", "title" => "title", "description" => "description"}]
        }
      ],
      "links" => %{"first" => "first", "last" => "last", "prev" => nil, "next" => nil},
      "meta" => %{
        "current_page" => 1,
        "from" => nil,
        "last_page" => 1,
        "links" => [%{"url" => nil, "label" => "label", "active" => true}],
        "path" => "path",
        "per_page" => 1,
        "to" => nil,
        "total" => 1
      }
    }

    serialized =
      data
      |> SellApp.SdkListSectionsResponseValue200ApplicationJson.from_map()
      |> SellApp.SdkListSectionsResponseValue200ApplicationJson.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.SdkListSectionsResponseValue200ApplicationJson.from_map()
           |> SellApp.SdkListSectionsResponseValue200ApplicationJson.to_map() == serialized
  end

  test "SdkReplaceSectionGroupsResponseValue200ApplicationJson round-trips between wire and struct" do
    data = %{
      "data" => %{
        "id" => 1,
        "title" => "title",
        "slug" => nil,
        "hidden" => true,
        "order" => 1,
        "created_at" => "2024-01-01T00:00:00.000Z",
        "updated_at" => "2024-01-01T00:00:00.000Z",
        "store_id" => 1,
        "groups_linked" => 1,
        "products_linked" => 1,
        "groups" => [%{"id" => 1, "title" => "title", "group_products" => 1}],
        "products" => [%{"id" => "id", "title" => "title", "description" => "description"}]
      }
    }

    serialized =
      data
      |> SellApp.SdkReplaceSectionGroupsResponseValue200ApplicationJson.from_map()
      |> SellApp.SdkReplaceSectionGroupsResponseValue200ApplicationJson.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.SdkReplaceSectionGroupsResponseValue200ApplicationJson.from_map()
           |> SellApp.SdkReplaceSectionGroupsResponseValue200ApplicationJson.to_map() ==
             serialized
  end

  test "SdkReplaceSectionOrderResponseValue200ApplicationJson round-trips between wire and struct" do
    data = %{
      "data" => [
        %{
          "id" => 1,
          "title" => "title",
          "slug" => nil,
          "hidden" => true,
          "order" => 1,
          "created_at" => "2024-01-01T00:00:00.000Z",
          "updated_at" => "2024-01-01T00:00:00.000Z",
          "store_id" => 1,
          "groups_linked" => 1,
          "products_linked" => 1,
          "groups" => [%{"id" => 1, "title" => "title", "group_products" => 1}],
          "products" => [%{"id" => "id", "title" => "title", "description" => "description"}]
        }
      ]
    }

    serialized =
      data
      |> SellApp.SdkReplaceSectionOrderResponseValue200ApplicationJson.from_map()
      |> SellApp.SdkReplaceSectionOrderResponseValue200ApplicationJson.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.SdkReplaceSectionOrderResponseValue200ApplicationJson.from_map()
           |> SellApp.SdkReplaceSectionOrderResponseValue200ApplicationJson.to_map() == serialized
  end

  test "SdkReplaceSectionProductsResponseValue200ApplicationJson round-trips between wire and struct" do
    data = %{
      "data" => %{
        "id" => 1,
        "title" => "title",
        "slug" => nil,
        "hidden" => true,
        "order" => 1,
        "created_at" => "2024-01-01T00:00:00.000Z",
        "updated_at" => "2024-01-01T00:00:00.000Z",
        "store_id" => 1,
        "groups_linked" => 1,
        "products_linked" => 1,
        "groups" => [%{"id" => 1, "title" => "title", "group_products" => 1}],
        "products" => [%{"id" => "id", "title" => "title", "description" => "description"}]
      }
    }

    serialized =
      data
      |> SellApp.SdkReplaceSectionProductsResponseValue200ApplicationJson.from_map()
      |> SellApp.SdkReplaceSectionProductsResponseValue200ApplicationJson.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.SdkReplaceSectionProductsResponseValue200ApplicationJson.from_map()
           |> SellApp.SdkReplaceSectionProductsResponseValue200ApplicationJson.to_map() ==
             serialized
  end

  test "SdkReplaceSectionResponseValue200ApplicationJson round-trips between wire and struct" do
    data = %{
      "data" => %{
        "id" => 1,
        "title" => "title",
        "slug" => nil,
        "hidden" => true,
        "order" => 1,
        "created_at" => "2024-01-01T00:00:00.000Z",
        "updated_at" => "2024-01-01T00:00:00.000Z",
        "store_id" => 1,
        "groups_linked" => 1,
        "products_linked" => 1,
        "groups" => [%{"id" => 1, "title" => "title", "group_products" => 1}],
        "products" => [%{"id" => "id", "title" => "title", "description" => "description"}]
      }
    }

    serialized =
      data
      |> SellApp.SdkReplaceSectionResponseValue200ApplicationJson.from_map()
      |> SellApp.SdkReplaceSectionResponseValue200ApplicationJson.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.SdkReplaceSectionResponseValue200ApplicationJson.from_map()
           |> SellApp.SdkReplaceSectionResponseValue200ApplicationJson.to_map() == serialized
  end

  test "SdkSearchSectionsResponseValue200ApplicationJson round-trips between wire and struct" do
    data = %{
      "data" => [
        %{
          "id" => 1,
          "title" => "title",
          "slug" => nil,
          "hidden" => true,
          "order" => 1,
          "created_at" => "2024-01-01T00:00:00.000Z",
          "updated_at" => "2024-01-01T00:00:00.000Z",
          "store_id" => 1,
          "groups_linked" => 1,
          "products_linked" => 1,
          "groups" => [%{"id" => 1, "title" => "title", "group_products" => 1}],
          "products" => [%{"id" => "id", "title" => "title", "description" => "description"}]
        }
      ],
      "links" => %{"first" => "first", "last" => "last", "prev" => nil, "next" => nil},
      "meta" => %{
        "current_page" => 1,
        "from" => nil,
        "last_page" => 1,
        "links" => [%{"url" => nil, "label" => "label", "active" => true}],
        "path" => "path",
        "per_page" => 1,
        "to" => nil,
        "total" => 1
      }
    }

    serialized =
      data
      |> SellApp.SdkSearchSectionsResponseValue200ApplicationJson.from_map()
      |> SellApp.SdkSearchSectionsResponseValue200ApplicationJson.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.SdkSearchSectionsResponseValue200ApplicationJson.from_map()
           |> SellApp.SdkSearchSectionsResponseValue200ApplicationJson.to_map() == serialized
  end

  test "SdkUpdateSectionResponseValue200ApplicationJson round-trips between wire and struct" do
    data = %{
      "data" => %{
        "id" => 1,
        "title" => "title",
        "slug" => nil,
        "hidden" => true,
        "order" => 1,
        "created_at" => "2024-01-01T00:00:00.000Z",
        "updated_at" => "2024-01-01T00:00:00.000Z",
        "store_id" => 1,
        "groups_linked" => 1,
        "products_linked" => 1,
        "groups" => [%{"id" => 1, "title" => "title", "group_products" => 1}],
        "products" => [%{"id" => "id", "title" => "title", "description" => "description"}]
      }
    }

    serialized =
      data
      |> SellApp.SdkUpdateSectionResponseValue200ApplicationJson.from_map()
      |> SellApp.SdkUpdateSectionResponseValue200ApplicationJson.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.SdkUpdateSectionResponseValue200ApplicationJson.from_map()
           |> SellApp.SdkUpdateSectionResponseValue200ApplicationJson.to_map() == serialized
  end

  test "SdkV2BatchCreateSectionsResponseValue200ApplicationJson round-trips between wire and struct" do
    data = %{
      "data" => [
        %{
          "id" => 1,
          "title" => "title",
          "slug" => nil,
          "hidden" => true,
          "order" => 1,
          "created_at" => "2024-01-01T00:00:00.000Z",
          "updated_at" => "2024-01-01T00:00:00.000Z",
          "store_id" => 1,
          "groups_linked" => 1,
          "products_linked" => 1,
          "groups" => [%{"id" => 1, "title" => "title", "group_products" => 1}],
          "products" => [%{"id" => "id", "title" => "title", "description" => "description"}]
        }
      ]
    }

    serialized =
      data
      |> SellApp.SdkV2BatchCreateSectionsResponseValue200ApplicationJson.from_map()
      |> SellApp.SdkV2BatchCreateSectionsResponseValue200ApplicationJson.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.SdkV2BatchCreateSectionsResponseValue200ApplicationJson.from_map()
           |> SellApp.SdkV2BatchCreateSectionsResponseValue200ApplicationJson.to_map() ==
             serialized
  end

  test "SdkV2BatchDeleteSectionsResponseValue200ApplicationJson round-trips between wire and struct" do
    data = %{
      "data" => [
        %{
          "id" => 1,
          "title" => "title",
          "slug" => nil,
          "hidden" => true,
          "order" => 1,
          "created_at" => "2024-01-01T00:00:00.000Z",
          "updated_at" => "2024-01-01T00:00:00.000Z",
          "store_id" => 1,
          "groups_linked" => 1,
          "products_linked" => 1,
          "groups" => [%{"id" => 1, "title" => "title", "group_products" => 1}],
          "products" => [%{"id" => "id", "title" => "title", "description" => "description"}]
        }
      ]
    }

    serialized =
      data
      |> SellApp.SdkV2BatchDeleteSectionsResponseValue200ApplicationJson.from_map()
      |> SellApp.SdkV2BatchDeleteSectionsResponseValue200ApplicationJson.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.SdkV2BatchDeleteSectionsResponseValue200ApplicationJson.from_map()
           |> SellApp.SdkV2BatchDeleteSectionsResponseValue200ApplicationJson.to_map() ==
             serialized
  end

  test "SdkV2BatchUpdateSectionsResponseValue200ApplicationJson round-trips between wire and struct" do
    data = %{
      "data" => [
        %{
          "id" => 1,
          "title" => "title",
          "slug" => nil,
          "hidden" => true,
          "order" => 1,
          "created_at" => "2024-01-01T00:00:00.000Z",
          "updated_at" => "2024-01-01T00:00:00.000Z",
          "store_id" => 1,
          "groups_linked" => 1,
          "products_linked" => 1,
          "groups" => [%{"id" => 1, "title" => "title", "group_products" => 1}],
          "products" => [%{"id" => "id", "title" => "title", "description" => "description"}]
        }
      ]
    }

    serialized =
      data
      |> SellApp.SdkV2BatchUpdateSectionsResponseValue200ApplicationJson.from_map()
      |> SellApp.SdkV2BatchUpdateSectionsResponseValue200ApplicationJson.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.SdkV2BatchUpdateSectionsResponseValue200ApplicationJson.from_map()
           |> SellApp.SdkV2BatchUpdateSectionsResponseValue200ApplicationJson.to_map() ==
             serialized
  end

  test "SdkV2CreateSectionResponseValue201ApplicationJson round-trips between wire and struct" do
    data = %{
      "data" => %{
        "id" => 1,
        "title" => "title",
        "slug" => nil,
        "hidden" => true,
        "order" => 1,
        "created_at" => "2024-01-01T00:00:00.000Z",
        "updated_at" => "2024-01-01T00:00:00.000Z",
        "store_id" => 1,
        "groups_linked" => 1,
        "products_linked" => 1,
        "groups" => [%{"id" => 1, "title" => "title", "group_products" => 1}],
        "products" => [%{"id" => "id", "title" => "title", "description" => "description"}]
      }
    }

    serialized =
      data
      |> SellApp.SdkV2CreateSectionResponseValue201ApplicationJson.from_map()
      |> SellApp.SdkV2CreateSectionResponseValue201ApplicationJson.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.SdkV2CreateSectionResponseValue201ApplicationJson.from_map()
           |> SellApp.SdkV2CreateSectionResponseValue201ApplicationJson.to_map() == serialized
  end

  test "SdkV2DeleteSectionResponseValue200ApplicationJson round-trips between wire and struct" do
    data = %{
      "data" => %{
        "id" => 1,
        "title" => "title",
        "slug" => nil,
        "hidden" => true,
        "order" => 1,
        "created_at" => "2024-01-01T00:00:00.000Z",
        "updated_at" => "2024-01-01T00:00:00.000Z",
        "store_id" => 1,
        "groups_linked" => 1,
        "products_linked" => 1,
        "groups" => [%{"id" => 1, "title" => "title", "group_products" => 1}],
        "products" => [%{"id" => "id", "title" => "title", "description" => "description"}]
      }
    }

    serialized =
      data
      |> SellApp.SdkV2DeleteSectionResponseValue200ApplicationJson.from_map()
      |> SellApp.SdkV2DeleteSectionResponseValue200ApplicationJson.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.SdkV2DeleteSectionResponseValue200ApplicationJson.from_map()
           |> SellApp.SdkV2DeleteSectionResponseValue200ApplicationJson.to_map() == serialized
  end

  test "SdkV2GetSectionResponseValue200ApplicationJson round-trips between wire and struct" do
    data = %{
      "data" => %{
        "id" => 1,
        "title" => "title",
        "slug" => nil,
        "hidden" => true,
        "order" => 1,
        "created_at" => "2024-01-01T00:00:00.000Z",
        "updated_at" => "2024-01-01T00:00:00.000Z",
        "store_id" => 1,
        "groups_linked" => 1,
        "products_linked" => 1,
        "groups" => [%{"id" => 1, "title" => "title", "group_products" => 1}],
        "products" => [%{"id" => "id", "title" => "title", "description" => "description"}]
      }
    }

    serialized =
      data
      |> SellApp.SdkV2GetSectionResponseValue200ApplicationJson.from_map()
      |> SellApp.SdkV2GetSectionResponseValue200ApplicationJson.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.SdkV2GetSectionResponseValue200ApplicationJson.from_map()
           |> SellApp.SdkV2GetSectionResponseValue200ApplicationJson.to_map() == serialized
  end

  test "SdkV2ListSectionsResponseValue200ApplicationJson round-trips between wire and struct" do
    data = %{
      "data" => [
        %{
          "id" => 1,
          "title" => "title",
          "slug" => nil,
          "hidden" => true,
          "order" => 1,
          "created_at" => "2024-01-01T00:00:00.000Z",
          "updated_at" => "2024-01-01T00:00:00.000Z",
          "store_id" => 1,
          "groups_linked" => 1,
          "products_linked" => 1,
          "groups" => [%{"id" => 1, "title" => "title", "group_products" => 1}],
          "products" => [%{"id" => "id", "title" => "title", "description" => "description"}]
        }
      ],
      "links" => %{"first" => "first", "last" => "last", "prev" => nil, "next" => nil},
      "meta" => %{
        "current_page" => 1,
        "from" => nil,
        "last_page" => 1,
        "links" => [%{"url" => nil, "label" => "label", "active" => true}],
        "path" => "path",
        "per_page" => 1,
        "to" => nil,
        "total" => 1
      }
    }

    serialized =
      data
      |> SellApp.SdkV2ListSectionsResponseValue200ApplicationJson.from_map()
      |> SellApp.SdkV2ListSectionsResponseValue200ApplicationJson.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.SdkV2ListSectionsResponseValue200ApplicationJson.from_map()
           |> SellApp.SdkV2ListSectionsResponseValue200ApplicationJson.to_map() == serialized
  end

  test "SdkV2ReplaceSectionGroupsResponseValue200ApplicationJson round-trips between wire and struct" do
    data = %{
      "data" => %{
        "id" => 1,
        "title" => "title",
        "slug" => nil,
        "hidden" => true,
        "order" => 1,
        "created_at" => "2024-01-01T00:00:00.000Z",
        "updated_at" => "2024-01-01T00:00:00.000Z",
        "store_id" => 1,
        "groups_linked" => 1,
        "products_linked" => 1,
        "groups" => [%{"id" => 1, "title" => "title", "group_products" => 1}],
        "products" => [%{"id" => "id", "title" => "title", "description" => "description"}]
      }
    }

    serialized =
      data
      |> SellApp.SdkV2ReplaceSectionGroupsResponseValue200ApplicationJson.from_map()
      |> SellApp.SdkV2ReplaceSectionGroupsResponseValue200ApplicationJson.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.SdkV2ReplaceSectionGroupsResponseValue200ApplicationJson.from_map()
           |> SellApp.SdkV2ReplaceSectionGroupsResponseValue200ApplicationJson.to_map() ==
             serialized
  end

  test "SdkV2ReplaceSectionOrderResponseValue200ApplicationJson round-trips between wire and struct" do
    data = %{
      "data" => [
        %{
          "id" => 1,
          "title" => "title",
          "slug" => nil,
          "hidden" => true,
          "order" => 1,
          "created_at" => "2024-01-01T00:00:00.000Z",
          "updated_at" => "2024-01-01T00:00:00.000Z",
          "store_id" => 1,
          "groups_linked" => 1,
          "products_linked" => 1,
          "groups" => [%{"id" => 1, "title" => "title", "group_products" => 1}],
          "products" => [%{"id" => "id", "title" => "title", "description" => "description"}]
        }
      ]
    }

    serialized =
      data
      |> SellApp.SdkV2ReplaceSectionOrderResponseValue200ApplicationJson.from_map()
      |> SellApp.SdkV2ReplaceSectionOrderResponseValue200ApplicationJson.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.SdkV2ReplaceSectionOrderResponseValue200ApplicationJson.from_map()
           |> SellApp.SdkV2ReplaceSectionOrderResponseValue200ApplicationJson.to_map() ==
             serialized
  end

  test "SdkV2ReplaceSectionProductsResponseValue200ApplicationJson round-trips between wire and struct" do
    data = %{
      "data" => %{
        "id" => 1,
        "title" => "title",
        "slug" => nil,
        "hidden" => true,
        "order" => 1,
        "created_at" => "2024-01-01T00:00:00.000Z",
        "updated_at" => "2024-01-01T00:00:00.000Z",
        "store_id" => 1,
        "groups_linked" => 1,
        "products_linked" => 1,
        "groups" => [%{"id" => 1, "title" => "title", "group_products" => 1}],
        "products" => [%{"id" => "id", "title" => "title", "description" => "description"}]
      }
    }

    serialized =
      data
      |> SellApp.SdkV2ReplaceSectionProductsResponseValue200ApplicationJson.from_map()
      |> SellApp.SdkV2ReplaceSectionProductsResponseValue200ApplicationJson.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.SdkV2ReplaceSectionProductsResponseValue200ApplicationJson.from_map()
           |> SellApp.SdkV2ReplaceSectionProductsResponseValue200ApplicationJson.to_map() ==
             serialized
  end

  test "SdkV2ReplaceSectionResponseValue200ApplicationJson round-trips between wire and struct" do
    data = %{
      "data" => %{
        "id" => 1,
        "title" => "title",
        "slug" => nil,
        "hidden" => true,
        "order" => 1,
        "created_at" => "2024-01-01T00:00:00.000Z",
        "updated_at" => "2024-01-01T00:00:00.000Z",
        "store_id" => 1,
        "groups_linked" => 1,
        "products_linked" => 1,
        "groups" => [%{"id" => 1, "title" => "title", "group_products" => 1}],
        "products" => [%{"id" => "id", "title" => "title", "description" => "description"}]
      }
    }

    serialized =
      data
      |> SellApp.SdkV2ReplaceSectionResponseValue200ApplicationJson.from_map()
      |> SellApp.SdkV2ReplaceSectionResponseValue200ApplicationJson.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.SdkV2ReplaceSectionResponseValue200ApplicationJson.from_map()
           |> SellApp.SdkV2ReplaceSectionResponseValue200ApplicationJson.to_map() == serialized
  end

  test "SdkV2SearchSectionsResponseValue200ApplicationJson round-trips between wire and struct" do
    data = %{
      "data" => [
        %{
          "id" => 1,
          "title" => "title",
          "slug" => nil,
          "hidden" => true,
          "order" => 1,
          "created_at" => "2024-01-01T00:00:00.000Z",
          "updated_at" => "2024-01-01T00:00:00.000Z",
          "store_id" => 1,
          "groups_linked" => 1,
          "products_linked" => 1,
          "groups" => [%{"id" => 1, "title" => "title", "group_products" => 1}],
          "products" => [%{"id" => "id", "title" => "title", "description" => "description"}]
        }
      ],
      "links" => %{"first" => "first", "last" => "last", "prev" => nil, "next" => nil},
      "meta" => %{
        "current_page" => 1,
        "from" => nil,
        "last_page" => 1,
        "links" => [%{"url" => nil, "label" => "label", "active" => true}],
        "path" => "path",
        "per_page" => 1,
        "to" => nil,
        "total" => 1
      }
    }

    serialized =
      data
      |> SellApp.SdkV2SearchSectionsResponseValue200ApplicationJson.from_map()
      |> SellApp.SdkV2SearchSectionsResponseValue200ApplicationJson.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.SdkV2SearchSectionsResponseValue200ApplicationJson.from_map()
           |> SellApp.SdkV2SearchSectionsResponseValue200ApplicationJson.to_map() == serialized
  end

  test "SdkV2UpdateSectionResponseValue200ApplicationJson round-trips between wire and struct" do
    data = %{
      "data" => %{
        "id" => 1,
        "title" => "title",
        "slug" => nil,
        "hidden" => true,
        "order" => 1,
        "created_at" => "2024-01-01T00:00:00.000Z",
        "updated_at" => "2024-01-01T00:00:00.000Z",
        "store_id" => 1,
        "groups_linked" => 1,
        "products_linked" => 1,
        "groups" => [%{"id" => 1, "title" => "title", "group_products" => 1}],
        "products" => [%{"id" => "id", "title" => "title", "description" => "description"}]
      }
    }

    serialized =
      data
      |> SellApp.SdkV2UpdateSectionResponseValue200ApplicationJson.from_map()
      |> SellApp.SdkV2UpdateSectionResponseValue200ApplicationJson.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.SdkV2UpdateSectionResponseValue200ApplicationJson.from_map()
           |> SellApp.SdkV2UpdateSectionResponseValue200ApplicationJson.to_map() == serialized
  end

  test "SearchSectionsResponseValue200ApplicationJsonPropertyDataItem round-trips between wire and struct" do
    data = %{
      "id" => 1,
      "title" => "title",
      "slug" => nil,
      "hidden" => true,
      "order" => 1,
      "created_at" => "2024-01-01T00:00:00.000Z",
      "updated_at" => "2024-01-01T00:00:00.000Z",
      "store_id" => 1,
      "groups_linked" => 1,
      "products_linked" => 1,
      "groups" => [%{"id" => 1, "title" => "title", "group_products" => 1}],
      "products" => [%{"id" => "id", "title" => "title", "description" => "description"}]
    }

    serialized =
      data
      |> SellApp.SearchSectionsResponseValue200ApplicationJsonPropertyDataItem.from_map()
      |> SellApp.SearchSectionsResponseValue200ApplicationJsonPropertyDataItem.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.SearchSectionsResponseValue200ApplicationJsonPropertyDataItem.from_map()
           |> SellApp.SearchSectionsResponseValue200ApplicationJsonPropertyDataItem.to_map() ==
             serialized
  end

  test "V2ListSectionsResponseValue200ApplicationJsonPropertyDataItem round-trips between wire and struct" do
    data = %{
      "id" => 1,
      "title" => "title",
      "slug" => nil,
      "hidden" => true,
      "order" => 1,
      "created_at" => "2024-01-01T00:00:00.000Z",
      "updated_at" => "2024-01-01T00:00:00.000Z",
      "store_id" => 1,
      "groups_linked" => 1,
      "products_linked" => 1,
      "groups" => [%{"id" => 1, "title" => "title", "group_products" => 1}],
      "products" => [%{"id" => "id", "title" => "title", "description" => "description"}]
    }

    serialized =
      data
      |> SellApp.V2ListSectionsResponseValue200ApplicationJsonPropertyDataItem.from_map()
      |> SellApp.V2ListSectionsResponseValue200ApplicationJsonPropertyDataItem.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.V2ListSectionsResponseValue200ApplicationJsonPropertyDataItem.from_map()
           |> SellApp.V2ListSectionsResponseValue200ApplicationJsonPropertyDataItem.to_map() ==
             serialized
  end

  test "V2SearchSectionsResponseValue200ApplicationJsonPropertyDataItem round-trips between wire and struct" do
    data = %{
      "id" => 1,
      "title" => "title",
      "slug" => nil,
      "hidden" => true,
      "order" => 1,
      "created_at" => "2024-01-01T00:00:00.000Z",
      "updated_at" => "2024-01-01T00:00:00.000Z",
      "store_id" => 1,
      "groups_linked" => 1,
      "products_linked" => 1,
      "groups" => [%{"id" => 1, "title" => "title", "group_products" => 1}],
      "products" => [%{"id" => "id", "title" => "title", "description" => "description"}]
    }

    serialized =
      data
      |> SellApp.V2SearchSectionsResponseValue200ApplicationJsonPropertyDataItem.from_map()
      |> SellApp.V2SearchSectionsResponseValue200ApplicationJsonPropertyDataItem.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.V2SearchSectionsResponseValue200ApplicationJsonPropertyDataItem.from_map()
           |> SellApp.V2SearchSectionsResponseValue200ApplicationJsonPropertyDataItem.to_map() ==
             serialized
  end
end
