# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.UpsellOffersRoundTripTest do
  use ExUnit.Case, async: true

  test "SdkCreateUpsellOfferResponseValue201ApplicationJson round-trips between wire and struct" do
    data = %{
      "data" => %{
        "id" => 1,
        "name" => "name",
        "description" => nil,
        "is_active" => true,
        "source_listing_id" => 1,
        "source_variant_id" => nil,
        "minimum_order_total_usd_cents" => nil,
        "maximum_order_total_usd_cents" => nil,
        "starts_at" => nil,
        "ends_at" => nil,
        "available_for_days" => nil,
        "max_accepts_per_customer" => nil,
        "sort_order" => 1,
        "version" => 1,
        "source_product" => nil,
        "source_variant" => nil,
        "items" => [
          %{
            "id" => 1,
            "target_listing_id" => 1,
            "target_variant_id" => 1,
            "headline" => nil,
            "description" => nil,
            "discount_type" => nil,
            "discount_value" => nil,
            "maximum_discount_amount" => nil,
            "sort_order" => 1,
            "target_product" => nil,
            "target_variant" => nil,
            "created_at" => nil,
            "updated_at" => nil
          }
        ],
        "created_at" => nil,
        "updated_at" => nil,
        "deleted_at" => nil
      }
    }

    serialized =
      data
      |> SellApp.SdkCreateUpsellOfferResponseValue201ApplicationJson.from_map()
      |> SellApp.SdkCreateUpsellOfferResponseValue201ApplicationJson.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.SdkCreateUpsellOfferResponseValue201ApplicationJson.from_map()
           |> SellApp.SdkCreateUpsellOfferResponseValue201ApplicationJson.to_map() == serialized
  end

  test "SdkDeleteUpsellOfferResponseValue200ApplicationJson round-trips between wire and struct" do
    data = %{
      "data" => %{
        "id" => 1,
        "name" => "name",
        "description" => nil,
        "is_active" => true,
        "source_listing_id" => 1,
        "source_variant_id" => nil,
        "minimum_order_total_usd_cents" => nil,
        "maximum_order_total_usd_cents" => nil,
        "starts_at" => nil,
        "ends_at" => nil,
        "available_for_days" => nil,
        "max_accepts_per_customer" => nil,
        "sort_order" => 1,
        "version" => 1,
        "source_product" => nil,
        "source_variant" => nil,
        "items" => [
          %{
            "id" => 1,
            "target_listing_id" => 1,
            "target_variant_id" => 1,
            "headline" => nil,
            "description" => nil,
            "discount_type" => nil,
            "discount_value" => nil,
            "maximum_discount_amount" => nil,
            "sort_order" => 1,
            "target_product" => nil,
            "target_variant" => nil,
            "created_at" => nil,
            "updated_at" => nil
          }
        ],
        "created_at" => nil,
        "updated_at" => nil,
        "deleted_at" => nil
      }
    }

    serialized =
      data
      |> SellApp.SdkDeleteUpsellOfferResponseValue200ApplicationJson.from_map()
      |> SellApp.SdkDeleteUpsellOfferResponseValue200ApplicationJson.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.SdkDeleteUpsellOfferResponseValue200ApplicationJson.from_map()
           |> SellApp.SdkDeleteUpsellOfferResponseValue200ApplicationJson.to_map() == serialized
  end

  test "SdkGetUpsellOfferResponseValue200ApplicationJson round-trips between wire and struct" do
    data = %{
      "data" => %{
        "id" => 1,
        "name" => "name",
        "description" => nil,
        "is_active" => true,
        "source_listing_id" => 1,
        "source_variant_id" => nil,
        "minimum_order_total_usd_cents" => nil,
        "maximum_order_total_usd_cents" => nil,
        "starts_at" => nil,
        "ends_at" => nil,
        "available_for_days" => nil,
        "max_accepts_per_customer" => nil,
        "sort_order" => 1,
        "version" => 1,
        "source_product" => nil,
        "source_variant" => nil,
        "items" => [
          %{
            "id" => 1,
            "target_listing_id" => 1,
            "target_variant_id" => 1,
            "headline" => nil,
            "description" => nil,
            "discount_type" => nil,
            "discount_value" => nil,
            "maximum_discount_amount" => nil,
            "sort_order" => 1,
            "target_product" => nil,
            "target_variant" => nil,
            "created_at" => nil,
            "updated_at" => nil
          }
        ],
        "created_at" => nil,
        "updated_at" => nil,
        "deleted_at" => nil
      }
    }

    serialized =
      data
      |> SellApp.SdkGetUpsellOfferResponseValue200ApplicationJson.from_map()
      |> SellApp.SdkGetUpsellOfferResponseValue200ApplicationJson.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.SdkGetUpsellOfferResponseValue200ApplicationJson.from_map()
           |> SellApp.SdkGetUpsellOfferResponseValue200ApplicationJson.to_map() == serialized
  end

  test "SdkReplaceUpsellOfferResponseValue200ApplicationJson round-trips between wire and struct" do
    data = %{
      "data" => %{
        "id" => 1,
        "name" => "name",
        "description" => nil,
        "is_active" => true,
        "source_listing_id" => 1,
        "source_variant_id" => nil,
        "minimum_order_total_usd_cents" => nil,
        "maximum_order_total_usd_cents" => nil,
        "starts_at" => nil,
        "ends_at" => nil,
        "available_for_days" => nil,
        "max_accepts_per_customer" => nil,
        "sort_order" => 1,
        "version" => 1,
        "source_product" => nil,
        "source_variant" => nil,
        "items" => [
          %{
            "id" => 1,
            "target_listing_id" => 1,
            "target_variant_id" => 1,
            "headline" => nil,
            "description" => nil,
            "discount_type" => nil,
            "discount_value" => nil,
            "maximum_discount_amount" => nil,
            "sort_order" => 1,
            "target_product" => nil,
            "target_variant" => nil,
            "created_at" => nil,
            "updated_at" => nil
          }
        ],
        "created_at" => nil,
        "updated_at" => nil,
        "deleted_at" => nil
      }
    }

    serialized =
      data
      |> SellApp.SdkReplaceUpsellOfferResponseValue200ApplicationJson.from_map()
      |> SellApp.SdkReplaceUpsellOfferResponseValue200ApplicationJson.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.SdkReplaceUpsellOfferResponseValue200ApplicationJson.from_map()
           |> SellApp.SdkReplaceUpsellOfferResponseValue200ApplicationJson.to_map() == serialized
  end

  test "SdkUpdateUpsellOfferResponseValue200ApplicationJson round-trips between wire and struct" do
    data = %{
      "data" => %{
        "id" => 1,
        "name" => "name",
        "description" => nil,
        "is_active" => true,
        "source_listing_id" => 1,
        "source_variant_id" => nil,
        "minimum_order_total_usd_cents" => nil,
        "maximum_order_total_usd_cents" => nil,
        "starts_at" => nil,
        "ends_at" => nil,
        "available_for_days" => nil,
        "max_accepts_per_customer" => nil,
        "sort_order" => 1,
        "version" => 1,
        "source_product" => nil,
        "source_variant" => nil,
        "items" => [
          %{
            "id" => 1,
            "target_listing_id" => 1,
            "target_variant_id" => 1,
            "headline" => nil,
            "description" => nil,
            "discount_type" => nil,
            "discount_value" => nil,
            "maximum_discount_amount" => nil,
            "sort_order" => 1,
            "target_product" => nil,
            "target_variant" => nil,
            "created_at" => nil,
            "updated_at" => nil
          }
        ],
        "created_at" => nil,
        "updated_at" => nil,
        "deleted_at" => nil
      }
    }

    serialized =
      data
      |> SellApp.SdkUpdateUpsellOfferResponseValue200ApplicationJson.from_map()
      |> SellApp.SdkUpdateUpsellOfferResponseValue200ApplicationJson.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.SdkUpdateUpsellOfferResponseValue200ApplicationJson.from_map()
           |> SellApp.SdkUpdateUpsellOfferResponseValue200ApplicationJson.to_map() == serialized
  end
end
