# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.WalletSettingsRoundTripTest do
  use ExUnit.Case, async: true

  test "SdkGetWalletSettingsResponseValue200ApplicationJson round-trips between wire and struct" do
    data = %{
      "data" => %{
        "enabled" => true,
        "minimum_top_up_cents" => nil,
        "maximum_top_up_cents" => nil,
        "expiration_days" => nil,
        "payment_methods" => ["payment_methods"]
      }
    }

    serialized =
      data
      |> SellApp.SdkGetWalletSettingsResponseValue200ApplicationJson.from_map()
      |> SellApp.SdkGetWalletSettingsResponseValue200ApplicationJson.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.SdkGetWalletSettingsResponseValue200ApplicationJson.from_map()
           |> SellApp.SdkGetWalletSettingsResponseValue200ApplicationJson.to_map() == serialized
  end

  test "SdkReplaceWalletSettingsResponseValue200ApplicationJson round-trips between wire and struct" do
    data = %{
      "data" => %{
        "enabled" => true,
        "minimum_top_up_cents" => nil,
        "maximum_top_up_cents" => nil,
        "expiration_days" => nil,
        "payment_methods" => ["payment_methods"]
      }
    }

    serialized =
      data
      |> SellApp.SdkReplaceWalletSettingsResponseValue200ApplicationJson.from_map()
      |> SellApp.SdkReplaceWalletSettingsResponseValue200ApplicationJson.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.SdkReplaceWalletSettingsResponseValue200ApplicationJson.from_map()
           |> SellApp.SdkReplaceWalletSettingsResponseValue200ApplicationJson.to_map() ==
             serialized
  end
end
