# This file is auto-generated by oagen. Do not edit.

defmodule SellApp.WalletTopupsRoundTripTest do
  use ExUnit.Case, async: true

  test "SdkCreateWalletTopUpResponseValue201ApplicationJson round-trips between wire and struct" do
    data = %{
      "data" => %{
        "charge_id" => 1,
        "amount_cents" => 1,
        "currency" => "USD",
        "checkout_url" => "checkout_url",
        "payment_method" => "AUTHNET",
        "custom_payment_method_id" => nil
      }
    }

    serialized =
      data
      |> SellApp.SdkCreateWalletTopUpResponseValue201ApplicationJson.from_map()
      |> SellApp.SdkCreateWalletTopUpResponseValue201ApplicationJson.to_map()

    assert serialized == data

    assert serialized
           |> SellApp.SdkCreateWalletTopUpResponseValue201ApplicationJson.from_map()
           |> SellApp.SdkCreateWalletTopUpResponseValue201ApplicationJson.to_map() == serialized
  end
end
